{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.cauly.adapter",
    "module": "cauly-sdk-uat",
    "version": "3.5.39.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.39.8.aar",
          "url": "cauly-sdk-uat-3.5.39.8.aar",
          "size": 20635,
          "sha512": "6e3cd636963e879c3b329548c1decbbfcdf482a1ab2763874f3f7e422d7484e578bdb8105a766d5a3ef56488cac0c89ad68d5eee81e6635d8f496d0fb616b5cf",
          "sha256": "8e92547bd11da991e839fac9daf9747507f9c9b2255a1fee8c64312e6068274c",
          "sha1": "a93231690a1db42a4d261b32d6d991dbd254468d",
          "md5": "0741f4012bb4b1ee031b50bfe2da953e"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "com.fsn.cauly",
          "module": "cauly-sdk-uat",
          "version": {
            "requires": "3.5.39"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.39.8.aar",
          "url": "cauly-sdk-uat-3.5.39.8.aar",
          "size": 20635,
          "sha512": "6e3cd636963e879c3b329548c1decbbfcdf482a1ab2763874f3f7e422d7484e578bdb8105a766d5a3ef56488cac0c89ad68d5eee81e6635d8f496d0fb616b5cf",
          "sha256": "8e92547bd11da991e839fac9daf9747507f9c9b2255a1fee8c64312e6068274c",
          "sha1": "a93231690a1db42a4d261b32d6d991dbd254468d",
          "md5": "0741f4012bb4b1ee031b50bfe2da953e"
        }
      ]
    }
  ]
}
