{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.cauly.adapter",
    "module": "cauly-sdk-uat",
    "version": "3.5.39.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.39.8.aar",
          "url": "cauly-sdk-uat-3.5.39.8.aar",
          "size": 20635,
          "sha512": "ef0162f853e90ed11773a51e893d602f23237774dc79768bb885f87ab17f2c7dec6745ce1242190dddde7038ee1238906503c250cb4be5b2a7b7e77f37dfda7d",
          "sha256": "1fd3b486729c7acb60d597458b2e8cbcc436058743d7bf5e871b12d874da7e62",
          "sha1": "5ad3e27c0a9da7115393235a5304bd1bc94dab47",
          "md5": "2a15dd10c1052c672b0efa7b013597df"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "com.fsn.cauly",
          "module": "cauly-sdk-uat",
          "version": {
            "requires": "3.5.39"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.39.8.aar",
          "url": "cauly-sdk-uat-3.5.39.8.aar",
          "size": 20635,
          "sha512": "ef0162f853e90ed11773a51e893d602f23237774dc79768bb885f87ab17f2c7dec6745ce1242190dddde7038ee1238906503c250cb4be5b2a7b7e77f37dfda7d",
          "sha256": "1fd3b486729c7acb60d597458b2e8cbcc436058743d7bf5e871b12d874da7e62",
          "sha1": "5ad3e27c0a9da7115393235a5304bd1bc94dab47",
          "md5": "2a15dd10c1052c672b0efa7b013597df"
        }
      ]
    }
  ]
}
