{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk-uat",
    "version": "8.12.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-uat-8.12.0.4.aar",
          "url": "levelplay-sdk-uat-8.12.0.4.aar",
          "size": 57271,
          "sha512": "f47965800fd18d7b090fb677d3fbdd1d20f50272b41443135e648e1e004f2375089e18d5f9cb13c6d1d7c109c193febe1785e1bee823bf02e82d1e15825f61c9",
          "sha256": "11637102752d775ac8d8a163484d6427fc79eaa13f2f9c5a7697647dff83b5e6",
          "sha1": "e4a90f1ec6ac4827b557ea9eeca937161709947d",
          "md5": "f140941b11e0e33cf520eb2cc0b73ac7"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-uat-8.12.0.4.aar",
          "url": "levelplay-sdk-uat-8.12.0.4.aar",
          "size": 57271,
          "sha512": "f47965800fd18d7b090fb677d3fbdd1d20f50272b41443135e648e1e004f2375089e18d5f9cb13c6d1d7c109c193febe1785e1bee823bf02e82d1e15825f61c9",
          "sha256": "11637102752d775ac8d8a163484d6427fc79eaa13f2f9c5a7697647dff83b5e6",
          "sha1": "e4a90f1ec6ac4827b557ea9eeca937161709947d",
          "md5": "f140941b11e0e33cf520eb2cc0b73ac7"
        }
      ]
    }
  ]
}
