{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk-uat",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.6.0.aar",
          "url": "adwhale-core-sdk-uat-2.6.0.aar",
          "size": 40360,
          "sha512": "2407970cb41d05396b9c9e185d5f95ef5f855615ac36c1f337bcc00ba0df8effd8b84d3e14a3000d571fb21121c122c2eeddb17e37f9e48967e93aa57d7f603d",
          "sha256": "67374ba1bfed9db93392018e73387dfa2125fcbb2ccf59130be26fa251c18b07",
          "sha1": "c9b94fbaef9d5ab95717aff8f21e9a64bae93f9d",
          "md5": "61d51ad3fc66b0095d097ec6ff11ce63"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.6.0.aar",
          "url": "adwhale-core-sdk-uat-2.6.0.aar",
          "size": 40360,
          "sha512": "2407970cb41d05396b9c9e185d5f95ef5f855615ac36c1f337bcc00ba0df8effd8b84d3e14a3000d571fb21121c122c2eeddb17e37f9e48967e93aa57d7f603d",
          "sha256": "67374ba1bfed9db93392018e73387dfa2125fcbb2ccf59130be26fa251c18b07",
          "sha1": "c9b94fbaef9d5ab95717aff8f21e9a64bae93f9d",
          "md5": "61d51ad3fc66b0095d097ec6ff11ce63"
        }
      ]
    }
  ]
}
