{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk-uat",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.6.0.aar",
          "url": "adwhale-core-sdk-uat-2.6.0.aar",
          "size": 40256,
          "sha512": "8b82efe9a7d8f615aa7deb1991e09f49145f739e9ed0440e2cce092a297abdfb7149779830ae65da1b8b2c95bc43710e8e61d55d4dec2c94e743a3365a430181",
          "sha256": "47eee0f88c8c85f64185680eb9c55c88dd6343e760b0c5d7983a4491c30ffe97",
          "sha1": "843cd229a1cb6c8b5ed3ce56fc90d614369ce6d8",
          "md5": "bbd99846ab2238239284e90875a89250"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.6.0.aar",
          "url": "adwhale-core-sdk-uat-2.6.0.aar",
          "size": 40256,
          "sha512": "8b82efe9a7d8f615aa7deb1991e09f49145f739e9ed0440e2cce092a297abdfb7149779830ae65da1b8b2c95bc43710e8e61d55d4dec2c94e743a3365a430181",
          "sha256": "47eee0f88c8c85f64185680eb9c55c88dd6343e760b0c5d7983a4491c30ffe97",
          "sha1": "843cd229a1cb6c8b5ed3ce56fc90d614369ce6d8",
          "md5": "bbd99846ab2238239284e90875a89250"
        }
      ]
    }
  ]
}
