{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk-uat",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.6.0.aar",
          "url": "adwhale-core-sdk-uat-2.6.0.aar",
          "size": 40471,
          "sha512": "c113b6d65884bea8db0c33c7e80e9954730d83ca50c820d88a0da23fe0369cffd3487ffc55d4a836c20879cecdc5b16395c5d3eae91646027f5593d4a9495caa",
          "sha256": "90ab0cd1f73987819056ff55f5f0934497e864250754a50fa7cb82ee3aeef6d4",
          "sha1": "fbd27a76d14a9f794e6200e1359ade5d30343815",
          "md5": "3c45b94cef1cec57eaf18ea3d74c2949"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.6.0.aar",
          "url": "adwhale-core-sdk-uat-2.6.0.aar",
          "size": 40471,
          "sha512": "c113b6d65884bea8db0c33c7e80e9954730d83ca50c820d88a0da23fe0369cffd3487ffc55d4a836c20879cecdc5b16395c5d3eae91646027f5593d4a9495caa",
          "sha256": "90ab0cd1f73987819056ff55f5f0934497e864250754a50fa7cb82ee3aeef6d4",
          "sha1": "fbd27a76d14a9f794e6200e1359ade5d30343815",
          "md5": "3c45b94cef1cec57eaf18ea3d74c2949"
        }
      ]
    }
  ]
}
