{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.cauly.adapter",
    "module": "cauly-sdk-uat",
    "version": "3.5.40.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.40.0.aar",
          "url": "cauly-sdk-uat-3.5.40.0.aar",
          "size": 22711,
          "sha512": "450be19ec5d0841996c0a3c21be8e22c262ebbee2a24b583e02dcdf2a1e171a7670b374e2dd7937bd2b5e732e65eda8956fa39a49cda1747d0677fb619129858",
          "sha256": "2990fc462bf918fe1720f76659adf45546f2c8e97ea9b9a1b32da4f04775d438",
          "sha1": "e272aa376bb6042ed0a4f48ba39de14863b2a411",
          "md5": "6014469835986a11eed9776497738b28"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.fsn.cauly",
          "module": "cauly-sdk-uat",
          "version": {
            "requires": "3.5.40"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.40.0.aar",
          "url": "cauly-sdk-uat-3.5.40.0.aar",
          "size": 22711,
          "sha512": "450be19ec5d0841996c0a3c21be8e22c262ebbee2a24b583e02dcdf2a1e171a7670b374e2dd7937bd2b5e732e65eda8956fa39a49cda1747d0677fb619129858",
          "sha256": "2990fc462bf918fe1720f76659adf45546f2c8e97ea9b9a1b32da4f04775d438",
          "sha1": "e272aa376bb6042ed0a4f48ba39de14863b2a411",
          "md5": "6014469835986a11eed9776497738b28"
        }
      ]
    }
  ]
}
