{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk-uat",
    "version": "8.7.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.5.aar",
          "url": "levelplay-sdk-uat-8.7.0.5.aar",
          "size": 55666,
          "sha512": "8ccadff47ff53a87f7e6963d2436f7f734656d3056e1190896860bc6d76531f6cd5233dddfd87565dcd0b295e293697da309aabb9942f2da5d95fd7ae9e6671b",
          "sha256": "aad08d1d910304f566cc49309a5b46006bd5512e12942d2bd9d90f834f576ac6",
          "sha1": "623e7ac75013dba13cca31beb9fb129a157979a8",
          "md5": "1d7324baa27bbeaa5d0beb4f9b5c947e"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.5.aar",
          "url": "levelplay-sdk-uat-8.7.0.5.aar",
          "size": 55666,
          "sha512": "8ccadff47ff53a87f7e6963d2436f7f734656d3056e1190896860bc6d76531f6cd5233dddfd87565dcd0b295e293697da309aabb9942f2da5d95fd7ae9e6671b",
          "sha256": "aad08d1d910304f566cc49309a5b46006bd5512e12942d2bd9d90f834f576ac6",
          "sha1": "623e7ac75013dba13cca31beb9fb129a157979a8",
          "md5": "1d7324baa27bbeaa5d0beb4f9b5c947e"
        }
      ]
    }
  ]
}
