{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk-uat",
    "version": "3.21.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-uat-3.21.17.1.aar",
          "url": "adfit-sdk-uat-3.21.17.1.aar",
          "size": 28842,
          "sha512": "3555093fa8dce2c100e01b57104b52cca0ae9bb35e329ebc2f8ed707a4a33c249bd19e7908e0fc23563bf3bdaaa3955e132c6fffb44d919c6ff516f2d52cdf40",
          "sha256": "07c51a02088e2e18b85a591c860bf8fe9480939d2b698dea2e32221009c9c977",
          "sha1": "1b83f829ac8b9df09e0d95891b1e6e5103dcaf79",
          "md5": "5dfd94c9dfedcba35abe724b492d9aae"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.21.17"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-uat-3.21.17.1.aar",
          "url": "adfit-sdk-uat-3.21.17.1.aar",
          "size": 28842,
          "sha512": "3555093fa8dce2c100e01b57104b52cca0ae9bb35e329ebc2f8ed707a4a33c249bd19e7908e0fc23563bf3bdaaa3955e132c6fffb44d919c6ff516f2d52cdf40",
          "sha256": "07c51a02088e2e18b85a591c860bf8fe9480939d2b698dea2e32221009c9c977",
          "sha1": "1b83f829ac8b9df09e0d95891b1e6e5103dcaf79",
          "md5": "5dfd94c9dfedcba35abe724b492d9aae"
        }
      ]
    }
  ]
}
