{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk",
    "version": "2.5.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.5.8.aar",
          "url": "adwhale-mediation-sdk-2.5.8.aar",
          "size": 84908,
          "sha512": "892cb2b0fdceebbd4b367bbe6ec04c11fddcae91fe9deb8e7e6b02908d8d449e306f09295ad7430a30fcbe922522b610d65020d85297f2a09c8cf7b29618d750",
          "sha256": "9ab455964ff93a183282c065d9d9dceebf20d94f8bca6074a131f71892083b90",
          "sha1": "447b9aff8235ea519d66b4c6e331c50d82d6f519",
          "md5": "ff7ee5620197d7d90a413e4006daf448"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.5.8"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.5.8.aar",
          "url": "adwhale-mediation-sdk-2.5.8.aar",
          "size": 84908,
          "sha512": "892cb2b0fdceebbd4b367bbe6ec04c11fddcae91fe9deb8e7e6b02908d8d449e306f09295ad7430a30fcbe922522b610d65020d85297f2a09c8cf7b29618d750",
          "sha256": "9ab455964ff93a183282c065d9d9dceebf20d94f8bca6074a131f71892083b90",
          "sha1": "447b9aff8235ea519d66b4c6e331c50d82d6f519",
          "md5": "ff7ee5620197d7d90a413e4006daf448"
        }
      ]
    }
  ]
}
