{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.cauly.adapter",
    "module": "cauly-sdk",
    "version": "3.5.40.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-3.5.40.4.aar",
          "url": "cauly-sdk-3.5.40.4.aar",
          "size": 33178,
          "sha512": "564184439c302eb8dc8b1ef6585174d381e527d09dc51c230ac218e30a0cb4c9745da8077a45ffa3b56931dfb5898435848ffeae25b37cdfd7a837067bd9ec29",
          "sha256": "992e87766b6fb1416b5c655dfa8cd38b6357cbd09977ef4bf6c2d5afcb2cbea9",
          "sha1": "ad737c4b91d38aed2685dc5ae0085ba7461536e8",
          "md5": "ec7e23e102626b0000f3e5a12b6d60b2"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "com.fsn.cauly",
          "module": "cauly-sdk",
          "version": {
            "requires": "3.5.40"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-3.5.40.4.aar",
          "url": "cauly-sdk-3.5.40.4.aar",
          "size": 33178,
          "sha512": "564184439c302eb8dc8b1ef6585174d381e527d09dc51c230ac218e30a0cb4c9745da8077a45ffa3b56931dfb5898435848ffeae25b37cdfd7a837067bd9ec29",
          "sha256": "992e87766b6fb1416b5c655dfa8cd38b6357cbd09977ef4bf6c2d5afcb2cbea9",
          "sha1": "ad737c4b91d38aed2685dc5ae0085ba7461536e8",
          "md5": "ec7e23e102626b0000f3e5a12b6d60b2"
        }
      ]
    }
  ]
}
