{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk-uat",
    "version": "2.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.7.1.aar",
          "url": "adwhale-core-sdk-uat-2.7.1.aar",
          "size": 46781,
          "sha512": "1ea5ba08c9a0a48e53a7ab04e6593fc28fed6cf911470455d5f955e6ef473e6898cc8c27f457ffecc5a64bb3b289d24407bc984118f63daac52ee60fbfaa2224",
          "sha256": "c2468b0bebbd53ab20e8c78b764743559c54a91077bac2fba29ff56580c9b097",
          "sha1": "31ad4b47db5df0786c602e3a76a68d5b6f26d679",
          "md5": "fd80a0eab28f5e673ecdc0ff708692b3"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.7.1.aar",
          "url": "adwhale-core-sdk-uat-2.7.1.aar",
          "size": 46781,
          "sha512": "1ea5ba08c9a0a48e53a7ab04e6593fc28fed6cf911470455d5f955e6ef473e6898cc8c27f457ffecc5a64bb3b289d24407bc984118f63daac52ee60fbfaa2224",
          "sha256": "c2468b0bebbd53ab20e8c78b764743559c54a91077bac2fba29ff56580c9b097",
          "sha1": "31ad4b47db5df0786c602e3a76a68d5b6f26d679",
          "md5": "fd80a0eab28f5e673ecdc0ff708692b3"
        }
      ]
    }
  ]
}
