{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk",
    "version": "3.21.17.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "realReleaseVariantRealReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-3.21.17.2.aar",
          "url": "adfit-sdk-3.21.17.2.aar",
          "size": 25011,
          "sha512": "51353adfd0933f1a390c8b28afae04ba8aae684a64bc0dc2dcb0dfad758a5305c0e31260cb896e170bd3edf9e00961914e0b1b43feaa280b42bb1e1cc0af572d",
          "sha256": "af566fc53ac31d419c8dde73418177f73c4e39f0ead367c1d06ea5a2139155d8",
          "sha1": "803ee035d86e133065c14458dc84e3653b80fb09",
          "md5": "73c2ea7b87003e44076fa1001541e556"
        }
      ]
    },
    {
      "name": "realReleaseVariantRealReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.21.17"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-3.21.17.2.aar",
          "url": "adfit-sdk-3.21.17.2.aar",
          "size": 25011,
          "sha512": "51353adfd0933f1a390c8b28afae04ba8aae684a64bc0dc2dcb0dfad758a5305c0e31260cb896e170bd3edf9e00961914e0b1b43feaa280b42bb1e1cc0af572d",
          "sha256": "af566fc53ac31d419c8dde73418177f73c4e39f0ead367c1d06ea5a2139155d8",
          "sha1": "803ee035d86e133065c14458dc84e3653b80fb09",
          "md5": "73c2ea7b87003e44076fa1001541e556"
        }
      ]
    }
  ]
}
