{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admize.adapter",
    "module": "admize-sdk-uat",
    "version": "1.0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-uat-1.0.7.0.aar",
          "url": "admize-sdk-uat-1.0.7.0.aar",
          "size": 35255,
          "sha512": "a55af2ec664f1c2bd59b73ee4bfc36ac038d90c852a876cec72579421e600ea7519c0b6d6b0a0e05715a61495403b45ae9c9532600249ae6e1af03803c14b5d8",
          "sha256": "748645b244ef37b30357ad544dc54a19b7544ff054aee3e7ecb1323332428517",
          "sha1": "0322558ba2efd54be92c7da734c0e762c2e8bf46",
          "md5": "1e61662b67fff7b0c0d8e11e1a8514f9"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.admize.sdk.android",
          "module": "admize-sdk-android-uat",
          "version": {
            "requires": "1.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-uat-1.0.7.0.aar",
          "url": "admize-sdk-uat-1.0.7.0.aar",
          "size": 35255,
          "sha512": "a55af2ec664f1c2bd59b73ee4bfc36ac038d90c852a876cec72579421e600ea7519c0b6d6b0a0e05715a61495403b45ae9c9532600249ae6e1af03803c14b5d8",
          "sha256": "748645b244ef37b30357ad544dc54a19b7544ff054aee3e7ecb1323332428517",
          "sha1": "0322558ba2efd54be92c7da734c0e762c2e8bf46",
          "md5": "1e61662b67fff7b0c0d8e11e1a8514f9"
        }
      ]
    }
  ]
}
