{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admize.adapter",
    "module": "admize-sdk-uat",
    "version": "1.0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-uat-1.0.7.0.aar",
          "url": "admize-sdk-uat-1.0.7.0.aar",
          "size": 35232,
          "sha512": "3fe2a4e5aa84dd92441d964f15bb4a91e70114d78c4d777a3c76ca33b0db83e8d2529fe91626952439bf0fad389ad4593123c0c4d0bccdba4ca79290c808b405",
          "sha256": "add67c9e7ecd9a1b232a20ca4f30b0d1f68279ef02e235d97a731b66114f79b4",
          "sha1": "e7c98efcc1b36fd6abbc0693333ed400a6f1a634",
          "md5": "ab971bb3f308d275ca4c7642540496bc"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.admize.sdk.android",
          "module": "admize-sdk-android-uat",
          "version": {
            "requires": "1.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-uat-1.0.7.0.aar",
          "url": "admize-sdk-uat-1.0.7.0.aar",
          "size": 35232,
          "sha512": "3fe2a4e5aa84dd92441d964f15bb4a91e70114d78c4d777a3c76ca33b0db83e8d2529fe91626952439bf0fad389ad4593123c0c4d0bccdba4ca79290c808b405",
          "sha256": "add67c9e7ecd9a1b232a20ca4f30b0d1f68279ef02e235d97a731b66114f79b4",
          "sha1": "e7c98efcc1b36fd6abbc0693333ed400a6f1a634",
          "md5": "ab971bb3f308d275ca4c7642540496bc"
        }
      ]
    }
  ]
}
