{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk",
    "version": "2.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.7.2.aar",
          "url": "adwhale-mediation-sdk-2.7.2.aar",
          "size": 116558,
          "sha512": "612c30d30b445f62c3ef1d3d7f2df52f94963a4fea0a653f729dc68c362dfa402b9e794813332b34b4181c95b12767cf678a93f5705f0fbd4c70a25a8d5b59d7",
          "sha256": "2f41041a0042798f1f020ce855dd58120bfe28993c962a47560a98fac4f2b3c9",
          "sha1": "6e2701ffe1995134d05ebdb977274b27149e8269",
          "md5": "2cb3af2c3b0ba221f1e81986856ea26e"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.7.2.aar",
          "url": "adwhale-mediation-sdk-2.7.2.aar",
          "size": 116558,
          "sha512": "612c30d30b445f62c3ef1d3d7f2df52f94963a4fea0a653f729dc68c362dfa402b9e794813332b34b4181c95b12767cf678a93f5705f0fbd4c70a25a8d5b59d7",
          "sha256": "2f41041a0042798f1f020ce855dd58120bfe28993c962a47560a98fac4f2b3c9",
          "sha1": "6e2701ffe1995134d05ebdb977274b27149e8269",
          "md5": "2cb3af2c3b0ba221f1e81986856ea26e"
        }
      ]
    }
  ]
}
