{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk-uat",
    "version": "3.17.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.2.aar",
          "url": "adfit-sdk-uat-3.17.2.2.aar",
          "size": 8885,
          "sha512": "ea25bb3cd0f39a777d1c4f628854dd5149c8eec3cd6927da14148ad877f4af7b5beb289cad1c5dcd659115fb6510bcbb35f6fe20b81e8e657cb621c45f8aac81",
          "sha256": "c582dae4694be7b343995a3164497b51e6e1bacc473e52567446ea5c3e8954dd",
          "sha1": "4f29f4464cc07cd79f2cae21b859b4d18c9ee868",
          "md5": "8704ce22dc999e04f5a439e1470b2fe6"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.2.aar",
          "url": "adfit-sdk-uat-3.17.2.2.aar",
          "size": 8885,
          "sha512": "ea25bb3cd0f39a777d1c4f628854dd5149c8eec3cd6927da14148ad877f4af7b5beb289cad1c5dcd659115fb6510bcbb35f6fe20b81e8e657cb621c45f8aac81",
          "sha256": "c582dae4694be7b343995a3164497b51e6e1bacc473e52567446ea5c3e8954dd",
          "sha1": "4f29f4464cc07cd79f2cae21b859b4d18c9ee868",
          "md5": "8704ce22dc999e04f5a439e1470b2fe6"
        }
      ]
    }
  ]
}
