{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk-uat",
    "version": "3.17.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.2.aar",
          "url": "adfit-sdk-uat-3.17.2.2.aar",
          "size": 8920,
          "sha512": "cad0f1471e3ba8ad7bc8700891af1ce66766256ec01745eeda86d08d0dbd20e6a2ac5db3d0b6ca48ee581e9b5ba4e42a41cb5e35796c64ed840a7fd593897d16",
          "sha256": "234e812d28325fbade52746007abe2211816dfbf1625d5e84b180b0c7ad143ce",
          "sha1": "3d7da9153ad77ff3588bd0893ad220cfc144a995",
          "md5": "a77accef5765bc8ce7417562babc4de6"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.2.aar",
          "url": "adfit-sdk-uat-3.17.2.2.aar",
          "size": 8920,
          "sha512": "cad0f1471e3ba8ad7bc8700891af1ce66766256ec01745eeda86d08d0dbd20e6a2ac5db3d0b6ca48ee581e9b5ba4e42a41cb5e35796c64ed840a7fd593897d16",
          "sha256": "234e812d28325fbade52746007abe2211816dfbf1625d5e84b180b0c7ad143ce",
          "sha1": "3d7da9153ad77ff3588bd0893ad220cfc144a995",
          "md5": "a77accef5765bc8ce7417562babc4de6"
        }
      ]
    }
  ]
}
