{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk-uat",
    "version": "3.17.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.2.aar",
          "url": "adfit-sdk-uat-3.17.2.2.aar",
          "size": 8930,
          "sha512": "567638f307d422532ac173f852b9324b0b6a91767c690e699fe3784e27209c89d50203250c777409296ba4ab54473813cca7a82fc1159de3539de47944b09719",
          "sha256": "a4f47a377e6367da20f9b24e972dd25403dfcf955cfab7801ec3581773d8c23a",
          "sha1": "17a9ea2b2184b4b4191a9d5240445267e846eb6e",
          "md5": "bbfe50df37659c9a52404f7b4d410c7f"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.2.aar",
          "url": "adfit-sdk-uat-3.17.2.2.aar",
          "size": 8930,
          "sha512": "567638f307d422532ac173f852b9324b0b6a91767c690e699fe3784e27209c89d50203250c777409296ba4ab54473813cca7a82fc1159de3539de47944b09719",
          "sha256": "a4f47a377e6367da20f9b24e972dd25403dfcf955cfab7801ec3581773d8c23a",
          "sha1": "17a9ea2b2184b4b4191a9d5240445267e846eb6e",
          "md5": "bbfe50df37659c9a52404f7b4d410c7f"
        }
      ]
    }
  ]
}
