{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk-uat",
    "version": "2.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.7.5.aar",
          "url": "adwhale-core-sdk-uat-2.7.5.aar",
          "size": 54732,
          "sha512": "3c9b8d38071ae395f21bed00158de9a00f96341b0d4175d12e53d80917d70c6e522d8edfb31a25660f23081e3699ac9247d82f923d081108d25d2bde07290564",
          "sha256": "a2364826db500a045be1d2d3b8b495104756f7bb7fd6eedc002333b9788f0969",
          "sha1": "f4f7b41db5ceb5661fa750e10befafa0ef03f65a",
          "md5": "58ce7ba49e71d92578cd44cb5e9b2764"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.7.5.aar",
          "url": "adwhale-core-sdk-uat-2.7.5.aar",
          "size": 54732,
          "sha512": "3c9b8d38071ae395f21bed00158de9a00f96341b0d4175d12e53d80917d70c6e522d8edfb31a25660f23081e3699ac9247d82f923d081108d25d2bde07290564",
          "sha256": "a2364826db500a045be1d2d3b8b495104756f7bb7fd6eedc002333b9788f0969",
          "sha1": "f4f7b41db5ceb5661fa750e10befafa0ef03f65a",
          "md5": "58ce7ba49e71d92578cd44cb5e9b2764"
        }
      ]
    }
  ]
}
