{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admob.adapter",
    "module": "admob-sdk",
    "version": "24.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "realReleaseVariantRealReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admob-sdk-24.3.0.4.aar",
          "url": "admob-sdk-24.3.0.4.aar",
          "size": 155001,
          "sha512": "c6c1782723ba321de4b67074e7f941dd1c5ee5ad660a9bd0021fb3ad4f32c82175b4149b9a579e2827017af6ff98081c44fca3dd0d61a0bfaec472f2940f23d5",
          "sha256": "0f8c88663e855acac5e1dce7e65407eb8783ff85bd3d18dd1123a34350fd98b0",
          "sha1": "87340a13d04c7a9cb35f95500a95337527b086ec",
          "md5": "d830420be82f85e96c04bb566d7f0e91"
        }
      ]
    },
    {
      "name": "realReleaseVariantRealReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "net.adwhale.sdk.cauly.adapter",
          "module": "cauly-sdk",
          "version": {
            "requires": "3.5.44.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "admob-sdk-24.3.0.4.aar",
          "url": "admob-sdk-24.3.0.4.aar",
          "size": 155001,
          "sha512": "c6c1782723ba321de4b67074e7f941dd1c5ee5ad660a9bd0021fb3ad4f32c82175b4149b9a579e2827017af6ff98081c44fca3dd0d61a0bfaec472f2940f23d5",
          "sha256": "0f8c88663e855acac5e1dce7e65407eb8783ff85bd3d18dd1123a34350fd98b0",
          "sha1": "87340a13d04c7a9cb35f95500a95337527b086ec",
          "md5": "d830420be82f85e96c04bb566d7f0e91"
        }
      ]
    }
  ]
}
