{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.cauly.adapter",
    "module": "cauly-sdk",
    "version": "3.5.40.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-3.5.40.2.aar",
          "url": "cauly-sdk-3.5.40.2.aar",
          "size": 33120,
          "sha512": "2c19ce5b6e892a715857a5886176a699564c0ca53a7d2db194d22a295dc537369cf456b97acd6c7e25d5e5996dc2fa5629c1a5386285d83984dc98e31f70ed0f",
          "sha256": "5e04e47c66ed38019df36b95ee97a98f5a93a5ec5ac94af7ac6217f4fc5a06c2",
          "sha1": "c09ce2d5a0a1f5006fb7031079e61026f7e45eb2",
          "md5": "d70d3e5eec03bc53cc06c2e6d18a0351"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.fsn.cauly",
          "module": "cauly-sdk",
          "version": {
            "requires": "3.5.40"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-3.5.40.2.aar",
          "url": "cauly-sdk-3.5.40.2.aar",
          "size": 33120,
          "sha512": "2c19ce5b6e892a715857a5886176a699564c0ca53a7d2db194d22a295dc537369cf456b97acd6c7e25d5e5996dc2fa5629c1a5386285d83984dc98e31f70ed0f",
          "sha256": "5e04e47c66ed38019df36b95ee97a98f5a93a5ec5ac94af7ac6217f4fc5a06c2",
          "sha1": "c09ce2d5a0a1f5006fb7031079e61026f7e45eb2",
          "md5": "d70d3e5eec03bc53cc06c2e6d18a0351"
        }
      ]
    }
  ]
}
