{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.cauly.adapter",
    "module": "cauly-sdk",
    "version": "3.5.40.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-3.5.40.2.aar",
          "url": "cauly-sdk-3.5.40.2.aar",
          "size": 33126,
          "sha512": "14994a3f9c857548a1c548064c67fa837bb562cf7bbae6ef97094afefdbfff7e99e8c5052c4fc753048be5e536d867e8635e4e8c47ab52168d13f640ec5ad8ba",
          "sha256": "82b98236e2ee3c37c03619eb4d4bbe58a5a478766cca44d11511ad1b8d56db59",
          "sha1": "5ed525b47fd4efa13e17b2d38783a74ab866c355",
          "md5": "c0ac970313da02cb14d4abc2c7aff3d6"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.fsn.cauly",
          "module": "cauly-sdk",
          "version": {
            "requires": "3.5.40"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-3.5.40.2.aar",
          "url": "cauly-sdk-3.5.40.2.aar",
          "size": 33126,
          "sha512": "14994a3f9c857548a1c548064c67fa837bb562cf7bbae6ef97094afefdbfff7e99e8c5052c4fc753048be5e536d867e8635e4e8c47ab52168d13f640ec5ad8ba",
          "sha256": "82b98236e2ee3c37c03619eb4d4bbe58a5a478766cca44d11511ad1b8d56db59",
          "sha1": "5ed525b47fd4efa13e17b2d38783a74ab866c355",
          "md5": "c0ac970313da02cb14d4abc2c7aff3d6"
        }
      ]
    }
  ]
}
