{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admob.adapter",
    "module": "admob-sdk-uat",
    "version": "23.6.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admob-sdk-uat-23.6.0.1.aar",
          "url": "admob-sdk-uat-23.6.0.1.aar",
          "size": 67718,
          "sha512": "59357d71c3aa6cb0589b51b77c351c83139638b3cca5fcb761e45759d1bffa46e8734a014990dc3ccd52838dcd087c02df9bd7df59bdd52d452ffdd1d08fb6be",
          "sha256": "55d8d4dbba5ecba5824d4722bac8c4f0eaec8d95cc4f33843b8fe30354bc2df2",
          "sha1": "2aebb596c97092d8576df3700275b6f5145ca230",
          "md5": "31473255eba6773709453243129d188a"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "admob-sdk-uat-23.6.0.1.aar",
          "url": "admob-sdk-uat-23.6.0.1.aar",
          "size": 67718,
          "sha512": "59357d71c3aa6cb0589b51b77c351c83139638b3cca5fcb761e45759d1bffa46e8734a014990dc3ccd52838dcd087c02df9bd7df59bdd52d452ffdd1d08fb6be",
          "sha256": "55d8d4dbba5ecba5824d4722bac8c4f0eaec8d95cc4f33843b8fe30354bc2df2",
          "sha1": "2aebb596c97092d8576df3700275b6f5145ca230",
          "md5": "31473255eba6773709453243129d188a"
        }
      ]
    }
  ]
}
