{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admob.adapter",
    "module": "admob-sdk",
    "version": "24.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admob-sdk-24.3.0.2.aar",
          "url": "admob-sdk-24.3.0.2.aar",
          "size": 145168,
          "sha512": "523ad0d1eb1b38d8659df0a2fab97ba86d442e1ffa666fcaa534bbcbca3c2391a1224a02f21698ed9646c896d839728c55e029d2c24698e26dce7385c458acf1",
          "sha256": "1fdd60902e8de2adb7a603914e16e36a5f128d0e2fbfbee109502561c25693ef",
          "sha1": "9da564ffee96a28d8a7ed93dc8b58556fed16c18",
          "md5": "e08b7625bdb8b84a0c9e09fe219b6fe9"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "admob-sdk-24.3.0.2.aar",
          "url": "admob-sdk-24.3.0.2.aar",
          "size": 145168,
          "sha512": "523ad0d1eb1b38d8659df0a2fab97ba86d442e1ffa666fcaa534bbcbca3c2391a1224a02f21698ed9646c896d839728c55e029d2c24698e26dce7385c458acf1",
          "sha256": "1fdd60902e8de2adb7a603914e16e36a5f128d0e2fbfbee109502561c25693ef",
          "sha1": "9da564ffee96a28d8a7ed93dc8b58556fed16c18",
          "md5": "e08b7625bdb8b84a0c9e09fe219b6fe9"
        }
      ]
    }
  ]
}
