{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk-uat",
    "version": "8.7.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.3.aar",
          "url": "levelplay-sdk-uat-8.7.0.3.aar",
          "size": 26379,
          "sha512": "ca48db342c2310e0109999d34097dc9acf03d33654579abd3d1bb795962571551cebbc130b0cc7e0f24f3cb347d7c2f0a122ef2281cb76ac4a237935a43edf46",
          "sha256": "9cd7dff390442d39d2d2c6f670c2e96290f624e7e2a0325e7f0cfe939424cce4",
          "sha1": "e65bec60a45e2a9fcb86b268a760e7b77504d233",
          "md5": "794dd424d3e107f2db1f16f24ac49939"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.3.aar",
          "url": "levelplay-sdk-uat-8.7.0.3.aar",
          "size": 26379,
          "sha512": "ca48db342c2310e0109999d34097dc9acf03d33654579abd3d1bb795962571551cebbc130b0cc7e0f24f3cb347d7c2f0a122ef2281cb76ac4a237935a43edf46",
          "sha256": "9cd7dff390442d39d2d2c6f670c2e96290f624e7e2a0325e7f0cfe939424cce4",
          "sha1": "e65bec60a45e2a9fcb86b268a760e7b77504d233",
          "md5": "794dd424d3e107f2db1f16f24ac49939"
        }
      ]
    }
  ]
}
