{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk-uat",
    "version": "8.7.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.3.aar",
          "url": "levelplay-sdk-uat-8.7.0.3.aar",
          "size": 26349,
          "sha512": "94c29bde341a7bb50ddf603432f8c26a01b1015a046b21d694b6ec678ecfa4b0b2d18d8b2d9c5f60221a1bcc67291e1afd77a8498fc2209e5026a62a0996b398",
          "sha256": "11295a362232c7d4ec6caa2a889de22cc87ad7e3f72574b814e93763188ea595",
          "sha1": "c7b110598dd671b25452fb882c81ee2a27165548",
          "md5": "8d23cea1f96a008857463e05492ad84c"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.3.aar",
          "url": "levelplay-sdk-uat-8.7.0.3.aar",
          "size": 26349,
          "sha512": "94c29bde341a7bb50ddf603432f8c26a01b1015a046b21d694b6ec678ecfa4b0b2d18d8b2d9c5f60221a1bcc67291e1afd77a8498fc2209e5026a62a0996b398",
          "sha256": "11295a362232c7d4ec6caa2a889de22cc87ad7e3f72574b814e93763188ea595",
          "sha1": "c7b110598dd671b25452fb882c81ee2a27165548",
          "md5": "8d23cea1f96a008857463e05492ad84c"
        }
      ]
    }
  ]
}
