{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk-uat",
    "version": "8.7.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.3.aar",
          "url": "levelplay-sdk-uat-8.7.0.3.aar",
          "size": 26391,
          "sha512": "b32f11dab5180dbc6eeefec5be6642a4bdf6d5ac233f1971e8bfa4c079cbd4c804b674f3b912c47708ca06e050de4cce29bb789d42f09d9b6ace65fe284358aa",
          "sha256": "544f947f3dc2e93acf8a99cd3d07ec8e6997899a258b75b616a40d40dadb99c9",
          "sha1": "aa978cf16dcddd5956e40d166191a8c45a496ded",
          "md5": "7c3536e7d746f9fadcd80f7635c53583"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.3.aar",
          "url": "levelplay-sdk-uat-8.7.0.3.aar",
          "size": 26391,
          "sha512": "b32f11dab5180dbc6eeefec5be6642a4bdf6d5ac233f1971e8bfa4c079cbd4c804b674f3b912c47708ca06e050de4cce29bb789d42f09d9b6ace65fe284358aa",
          "sha256": "544f947f3dc2e93acf8a99cd3d07ec8e6997899a258b75b616a40d40dadb99c9",
          "sha1": "aa978cf16dcddd5956e40d166191a8c45a496ded",
          "md5": "7c3536e7d746f9fadcd80f7635c53583"
        }
      ]
    }
  ]
}
