{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk-uat",
    "version": "2.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.7.0.aar",
          "url": "adwhale-core-sdk-uat-2.7.0.aar",
          "size": 46688,
          "sha512": "2f6a6242eed9138d09ea7314e4975f90f41cd6e20666b4c216513a72f3d2d2575f14e3f5a5eb1ee175195ca17cc6f98e92aa28da76a7e919fb8bc70b28e6b53c",
          "sha256": "9478868a8a277489522a8127ce993476ffdd0c8e5c1dd062e1fc968c95d19677",
          "sha1": "d3c732c732ec45e8e95dae9c7861663fa1a98cf7",
          "md5": "db8c1dea25cc22e12b030e0247c2859c"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.7.0.aar",
          "url": "adwhale-core-sdk-uat-2.7.0.aar",
          "size": 46688,
          "sha512": "2f6a6242eed9138d09ea7314e4975f90f41cd6e20666b4c216513a72f3d2d2575f14e3f5a5eb1ee175195ca17cc6f98e92aa28da76a7e919fb8bc70b28e6b53c",
          "sha256": "9478868a8a277489522a8127ce993476ffdd0c8e5c1dd062e1fc968c95d19677",
          "sha1": "d3c732c732ec45e8e95dae9c7861663fa1a98cf7",
          "md5": "db8c1dea25cc22e12b030e0247c2859c"
        }
      ]
    }
  ]
}
