{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk-uat",
    "version": "2.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.7.0.aar",
          "url": "adwhale-core-sdk-uat-2.7.0.aar",
          "size": 46692,
          "sha512": "d1af79a24d638ba078f55cc13cce6f8acd5e1599fa93f94a44d06d05fd01b130a51a05d0c2f7d30aff943e9f96b320f10b73ce0e4c5054301816e29562dc9c5a",
          "sha256": "cff96248dffb640b9c8307947c57417864bbd28ed2721e52a25ee7ca40811c2b",
          "sha1": "93ac700a3908a40fa8525f14ced33c88120045ee",
          "md5": "15309d4b33b70dcc8751aa7bb3072b98"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.7.0.aar",
          "url": "adwhale-core-sdk-uat-2.7.0.aar",
          "size": 46692,
          "sha512": "d1af79a24d638ba078f55cc13cce6f8acd5e1599fa93f94a44d06d05fd01b130a51a05d0c2f7d30aff943e9f96b320f10b73ce0e4c5054301816e29562dc9c5a",
          "sha256": "cff96248dffb640b9c8307947c57417864bbd28ed2721e52a25ee7ca40811c2b",
          "sha1": "93ac700a3908a40fa8525f14ced33c88120045ee",
          "md5": "15309d4b33b70dcc8751aa7bb3072b98"
        }
      ]
    }
  ]
}
