{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk-uat",
    "version": "2.7.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.7.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.7.aar",
          "size": 211300,
          "sha512": "ed50d3a1b4741084dfc12107b465c43df354fa8010d42782895276c43a856d208f14948e2a85cf2ee7bd4765cf53ff28e7750afac488e028bfef6891e5ac65c9",
          "sha256": "cf7ca147ef0b07871e41e709f9546c78bb9b3b1d50c69172116246bec3e53eb4",
          "sha1": "f1b5c9d232541f438651b093f1e5608dab37e16e",
          "md5": "d32da3866e4864e0d19778b37de1bae6"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.7.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.7.aar",
          "size": 211300,
          "sha512": "ed50d3a1b4741084dfc12107b465c43df354fa8010d42782895276c43a856d208f14948e2a85cf2ee7bd4765cf53ff28e7750afac488e028bfef6891e5ac65c9",
          "sha256": "cf7ca147ef0b07871e41e709f9546c78bb9b3b1d50c69172116246bec3e53eb4",
          "sha1": "f1b5c9d232541f438651b093f1e5608dab37e16e",
          "md5": "d32da3866e4864e0d19778b37de1bae6"
        }
      ]
    }
  ]
}
