{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk",
    "version": "8.7.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-8.7.0.4.aar",
          "url": "levelplay-sdk-8.7.0.4.aar",
          "size": 47685,
          "sha512": "6dc511bb3d56255521e254d085ed551e23965e5171db04dc0e4a57c02535aeec95d7d108cb0274bc18160b14455f561e58cd1d0c11332a314b3dc76bf6d01be4",
          "sha256": "6206b5ddbf90faa8c1c42e9be722f62f0c4e77e3d780b550c2738e9831937f52",
          "sha1": "f3bac18574be2356790efed646cda742e51098f2",
          "md5": "87ca385a2d53497e10e95ea053726e51"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-8.7.0.4.aar",
          "url": "levelplay-sdk-8.7.0.4.aar",
          "size": 47685,
          "sha512": "6dc511bb3d56255521e254d085ed551e23965e5171db04dc0e4a57c02535aeec95d7d108cb0274bc18160b14455f561e58cd1d0c11332a314b3dc76bf6d01be4",
          "sha256": "6206b5ddbf90faa8c1c42e9be722f62f0c4e77e3d780b550c2738e9831937f52",
          "sha1": "f3bac18574be2356790efed646cda742e51098f2",
          "md5": "87ca385a2d53497e10e95ea053726e51"
        }
      ]
    }
  ]
}
