{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk",
    "version": "8.7.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-8.7.0.4.aar",
          "url": "levelplay-sdk-8.7.0.4.aar",
          "size": 47691,
          "sha512": "9224e31f81681c71f49ac671d9b40283358cecbebe55efbe2774956903c3a32acc60f6714c9c4c591fca0b6c9a7ac61691882e66614805450a3553bcba72e7f0",
          "sha256": "351c7e71092b602cf0a5c576a3dce14abad1bbfa87470a7ea17955c3a223b726",
          "sha1": "b65a84fe9e1fca4222f83df0fd309e08c4a03670",
          "md5": "1948e0000db1f9ea753984009f5448ce"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-8.7.0.4.aar",
          "url": "levelplay-sdk-8.7.0.4.aar",
          "size": 47691,
          "sha512": "9224e31f81681c71f49ac671d9b40283358cecbebe55efbe2774956903c3a32acc60f6714c9c4c591fca0b6c9a7ac61691882e66614805450a3553bcba72e7f0",
          "sha256": "351c7e71092b602cf0a5c576a3dce14abad1bbfa87470a7ea17955c3a223b726",
          "sha1": "b65a84fe9e1fca4222f83df0fd309e08c4a03670",
          "md5": "1948e0000db1f9ea753984009f5448ce"
        }
      ]
    }
  ]
}
