{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk",
    "version": "8.7.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-8.7.0.4.aar",
          "url": "levelplay-sdk-8.7.0.4.aar",
          "size": 47697,
          "sha512": "a234d1f4ce95228809cb9cc2f8e1f225d4fa1e71ce68ac5840ea464d586f36f51d297cc5ee8c397b6b0f7719e2cc0270e10d836dbcccd8adb979715df8c81d88",
          "sha256": "55bfe22f9854d06a3742e88f317202e8d485a345ff44ca314bcc221cd339afce",
          "sha1": "f34ad669103405e138eac3a03dd38068118c7180",
          "md5": "59463ee716697376a805aa279211101b"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-8.7.0.4.aar",
          "url": "levelplay-sdk-8.7.0.4.aar",
          "size": 47697,
          "sha512": "a234d1f4ce95228809cb9cc2f8e1f225d4fa1e71ce68ac5840ea464d586f36f51d297cc5ee8c397b6b0f7719e2cc0270e10d836dbcccd8adb979715df8c81d88",
          "sha256": "55bfe22f9854d06a3742e88f317202e8d485a345ff44ca314bcc221cd339afce",
          "sha1": "f34ad669103405e138eac3a03dd38068118c7180",
          "md5": "59463ee716697376a805aa279211101b"
        }
      ]
    }
  ]
}
