{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk",
    "version": "3.21.17.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "realReleaseVariantRealReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-3.21.17.4.aar",
          "url": "adfit-sdk-3.21.17.4.aar",
          "size": 25011,
          "sha512": "eb735a863a875fd3be4575002a7671021abb59416ac8458fb51c5ab13bbffbad150ab952a1b9294b745be12bdc546e52b7204a5d199fb8d8ce94b060fb87e0b7",
          "sha256": "6606ce2a47623d959ac32797e09e0ac106169747d03043b5e0b7192e51f86504",
          "sha1": "5bc29948febf319a59e7a04562a8c3dc9defc631",
          "md5": "1dfd4b9e31ae08afed8a52d9e3babd73"
        }
      ]
    },
    {
      "name": "realReleaseVariantRealReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.21.17"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-3.21.17.4.aar",
          "url": "adfit-sdk-3.21.17.4.aar",
          "size": 25011,
          "sha512": "eb735a863a875fd3be4575002a7671021abb59416ac8458fb51c5ab13bbffbad150ab952a1b9294b745be12bdc546e52b7204a5d199fb8d8ce94b060fb87e0b7",
          "sha256": "6606ce2a47623d959ac32797e09e0ac106169747d03043b5e0b7192e51f86504",
          "sha1": "5bc29948febf319a59e7a04562a8c3dc9defc631",
          "md5": "1dfd4b9e31ae08afed8a52d9e3babd73"
        }
      ]
    }
  ]
}
