{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk",
    "version": "2.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.6.1.aar",
          "url": "adwhale-mediation-sdk-2.6.1.aar",
          "size": 89201,
          "sha512": "edfebd6773e1431838dd45b53720ecc87b1a0ca8e196c32be20d232794fc163fad5797bb9b937d1fb0af86f74cc76e0440f321ae1a26fe2552743d9ab8b7ff5b",
          "sha256": "c37298bf0acff754d8f82d1d5d420e74d22ad6565413622fe353f723a391811e",
          "sha1": "0993d3b75392cbc338f3c10dc52eb41b1ecd1f63",
          "md5": "be4c15b9453b20e5fc4610ab65c0ed01"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.6.1.aar",
          "url": "adwhale-mediation-sdk-2.6.1.aar",
          "size": 89201,
          "sha512": "edfebd6773e1431838dd45b53720ecc87b1a0ca8e196c32be20d232794fc163fad5797bb9b937d1fb0af86f74cc76e0440f321ae1a26fe2552743d9ab8b7ff5b",
          "sha256": "c37298bf0acff754d8f82d1d5d420e74d22ad6565413622fe353f723a391811e",
          "sha1": "0993d3b75392cbc338f3c10dc52eb41b1ecd1f63",
          "md5": "be4c15b9453b20e5fc4610ab65c0ed01"
        }
      ]
    }
  ]
}
