{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk",
    "version": "2.5.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-2.5.10.aar",
          "url": "adwhale-core-sdk-2.5.10.aar",
          "size": 27787,
          "sha512": "ff17a56a9c719864717a067a4e779195e0ea970a9acc11789e04867fe9ab5714f93565eb4e70620c6fe41b17613f3c702e827c94e08830a4e954e575444d0cb3",
          "sha256": "fb962dec62275c2728dddf925c789c980e3d3889763c8eaf851e8c1d4a42e4b9",
          "sha1": "c1ec1b34416f2abc5d908d21f65e7d8b60259453",
          "md5": "4e8e2c476bb2a6e5f1d0a6e3093ed4ed"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-2.5.10.aar",
          "url": "adwhale-core-sdk-2.5.10.aar",
          "size": 27787,
          "sha512": "ff17a56a9c719864717a067a4e779195e0ea970a9acc11789e04867fe9ab5714f93565eb4e70620c6fe41b17613f3c702e827c94e08830a4e954e575444d0cb3",
          "sha256": "fb962dec62275c2728dddf925c789c980e3d3889763c8eaf851e8c1d4a42e4b9",
          "sha1": "c1ec1b34416f2abc5d908d21f65e7d8b60259453",
          "md5": "4e8e2c476bb2a6e5f1d0a6e3093ed4ed"
        }
      ]
    }
  ]
}
