{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk",
    "version": "2.5.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-2.5.10.aar",
          "url": "adwhale-core-sdk-2.5.10.aar",
          "size": 27912,
          "sha512": "41c890c44c536e8c64a7da6c8879cdb23329e1d5a6cc8262759c4c66a281209442d364fdb92dcb263cc0eff0f98b356cd1575a0790c76dc1a74144e872464d7f",
          "sha256": "143244085c53d81d68d46b8ad1506f1d7be5bb231587de02a6c5e9aee584726e",
          "sha1": "06f770d56a960a332b6927b25c953c93b1eabe72",
          "md5": "448042e578f9dcfd860207cc355b711f"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-2.5.10.aar",
          "url": "adwhale-core-sdk-2.5.10.aar",
          "size": 27912,
          "sha512": "41c890c44c536e8c64a7da6c8879cdb23329e1d5a6cc8262759c4c66a281209442d364fdb92dcb263cc0eff0f98b356cd1575a0790c76dc1a74144e872464d7f",
          "sha256": "143244085c53d81d68d46b8ad1506f1d7be5bb231587de02a6c5e9aee584726e",
          "sha1": "06f770d56a960a332b6927b25c953c93b1eabe72",
          "md5": "448042e578f9dcfd860207cc355b711f"
        }
      ]
    }
  ]
}
