{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk-uat",
    "version": "3.17.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.1.aar",
          "url": "adfit-sdk-uat-3.17.2.1.aar",
          "size": 8482,
          "sha512": "08ef533ed691a57726a613a918e80c3fbd51fee562365feb57dca8ee32a68f9102ccb47e336b4cffafa9ed9fbaef8d12c4e13c3620e67fa319f82c9a1ef2c769",
          "sha256": "4cb3934f7d7ec68d13c4b38c9ea793dd1848d5a769304fbb5a3e2d51b7a612b7",
          "sha1": "42f306e6678a3264504c331b40e0dd17165d8540",
          "md5": "a220d70bd4ebba701ef7be4e6a6b9683"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.1.aar",
          "url": "adfit-sdk-uat-3.17.2.1.aar",
          "size": 8482,
          "sha512": "08ef533ed691a57726a613a918e80c3fbd51fee562365feb57dca8ee32a68f9102ccb47e336b4cffafa9ed9fbaef8d12c4e13c3620e67fa319f82c9a1ef2c769",
          "sha256": "4cb3934f7d7ec68d13c4b38c9ea793dd1848d5a769304fbb5a3e2d51b7a612b7",
          "sha1": "42f306e6678a3264504c331b40e0dd17165d8540",
          "md5": "a220d70bd4ebba701ef7be4e6a6b9683"
        }
      ]
    }
  ]
}
