{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk-uat",
    "version": "3.17.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.1.aar",
          "url": "adfit-sdk-uat-3.17.2.1.aar",
          "size": 8821,
          "sha512": "b4e404b9508b62d697546ad86eae7b1e9c773747415f33041977ed11ce167d94a0385d9e0bd78893dcb258519b20e936d4d0a92f2573ab902e4fb68388ab1303",
          "sha256": "35e53a35be47ce45f1b1c1f79357a3a370991d7473adfbb3364a618d153abf28",
          "sha1": "349c8e5eea66b1cbb5c3cef2882eae89546d760b",
          "md5": "420644ce677f0b78565b648a5cdc1087"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.1.aar",
          "url": "adfit-sdk-uat-3.17.2.1.aar",
          "size": 8821,
          "sha512": "b4e404b9508b62d697546ad86eae7b1e9c773747415f33041977ed11ce167d94a0385d9e0bd78893dcb258519b20e936d4d0a92f2573ab902e4fb68388ab1303",
          "sha256": "35e53a35be47ce45f1b1c1f79357a3a370991d7473adfbb3364a618d153abf28",
          "sha1": "349c8e5eea66b1cbb5c3cef2882eae89546d760b",
          "md5": "420644ce677f0b78565b648a5cdc1087"
        }
      ]
    }
  ]
}
