{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk-uat",
    "version": "3.17.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.1.aar",
          "url": "adfit-sdk-uat-3.17.2.1.aar",
          "size": 8838,
          "sha512": "cdb97cce7c7ffca0f86526483b9a833d06f4120f9eb7bce43dda382a597c9e3fc94654cba5d8cb69602c48e710c373025cc08437e4cabb127324834454b543f5",
          "sha256": "ff43b507f2a426688169fba1b052f0d55d9888f2741fff5f5a8a39a53f524b82",
          "sha1": "53a0e92342dabd397e09ba6392891cdc52e4a0c5",
          "md5": "5fcd83fba829bd2dc840e826320d647e"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.1.aar",
          "url": "adfit-sdk-uat-3.17.2.1.aar",
          "size": 8838,
          "sha512": "cdb97cce7c7ffca0f86526483b9a833d06f4120f9eb7bce43dda382a597c9e3fc94654cba5d8cb69602c48e710c373025cc08437e4cabb127324834454b543f5",
          "sha256": "ff43b507f2a426688169fba1b052f0d55d9888f2741fff5f5a8a39a53f524b82",
          "sha1": "53a0e92342dabd397e09ba6392891cdc52e4a0c5",
          "md5": "5fcd83fba829bd2dc840e826320d647e"
        }
      ]
    }
  ]
}
