{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk-uat",
    "version": "2.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.0.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.0.aar",
          "size": 132870,
          "sha512": "fc338fa199b2f2163482137e630346a7bdc9cd8af93f889d3c830091ab2e5e71f010701f86a399aecf7a5ea7c6f08612146c90559d81825bff51cc7bbce573dc",
          "sha256": "81944995d1a211c87b6e7313bf76e9a9428700ff1791eddf26dc2febbd10f8aa",
          "sha1": "2d1a129c3ca59794d2c1999a141859ea9529b61d",
          "md5": "76539962a6206fb184384cdad0e56e40"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.0.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.0.aar",
          "size": 132870,
          "sha512": "fc338fa199b2f2163482137e630346a7bdc9cd8af93f889d3c830091ab2e5e71f010701f86a399aecf7a5ea7c6f08612146c90559d81825bff51cc7bbce573dc",
          "sha256": "81944995d1a211c87b6e7313bf76e9a9428700ff1791eddf26dc2febbd10f8aa",
          "sha1": "2d1a129c3ca59794d2c1999a141859ea9529b61d",
          "md5": "76539962a6206fb184384cdad0e56e40"
        }
      ]
    }
  ]
}
