{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk-uat",
    "version": "2.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.0.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.0.aar",
          "size": 132888,
          "sha512": "7fdb826df2a944ea0233b4e11fde9f286a4ecb2493cca6e734d595b6cb7e755213fc28874e3842ad439143e264051ae36fbcd63919e13c4c07d5aa9a77e59b1e",
          "sha256": "aa720d824d4d556d626f18a82f76bf69e50ac06918c2963b5c80fcce47eef8ea",
          "sha1": "3d52627be76dc6153631854cdb3d490f90d4897d",
          "md5": "b7534242f5b9777b8ddf8e65269dabff"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.0.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.0.aar",
          "size": 132888,
          "sha512": "7fdb826df2a944ea0233b4e11fde9f286a4ecb2493cca6e734d595b6cb7e755213fc28874e3842ad439143e264051ae36fbcd63919e13c4c07d5aa9a77e59b1e",
          "sha256": "aa720d824d4d556d626f18a82f76bf69e50ac06918c2963b5c80fcce47eef8ea",
          "sha1": "3d52627be76dc6153631854cdb3d490f90d4897d",
          "md5": "b7534242f5b9777b8ddf8e65269dabff"
        }
      ]
    }
  ]
}
