{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk-uat",
    "version": "2.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.0.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.0.aar",
          "size": 132845,
          "sha512": "3dd377db3dab4163b1665dc9076fc464f62f4517a4c3647af9ad24a9f91aa56857f627e51881d8fbe0bf749f8b0d2b1641a4cb5b19348a2eaf33076abb2014a1",
          "sha256": "ad809d37135296b907ebf838de4600e401e6cdba03e5817b5696398adf1a1288",
          "sha1": "8cbf497b7c4d0d032901644480eab4a1b12f4cf0",
          "md5": "c1b116445e63e5c520fa036bfac935c6"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.0.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.0.aar",
          "size": 132845,
          "sha512": "3dd377db3dab4163b1665dc9076fc464f62f4517a4c3647af9ad24a9f91aa56857f627e51881d8fbe0bf749f8b0d2b1641a4cb5b19348a2eaf33076abb2014a1",
          "sha256": "ad809d37135296b907ebf838de4600e401e6cdba03e5817b5696398adf1a1288",
          "sha1": "8cbf497b7c4d0d032901644480eab4a1b12f4cf0",
          "md5": "c1b116445e63e5c520fa036bfac935c6"
        }
      ]
    }
  ]
}
