{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-2.6.0.aar",
          "url": "adwhale-core-sdk-2.6.0.aar",
          "size": 35025,
          "sha512": "565a4a8e47eec5209206105714ed4d7141be128ba6a81eabcb632393a6b827d6fa3ca72d02695d03e8d8dbb8efa7807e8c6f829c3547eec8c7da1e7a4469721c",
          "sha256": "6affc27f039d45dc265316d769f3daa21bacd33161e64a907eb39b0d295f8289",
          "sha1": "beee34181b1c3ce3002b5858c6186be952754e20",
          "md5": "17c3872ed917bf815f053c477a7f44bd"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-2.6.0.aar",
          "url": "adwhale-core-sdk-2.6.0.aar",
          "size": 35025,
          "sha512": "565a4a8e47eec5209206105714ed4d7141be128ba6a81eabcb632393a6b827d6fa3ca72d02695d03e8d8dbb8efa7807e8c6f829c3547eec8c7da1e7a4469721c",
          "sha256": "6affc27f039d45dc265316d769f3daa21bacd33161e64a907eb39b0d295f8289",
          "sha1": "beee34181b1c3ce3002b5858c6186be952754e20",
          "md5": "17c3872ed917bf815f053c477a7f44bd"
        }
      ]
    }
  ]
}
