{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk-uat",
    "version": "3.17.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.5.aar",
          "url": "adfit-sdk-uat-3.17.2.5.aar",
          "size": 15724,
          "sha512": "515c87edb9e9148382488ad255841f141d56686e7986d290b3dcdcb471f022db0cfc7bee70eff5235d1293191dfa09ab3260e5a0c6c47307389eb1338f33ec95",
          "sha256": "4aa20ed8383ec4185b98c82a30d9988acd3be80378ce49b3b18aba8e26870bb5",
          "sha1": "07b4ec935d4792af414b359b5a9e3ace6890b4b9",
          "md5": "72982a9f358ff5ec7de3bfc1deb37d08"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.5.aar",
          "url": "adfit-sdk-uat-3.17.2.5.aar",
          "size": 15724,
          "sha512": "515c87edb9e9148382488ad255841f141d56686e7986d290b3dcdcb471f022db0cfc7bee70eff5235d1293191dfa09ab3260e5a0c6c47307389eb1338f33ec95",
          "sha256": "4aa20ed8383ec4185b98c82a30d9988acd3be80378ce49b3b18aba8e26870bb5",
          "sha1": "07b4ec935d4792af414b359b5a9e3ace6890b4b9",
          "md5": "72982a9f358ff5ec7de3bfc1deb37d08"
        }
      ]
    }
  ]
}
