{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk-uat",
    "version": "2.5.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.5.10.aar",
          "url": "adwhale-core-sdk-uat-2.5.10.aar",
          "size": 32170,
          "sha512": "c5c559731833ff10e028e357e1fa8b1b101d4f48a229c854f5184a2b9b526d04e4564570e9b973c08f563424e9129cd067f31dd7921adb813b6dc404b1bb74d0",
          "sha256": "bc9053946fc7fb4edf21c0b0aea7c84a13e1986be29540827f2eae76c1d10bac",
          "sha1": "53082c8a2d6c6cd9875680959d96f7041d0e9ceb",
          "md5": "306637188cfa1eaf224335d6e78adf6c"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.5.10.aar",
          "url": "adwhale-core-sdk-uat-2.5.10.aar",
          "size": 32170,
          "sha512": "c5c559731833ff10e028e357e1fa8b1b101d4f48a229c854f5184a2b9b526d04e4564570e9b973c08f563424e9129cd067f31dd7921adb813b6dc404b1bb74d0",
          "sha256": "bc9053946fc7fb4edf21c0b0aea7c84a13e1986be29540827f2eae76c1d10bac",
          "sha1": "53082c8a2d6c6cd9875680959d96f7041d0e9ceb",
          "md5": "306637188cfa1eaf224335d6e78adf6c"
        }
      ]
    }
  ]
}
