{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk",
    "version": "2.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-2.7.2.aar",
          "url": "adwhale-core-sdk-2.7.2.aar",
          "size": 41935,
          "sha512": "b11ee70338970b4c75edf6f200dad3bce5610f901d4067692c61f76662d980a5193deff413c7fa7b489a25f850739b5c1ce8a7ee48faf33eb9e8845550004576",
          "sha256": "d274d48960b4adb9e4910431415abffca495a623d8de40677b36ad1ab79d79f7",
          "sha1": "201972e296768fb9f893bce8b9cb3519d0716d08",
          "md5": "94a223d305fc7e7e2edf3ead73945587"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-2.7.2.aar",
          "url": "adwhale-core-sdk-2.7.2.aar",
          "size": 41935,
          "sha512": "b11ee70338970b4c75edf6f200dad3bce5610f901d4067692c61f76662d980a5193deff413c7fa7b489a25f850739b5c1ce8a7ee48faf33eb9e8845550004576",
          "sha256": "d274d48960b4adb9e4910431415abffca495a623d8de40677b36ad1ab79d79f7",
          "sha1": "201972e296768fb9f893bce8b9cb3519d0716d08",
          "md5": "94a223d305fc7e7e2edf3ead73945587"
        }
      ]
    }
  ]
}
