{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk",
    "version": "2.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-2.7.2.aar",
          "url": "adwhale-core-sdk-2.7.2.aar",
          "size": 40969,
          "sha512": "40863809c39c5fdfc66890730ebf1090e8c8494c1f5ea9221ae10b6d1c376bca087cc0cdf7203df399194bf1061718fa5773c257db432ab8e231eb089c116275",
          "sha256": "e5e56bf75bb70beb68fea07d0fa38e02fec69ac581e203f6a711215c12651f36",
          "sha1": "df4f9f954663dd669362e0a81a7ab69652395997",
          "md5": "f51a591c882d4d8e719abc788ec093cc"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-2.7.2.aar",
          "url": "adwhale-core-sdk-2.7.2.aar",
          "size": 40969,
          "sha512": "40863809c39c5fdfc66890730ebf1090e8c8494c1f5ea9221ae10b6d1c376bca087cc0cdf7203df399194bf1061718fa5773c257db432ab8e231eb089c116275",
          "sha256": "e5e56bf75bb70beb68fea07d0fa38e02fec69ac581e203f6a711215c12651f36",
          "sha1": "df4f9f954663dd669362e0a81a7ab69652395997",
          "md5": "f51a591c882d4d8e719abc788ec093cc"
        }
      ]
    }
  ]
}
