{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk-uat",
    "version": "2.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.5.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.5.aar",
          "size": 174938,
          "sha512": "411223385c376e05c2500ecd3652acce43b823399baa1539a56738e7ce51005dff80ae43d1f09e31b471b0edfd656794e9529a8d0428104514e70005736ae162",
          "sha256": "03a2e8e16edf466f27f63b9b655923c154d4f27bb8ad3546a48f476aa16925cc",
          "sha1": "2c74cb7e1123f4e6cb14128cde65dd9cbeae8f07",
          "md5": "261b0e422118d1300e483e97e96f39a1"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.5.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.5.aar",
          "size": 174938,
          "sha512": "411223385c376e05c2500ecd3652acce43b823399baa1539a56738e7ce51005dff80ae43d1f09e31b471b0edfd656794e9529a8d0428104514e70005736ae162",
          "sha256": "03a2e8e16edf466f27f63b9b655923c154d4f27bb8ad3546a48f476aa16925cc",
          "sha1": "2c74cb7e1123f4e6cb14128cde65dd9cbeae8f07",
          "md5": "261b0e422118d1300e483e97e96f39a1"
        }
      ]
    }
  ]
}
