{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk",
    "version": "8.7.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "realReleaseVariantRealReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-8.7.0.7.aar",
          "url": "levelplay-sdk-8.7.0.7.aar",
          "size": 48902,
          "sha512": "08f070bc1b8747330e5c99223cf903d2783f7beb556f71b491611f35d578e0003cc5d8ce5056478750e944e6bcabee6960190a655f09c25a131f007dce5b3164",
          "sha256": "b40bf71b9284557b2e8d1dc5ef6cba7fd5ec75387d95be8f21c9f2e648d94cd2",
          "sha1": "8643aad436279b89a30e7b0a7b9e0d7cecc2bb03",
          "md5": "0c862d36892d94adaa57950278db1a50"
        }
      ]
    },
    {
      "name": "realReleaseVariantRealReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-8.7.0.7.aar",
          "url": "levelplay-sdk-8.7.0.7.aar",
          "size": 48902,
          "sha512": "08f070bc1b8747330e5c99223cf903d2783f7beb556f71b491611f35d578e0003cc5d8ce5056478750e944e6bcabee6960190a655f09c25a131f007dce5b3164",
          "sha256": "b40bf71b9284557b2e8d1dc5ef6cba7fd5ec75387d95be8f21c9f2e648d94cd2",
          "sha1": "8643aad436279b89a30e7b0a7b9e0d7cecc2bb03",
          "md5": "0c862d36892d94adaa57950278db1a50"
        }
      ]
    }
  ]
}
