{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admize.adapter",
    "module": "admize-sdk-uat",
    "version": "1.0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-uat-1.0.8.5.aar",
          "url": "admize-sdk-uat-1.0.8.5.aar",
          "size": 35925,
          "sha512": "6dcea7e02106d6d7d842490d303139f6d5136bd25df9b2ea76ac025106494367a2c3dd62ad4ed4e96efcb176b2d163e39560873cf41bc04c64dbe7a027731532",
          "sha256": "c253b0e6b9df22089dff1d8f73c56fe43a57174a13bd2bc2823c52ef70aaca99",
          "sha1": "1db9866b885112154db2781ee18cb2c533651cb5",
          "md5": "6018b46937638e565663ae7785cdf824"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "io.admize.sdk.android",
          "module": "admize-sdk-android-uat",
          "version": {
            "requires": "1.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-uat-1.0.8.5.aar",
          "url": "admize-sdk-uat-1.0.8.5.aar",
          "size": 35925,
          "sha512": "6dcea7e02106d6d7d842490d303139f6d5136bd25df9b2ea76ac025106494367a2c3dd62ad4ed4e96efcb176b2d163e39560873cf41bc04c64dbe7a027731532",
          "sha256": "c253b0e6b9df22089dff1d8f73c56fe43a57174a13bd2bc2823c52ef70aaca99",
          "sha1": "1db9866b885112154db2781ee18cb2c533651cb5",
          "md5": "6018b46937638e565663ae7785cdf824"
        }
      ]
    }
  ]
}
