{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admob.adapter",
    "module": "admob-sdk-uat",
    "version": "24.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admob-sdk-uat-24.3.0.3.aar",
          "url": "admob-sdk-uat-24.3.0.3.aar",
          "size": 179451,
          "sha512": "1a3fa013f5ece57f2d80622d5a4b1657ad0ba08d99ba243031bab6caec80ec1398df3f16457fae4c924de9eb3cb65a5d1a4df2d0de6024ef94f011a16f6641ab",
          "sha256": "3e3a01664afdf20111d63f382945267bf96a6ae6ee102c324cd295c3a5bba962",
          "sha1": "7460b9fda8b81e2ec1ba6482e8c0d8216781d58d",
          "md5": "e00bb5539d5ac02ce5250045258fbaf3"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "admob-sdk-uat-24.3.0.3.aar",
          "url": "admob-sdk-uat-24.3.0.3.aar",
          "size": 179451,
          "sha512": "1a3fa013f5ece57f2d80622d5a4b1657ad0ba08d99ba243031bab6caec80ec1398df3f16457fae4c924de9eb3cb65a5d1a4df2d0de6024ef94f011a16f6641ab",
          "sha256": "3e3a01664afdf20111d63f382945267bf96a6ae6ee102c324cd295c3a5bba962",
          "sha1": "7460b9fda8b81e2ec1ba6482e8c0d8216781d58d",
          "md5": "e00bb5539d5ac02ce5250045258fbaf3"
        }
      ]
    }
  ]
}
