{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admob.adapter",
    "module": "admob-sdk-uat",
    "version": "24.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admob-sdk-uat-24.3.0.3.aar",
          "url": "admob-sdk-uat-24.3.0.3.aar",
          "size": 179514,
          "sha512": "329916cc9986b595b586446062ac7cb1937e5a4eed429d5b103b0d9069c6025e93bbddc1f9509bc183f521c7b80451bf7680a825bf361ec10e70f04d78b9f687",
          "sha256": "a0daba050596d044a157278b20723b71d74f8c07c97d1f91ba9c3077de6b27c3",
          "sha1": "a9d030eb23b7509d65b3f6c5cd1384c5dc1c92d3",
          "md5": "1b9472bcf292310e4943d411b9c650fc"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "net.adwhale.sdk.cauly.adapter",
          "module": "cauly-sdk-uat",
          "version": {
            "requires": "3.5.43.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "admob-sdk-uat-24.3.0.3.aar",
          "url": "admob-sdk-uat-24.3.0.3.aar",
          "size": 179514,
          "sha512": "329916cc9986b595b586446062ac7cb1937e5a4eed429d5b103b0d9069c6025e93bbddc1f9509bc183f521c7b80451bf7680a825bf361ec10e70f04d78b9f687",
          "sha256": "a0daba050596d044a157278b20723b71d74f8c07c97d1f91ba9c3077de6b27c3",
          "sha1": "a9d030eb23b7509d65b3f6c5cd1384c5dc1c92d3",
          "md5": "1b9472bcf292310e4943d411b9c650fc"
        }
      ]
    }
  ]
}
