{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admob.adapter",
    "module": "admob-sdk-uat",
    "version": "24.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admob-sdk-uat-24.3.0.3.aar",
          "url": "admob-sdk-uat-24.3.0.3.aar",
          "size": 182296,
          "sha512": "4bb9b364bc12252f6055cc3fe7b2b22017a11a1537a33af9cfd4bc6c2ee31be4214b7ed5676303053892b3ece399b288f5fee9ec3e7d36e8a89b1e260f656ccf",
          "sha256": "526e7cb263eededb50ff7da440549b15e8835b1f11d09a5472f06e2b6e13dd51",
          "sha1": "ba6e828ec59515934c82bd9f98b5827235c778ec",
          "md5": "58a5a8e43deffe59a24f6d77c3ebf707"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "net.adwhale.sdk.cauly.adapter",
          "module": "cauly-sdk-uat",
          "version": {
            "requires": "3.5.43.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "admob-sdk-uat-24.3.0.3.aar",
          "url": "admob-sdk-uat-24.3.0.3.aar",
          "size": 182296,
          "sha512": "4bb9b364bc12252f6055cc3fe7b2b22017a11a1537a33af9cfd4bc6c2ee31be4214b7ed5676303053892b3ece399b288f5fee9ec3e7d36e8a89b1e260f656ccf",
          "sha256": "526e7cb263eededb50ff7da440549b15e8835b1f11d09a5472f06e2b6e13dd51",
          "sha1": "ba6e828ec59515934c82bd9f98b5827235c778ec",
          "md5": "58a5a8e43deffe59a24f6d77c3ebf707"
        }
      ]
    }
  ]
}
