{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admob.adapter",
    "module": "admob-sdk-uat",
    "version": "24.3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admob-sdk-uat-24.3.0.0.aar",
          "url": "admob-sdk-uat-24.3.0.0.aar",
          "size": 154475,
          "sha512": "d1d16deaa5d8c47f04aaa05fc4500d0c85a08697d23781f524f4729fe5b2915bbc79f2fa446570c328321735047b5f092f495eb382fd105d865896f07a68f70d",
          "sha256": "30889e2a686fe68e14e2e29adb9af2a19eae4b63c282951335a67619135a008d",
          "sha1": "aea16e040649ecbc12322abef97a3981c834c19d",
          "md5": "9e64c1fea2b5fd8961d7c606d90b5d03"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "admob-sdk-uat-24.3.0.0.aar",
          "url": "admob-sdk-uat-24.3.0.0.aar",
          "size": 154475,
          "sha512": "d1d16deaa5d8c47f04aaa05fc4500d0c85a08697d23781f524f4729fe5b2915bbc79f2fa446570c328321735047b5f092f495eb382fd105d865896f07a68f70d",
          "sha256": "30889e2a686fe68e14e2e29adb9af2a19eae4b63c282951335a67619135a008d",
          "sha1": "aea16e040649ecbc12322abef97a3981c834c19d",
          "md5": "9e64c1fea2b5fd8961d7c606d90b5d03"
        }
      ]
    }
  ]
}
