{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admob.adapter",
    "module": "admob-sdk-uat",
    "version": "24.3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admob-sdk-uat-24.3.0.0.aar",
          "url": "admob-sdk-uat-24.3.0.0.aar",
          "size": 154535,
          "sha512": "e47a578e1aa3919d443604f4f0247c324b24cff790bca3fd13d447eb0ad217c7943ce26f0a2816016ab529e7a6a6c34d86096ce15e2dcc231ea366b169cbfcf1",
          "sha256": "680611d441c38d2d369c9a9a5e348f4b89e70fe483731d4a5899df591f422384",
          "sha1": "b2abdc016036d3ae7a378976e58926276203bc3e",
          "md5": "1a17f070ac07e478e4e2487b63182820"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "admob-sdk-uat-24.3.0.0.aar",
          "url": "admob-sdk-uat-24.3.0.0.aar",
          "size": 154535,
          "sha512": "e47a578e1aa3919d443604f4f0247c324b24cff790bca3fd13d447eb0ad217c7943ce26f0a2816016ab529e7a6a6c34d86096ce15e2dcc231ea366b169cbfcf1",
          "sha256": "680611d441c38d2d369c9a9a5e348f4b89e70fe483731d4a5899df591f422384",
          "sha1": "b2abdc016036d3ae7a378976e58926276203bc3e",
          "md5": "1a17f070ac07e478e4e2487b63182820"
        }
      ]
    }
  ]
}
