{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk-uat",
    "version": "8.7.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.8.aar",
          "url": "levelplay-sdk-uat-8.7.0.8.aar",
          "size": 22546,
          "sha512": "9d318f0d00e4fe18f764bd21f4a7a9ba1deb7a141fa0e2c71e7323ba8cbb1f34f2fe43d2eceb11bf2b885634fa2ca2b4d22a68b4c0f4a0d66e7533fa34910c08",
          "sha256": "948de3d1304eea300e6248ffd6702cb0118191a2420c72c7873a90f3eb0b4ec9",
          "sha1": "666e82fcdd46cecd1df075f6a29dc423d68e6f27",
          "md5": "3000be5a69a37a0f8aad8ef0fc53cf9e"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.8.aar",
          "url": "levelplay-sdk-uat-8.7.0.8.aar",
          "size": 22546,
          "sha512": "9d318f0d00e4fe18f764bd21f4a7a9ba1deb7a141fa0e2c71e7323ba8cbb1f34f2fe43d2eceb11bf2b885634fa2ca2b4d22a68b4c0f4a0d66e7533fa34910c08",
          "sha256": "948de3d1304eea300e6248ffd6702cb0118191a2420c72c7873a90f3eb0b4ec9",
          "sha1": "666e82fcdd46cecd1df075f6a29dc423d68e6f27",
          "md5": "3000be5a69a37a0f8aad8ef0fc53cf9e"
        }
      ]
    }
  ]
}
