{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk-uat",
    "version": "3.21.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-uat-3.21.17.0.aar",
          "url": "adfit-sdk-uat-3.21.17.0.aar",
          "size": 28841,
          "sha512": "a5f41d1ba5003c695149c81e6a9d5c46f45c506d0bf6b2aff53779c5d9acdc99c4808c311ce4879c9bc0683e78be98401c400dc531d93e05067e1b9911a9598a",
          "sha256": "b8bc9d0c5fa2775fd73eb27952d05b7d1aa06901fd6a1379821e230c795970b0",
          "sha1": "15de97c53dd384980ab656a6c67330b28e80acc4",
          "md5": "0bd8ba7cfc136899829b748ac3135a92"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.21.17"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-uat-3.21.17.0.aar",
          "url": "adfit-sdk-uat-3.21.17.0.aar",
          "size": 28841,
          "sha512": "a5f41d1ba5003c695149c81e6a9d5c46f45c506d0bf6b2aff53779c5d9acdc99c4808c311ce4879c9bc0683e78be98401c400dc531d93e05067e1b9911a9598a",
          "sha256": "b8bc9d0c5fa2775fd73eb27952d05b7d1aa06901fd6a1379821e230c795970b0",
          "sha1": "15de97c53dd384980ab656a6c67330b28e80acc4",
          "md5": "0bd8ba7cfc136899829b748ac3135a92"
        }
      ]
    }
  ]
}
