{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk-uat",
    "version": "3.21.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-uat-3.21.17.0.aar",
          "url": "adfit-sdk-uat-3.21.17.0.aar",
          "size": 28843,
          "sha512": "fab3ba959d98db1f41914394e7035ab6169d316c3f15d6e8717ce496b8b39b62a72c37b35c3e19725178903f34f5afecd91f137b190357850e975453d8dcfa45",
          "sha256": "c7601ad2afcf22df123603e5b63f703fa285319b6ab9e6857486053c4124ff5e",
          "sha1": "83138e71989459bdcc514fa89ca04fb3e8d5f725",
          "md5": "bdf33fc81059bc54e618530b00b3587a"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.21.17"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-uat-3.21.17.0.aar",
          "url": "adfit-sdk-uat-3.21.17.0.aar",
          "size": 28843,
          "sha512": "fab3ba959d98db1f41914394e7035ab6169d316c3f15d6e8717ce496b8b39b62a72c37b35c3e19725178903f34f5afecd91f137b190357850e975453d8dcfa45",
          "sha256": "c7601ad2afcf22df123603e5b63f703fa285319b6ab9e6857486053c4124ff5e",
          "sha1": "83138e71989459bdcc514fa89ca04fb3e8d5f725",
          "md5": "bdf33fc81059bc54e618530b00b3587a"
        }
      ]
    }
  ]
}
