{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk-uat",
    "version": "8.7.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.6.aar",
          "url": "levelplay-sdk-uat-8.7.0.6.aar",
          "size": 55679,
          "sha512": "3a4d4855a24d702a28a591dc8f35c683ae7254560e89e77e370e089c71993942ecd10463810a3c8e0ca50b719582d00415a5f582f35d7cf46eed3b54c76d6faa",
          "sha256": "f2796455b3fe26e876b7f5e2f2743778e155629c2eb3f3a48efdc71158ae52d9",
          "sha1": "e64440c10643624c8cf3c1bec15569c40346f4aa",
          "md5": "8e6b5112a14c9336c34247db4e656b5d"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.6.aar",
          "url": "levelplay-sdk-uat-8.7.0.6.aar",
          "size": 55679,
          "sha512": "3a4d4855a24d702a28a591dc8f35c683ae7254560e89e77e370e089c71993942ecd10463810a3c8e0ca50b719582d00415a5f582f35d7cf46eed3b54c76d6faa",
          "sha256": "f2796455b3fe26e876b7f5e2f2743778e155629c2eb3f3a48efdc71158ae52d9",
          "sha1": "e64440c10643624c8cf3c1bec15569c40346f4aa",
          "md5": "8e6b5112a14c9336c34247db4e656b5d"
        }
      ]
    }
  ]
}
