{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk-uat",
    "version": "8.7.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.4.aar",
          "url": "levelplay-sdk-uat-8.7.0.4.aar",
          "size": 55112,
          "sha512": "5198461d1e8e6de8fc8727fcc6a00600f06de29417f32c1d0852b979210d193741c0a0e0da60f9f4925cc8ef5c90725949fb70e6920a6368951c66196ac34f1c",
          "sha256": "308d79996d22431db081c4f54084cc530a9da56e88d15184cff24535ba6f442f",
          "sha1": "02f5f5bad64bb25fc9da7a9a430cf86cc22b5fd4",
          "md5": "34d48bdfc4c0f22d72a9f2954644a090"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.4.aar",
          "url": "levelplay-sdk-uat-8.7.0.4.aar",
          "size": 55112,
          "sha512": "5198461d1e8e6de8fc8727fcc6a00600f06de29417f32c1d0852b979210d193741c0a0e0da60f9f4925cc8ef5c90725949fb70e6920a6368951c66196ac34f1c",
          "sha256": "308d79996d22431db081c4f54084cc530a9da56e88d15184cff24535ba6f442f",
          "sha1": "02f5f5bad64bb25fc9da7a9a430cf86cc22b5fd4",
          "md5": "34d48bdfc4c0f22d72a9f2954644a090"
        }
      ]
    }
  ]
}
