{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk-uat",
    "version": "8.7.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.4.aar",
          "url": "levelplay-sdk-uat-8.7.0.4.aar",
          "size": 55097,
          "sha512": "952d8d1c805ef06d8355c83959b3f3dabbd8120aa9d2c6a9f7fb0584174144769b907165be660583e55bc749aceefa53eaa6af64998bf060410fbc7af127b307",
          "sha256": "da8a729e5f109b7de73ba041b7d63108dfd52a15a96395ef06f327b9d43e66bd",
          "sha1": "10deff20c0aba41a3c6b71327d125b97fbb159cd",
          "md5": "71e68fa5e67351d3e2f7281afcafb036"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.4.aar",
          "url": "levelplay-sdk-uat-8.7.0.4.aar",
          "size": 55097,
          "sha512": "952d8d1c805ef06d8355c83959b3f3dabbd8120aa9d2c6a9f7fb0584174144769b907165be660583e55bc749aceefa53eaa6af64998bf060410fbc7af127b307",
          "sha256": "da8a729e5f109b7de73ba041b7d63108dfd52a15a96395ef06f327b9d43e66bd",
          "sha1": "10deff20c0aba41a3c6b71327d125b97fbb159cd",
          "md5": "71e68fa5e67351d3e2f7281afcafb036"
        }
      ]
    }
  ]
}
