{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk-uat",
    "version": "8.7.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.4.aar",
          "url": "levelplay-sdk-uat-8.7.0.4.aar",
          "size": 55124,
          "sha512": "1fc703691206431cac81bd6072f553459134a4f3dfbb80fc20001a5ead804a60744ea7f58695217ff1df1073d67f423a2ee010ac84a31582ecd2f7675f91e5e6",
          "sha256": "88406e7abd70ef76ab2122bd2ba783958c74153251694bae5054f242be66392e",
          "sha1": "c6bcb9b769599d73dd3e483982615d3377f2ea89",
          "md5": "a3f8b47bcfb7d859d3c470aa58c12bd4"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.4.aar",
          "url": "levelplay-sdk-uat-8.7.0.4.aar",
          "size": 55124,
          "sha512": "1fc703691206431cac81bd6072f553459134a4f3dfbb80fc20001a5ead804a60744ea7f58695217ff1df1073d67f423a2ee010ac84a31582ecd2f7675f91e5e6",
          "sha256": "88406e7abd70ef76ab2122bd2ba783958c74153251694bae5054f242be66392e",
          "sha1": "c6bcb9b769599d73dd3e483982615d3377f2ea89",
          "md5": "a3f8b47bcfb7d859d3c470aa58c12bd4"
        }
      ]
    }
  ]
}
