{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk",
    "version": "2.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-2.7.0.aar",
          "url": "adwhale-core-sdk-2.7.0.aar",
          "size": 39923,
          "sha512": "6df92947d58c6171cd5ec06d3e4bcb7f82d528330a92853ece49684d2c9692255a9c16d6d1030f2f3d29b938cafcd2e6023323d63a5d79fc4c416f4fc984f5b9",
          "sha256": "643384d764abb5d9362ba6aaf9429ddb69d8f1e1dc2351f34c4b435b1d8a6537",
          "sha1": "531e810c89b29fad7f9780c06f3846063db5bee3",
          "md5": "0007a8aff25e7906a7546fca344c7657"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-2.7.0.aar",
          "url": "adwhale-core-sdk-2.7.0.aar",
          "size": 39923,
          "sha512": "6df92947d58c6171cd5ec06d3e4bcb7f82d528330a92853ece49684d2c9692255a9c16d6d1030f2f3d29b938cafcd2e6023323d63a5d79fc4c416f4fc984f5b9",
          "sha256": "643384d764abb5d9362ba6aaf9429ddb69d8f1e1dc2351f34c4b435b1d8a6537",
          "sha1": "531e810c89b29fad7f9780c06f3846063db5bee3",
          "md5": "0007a8aff25e7906a7546fca344c7657"
        }
      ]
    }
  ]
}
