{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk",
    "version": "2.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-2.7.0.aar",
          "url": "adwhale-core-sdk-2.7.0.aar",
          "size": 39480,
          "sha512": "e119824f8ebc89b22ac64fd6399ba4eee78460a0cf53a38edb025bfaab74a3f90325914a38278d0925df663d06308899be298f7c6344ac636ff8cd76cb6d1d75",
          "sha256": "c03bb5113570426fb6f59688ef3a1f4ea84de3053e918f8b34ddd03c277b07d0",
          "sha1": "e4d3a262108f0dcec5265c7f9d20d544ee5c9fc9",
          "md5": "1fe711c30acdb6aa55f5c8c5bf22849e"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-2.7.0.aar",
          "url": "adwhale-core-sdk-2.7.0.aar",
          "size": 39480,
          "sha512": "e119824f8ebc89b22ac64fd6399ba4eee78460a0cf53a38edb025bfaab74a3f90325914a38278d0925df663d06308899be298f7c6344ac636ff8cd76cb6d1d75",
          "sha256": "c03bb5113570426fb6f59688ef3a1f4ea84de3053e918f8b34ddd03c277b07d0",
          "sha1": "e4d3a262108f0dcec5265c7f9d20d544ee5c9fc9",
          "md5": "1fe711c30acdb6aa55f5c8c5bf22849e"
        }
      ]
    }
  ]
}
