{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk",
    "version": "2.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-2.7.0.aar",
          "url": "adwhale-core-sdk-2.7.0.aar",
          "size": 41010,
          "sha512": "bca3040a73e122c4b8fa80fa43cdab62d287b00862e98ecf56ee4d80b72a68996f5b6fb945c850cd239a628989f294f911364c44964bda9e12654945582edf34",
          "sha256": "c4f5f98c8bebb945ee9a6c6a888dd231810178ec68c3c58ecb485c1b4852be87",
          "sha1": "f40366c60fad7473d5036b2f9ee71bcda493338b",
          "md5": "47e8acf51f2207dc860a334897ee7581"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-2.7.0.aar",
          "url": "adwhale-core-sdk-2.7.0.aar",
          "size": 41010,
          "sha512": "bca3040a73e122c4b8fa80fa43cdab62d287b00862e98ecf56ee4d80b72a68996f5b6fb945c850cd239a628989f294f911364c44964bda9e12654945582edf34",
          "sha256": "c4f5f98c8bebb945ee9a6c6a888dd231810178ec68c3c58ecb485c1b4852be87",
          "sha1": "f40366c60fad7473d5036b2f9ee71bcda493338b",
          "md5": "47e8acf51f2207dc860a334897ee7581"
        }
      ]
    }
  ]
}
