{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk-uat",
    "version": "8.7.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.2.aar",
          "url": "levelplay-sdk-uat-8.7.0.2.aar",
          "size": 26306,
          "sha512": "d2cabd9a7626f6075b92301b31240f183ce202f501c862132cbe89794dae254d02f488f27b1e9cb8d929e36c3f42bec1c23b0b8466b234c2c303080723a5b595",
          "sha256": "96ede16adb33b089d101d4a6a9b9f7583a95aa5312b721d9073b4e2d3d0bdf31",
          "sha1": "0d9d77cf4304f708f8918c313659dd8ab25fd929",
          "md5": "e86d264dd39454e8e8fce9c9563ec39b"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.2.aar",
          "url": "levelplay-sdk-uat-8.7.0.2.aar",
          "size": 26306,
          "sha512": "d2cabd9a7626f6075b92301b31240f183ce202f501c862132cbe89794dae254d02f488f27b1e9cb8d929e36c3f42bec1c23b0b8466b234c2c303080723a5b595",
          "sha256": "96ede16adb33b089d101d4a6a9b9f7583a95aa5312b721d9073b4e2d3d0bdf31",
          "sha1": "0d9d77cf4304f708f8918c313659dd8ab25fd929",
          "md5": "e86d264dd39454e8e8fce9c9563ec39b"
        }
      ]
    }
  ]
}
