{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk-uat",
    "version": "8.7.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.2.aar",
          "url": "levelplay-sdk-uat-8.7.0.2.aar",
          "size": 22546,
          "sha512": "69c67ff28068b9016760ae239547ef64a19d712af7c5aca8106266e0d0e40c8bc0b265069ede22a6c3a22d37f1cdd9ae5bfe78531a488c4d617295d45a0aaf51",
          "sha256": "021c59d970f1c89ce4941a7140ba6e62125d05c5af43f07413b02fdcdf022799",
          "sha1": "d4d54a96d0125cd53b678fdd40c054858a7017dc",
          "md5": "c864cd92f50baba23d3b1be69df0f7eb"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.2.aar",
          "url": "levelplay-sdk-uat-8.7.0.2.aar",
          "size": 22546,
          "sha512": "69c67ff28068b9016760ae239547ef64a19d712af7c5aca8106266e0d0e40c8bc0b265069ede22a6c3a22d37f1cdd9ae5bfe78531a488c4d617295d45a0aaf51",
          "sha256": "021c59d970f1c89ce4941a7140ba6e62125d05c5af43f07413b02fdcdf022799",
          "sha1": "d4d54a96d0125cd53b678fdd40c054858a7017dc",
          "md5": "c864cd92f50baba23d3b1be69df0f7eb"
        }
      ]
    }
  ]
}
