{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk-uat",
    "version": "8.7.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.2.aar",
          "url": "levelplay-sdk-uat-8.7.0.2.aar",
          "size": 21898,
          "sha512": "9255d1270a7e708433204ee998f46837e728318f8c2e9e1f8bc15f0ad75dcba9701cbb7abd0bbe7a09b36991eb2371e42cfa74602de73e0be6f80187aaca4d5f",
          "sha256": "5f753938100a9d6c815a62f3faa081fc86ef06532a5fdc99d4c91d9d6a7c6d7a",
          "sha1": "0d40e971cc2b326fca694bb14cc4474996d7452c",
          "md5": "49ba8532d6bc88d809863fdc02d9c684"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.2.aar",
          "url": "levelplay-sdk-uat-8.7.0.2.aar",
          "size": 21898,
          "sha512": "9255d1270a7e708433204ee998f46837e728318f8c2e9e1f8bc15f0ad75dcba9701cbb7abd0bbe7a09b36991eb2371e42cfa74602de73e0be6f80187aaca4d5f",
          "sha256": "5f753938100a9d6c815a62f3faa081fc86ef06532a5fdc99d4c91d9d6a7c6d7a",
          "sha1": "0d40e971cc2b326fca694bb14cc4474996d7452c",
          "md5": "49ba8532d6bc88d809863fdc02d9c684"
        }
      ]
    }
  ]
}
