{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk",
    "version": "2.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "realReleaseVariantRealReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.7.5.aar",
          "url": "adwhale-mediation-sdk-2.7.5.aar",
          "size": 134454,
          "sha512": "9387afc7ec1f13b911efe2e83c04dd17b9808e814de4c3a61ad3b199d82bb7defd94702c86ef2e6f678620b8da32c9507c2f6df0467196d8a815898d0ab47c22",
          "sha256": "1cffd2d1bcd53e98cdedb52ed35ccc18297853a30cce98a9fecb0c5485a412ea",
          "sha1": "b800bbd599fd356ff0286aea2516eb319f9cc926",
          "md5": "43162012fa9938b7e8341adb85ff41ac"
        }
      ]
    },
    {
      "name": "realReleaseVariantRealReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.7.5.aar",
          "url": "adwhale-mediation-sdk-2.7.5.aar",
          "size": 134454,
          "sha512": "9387afc7ec1f13b911efe2e83c04dd17b9808e814de4c3a61ad3b199d82bb7defd94702c86ef2e6f678620b8da32c9507c2f6df0467196d8a815898d0ab47c22",
          "sha256": "1cffd2d1bcd53e98cdedb52ed35ccc18297853a30cce98a9fecb0c5485a412ea",
          "sha1": "b800bbd599fd356ff0286aea2516eb319f9cc926",
          "md5": "43162012fa9938b7e8341adb85ff41ac"
        }
      ]
    }
  ]
}
