{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk",
    "version": "2.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "realReleaseVariantRealReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.7.3.aar",
          "url": "adwhale-mediation-sdk-2.7.3.aar",
          "size": 133801,
          "sha512": "6153b31dd1ef2f9d39ac1a1052c54b09d4c6575a1e64e6bf3810e55b6b2e3e9284719395fab7b46c7395e7c436d4465e4b8757ba680a3cb17b0ffdc563d9a7c9",
          "sha256": "451d42ca45bc208b2310dfc07a43e18d7a78cfbebac5367f85ec759c34225e9d",
          "sha1": "889e5977bb0c9e07eabd493658d10f6e3bed99de",
          "md5": "512c9064caef531785cc9d60501b9ad3"
        }
      ]
    },
    {
      "name": "realReleaseVariantRealReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.7.3.aar",
          "url": "adwhale-mediation-sdk-2.7.3.aar",
          "size": 133801,
          "sha512": "6153b31dd1ef2f9d39ac1a1052c54b09d4c6575a1e64e6bf3810e55b6b2e3e9284719395fab7b46c7395e7c436d4465e4b8757ba680a3cb17b0ffdc563d9a7c9",
          "sha256": "451d42ca45bc208b2310dfc07a43e18d7a78cfbebac5367f85ec759c34225e9d",
          "sha1": "889e5977bb0c9e07eabd493658d10f6e3bed99de",
          "md5": "512c9064caef531785cc9d60501b9ad3"
        }
      ]
    }
  ]
}
