{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk",
    "version": "2.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "realReleaseVariantRealReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.7.3.aar",
          "url": "adwhale-mediation-sdk-2.7.3.aar",
          "size": 113151,
          "sha512": "24dcff3fd3913529d7e5fbda209bd58539e0c333d58120ccb19aa5a342f44f168c22b5d10d3fcc75d860f80a9f686c2e3e1a7c4b1b2bef887ac433b3ff8c5d09",
          "sha256": "4baa79f761db308426f18ba627c55d14504902815e75196a632be20a0a6e400c",
          "sha1": "c45c6360df3257462c3f6e63200a3d5df0df4d4a",
          "md5": "8bb43751c99f166dcfa8b49cf495cc55"
        }
      ]
    },
    {
      "name": "realReleaseVariantRealReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.7.3.aar",
          "url": "adwhale-mediation-sdk-2.7.3.aar",
          "size": 113151,
          "sha512": "24dcff3fd3913529d7e5fbda209bd58539e0c333d58120ccb19aa5a342f44f168c22b5d10d3fcc75d860f80a9f686c2e3e1a7c4b1b2bef887ac433b3ff8c5d09",
          "sha256": "4baa79f761db308426f18ba627c55d14504902815e75196a632be20a0a6e400c",
          "sha1": "c45c6360df3257462c3f6e63200a3d5df0df4d4a",
          "md5": "8bb43751c99f166dcfa8b49cf495cc55"
        }
      ]
    }
  ]
}
