{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk",
    "version": "2.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "realReleaseVariantRealReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.7.3.aar",
          "url": "adwhale-mediation-sdk-2.7.3.aar",
          "size": 133731,
          "sha512": "4bbebe25a165b323196ab2c2e5a8fdbf16c527929fc9e7f0b6afa8002d8e97c7b3daca9069b31dc1548ceb3afc0dd044b9b5aef01835a1d9d4e75be5e4050f94",
          "sha256": "3c30a84f9060456313a3b2d59326c1b674d02325536cf64e186de82bbbdf05bf",
          "sha1": "0f5f60ad33a0303ad6323848f60d8a6c9de4b6ab",
          "md5": "d0a2ae29da88f011dbf31129d79c4bcd"
        }
      ]
    },
    {
      "name": "realReleaseVariantRealReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.7.3.aar",
          "url": "adwhale-mediation-sdk-2.7.3.aar",
          "size": 133731,
          "sha512": "4bbebe25a165b323196ab2c2e5a8fdbf16c527929fc9e7f0b6afa8002d8e97c7b3daca9069b31dc1548ceb3afc0dd044b9b5aef01835a1d9d4e75be5e4050f94",
          "sha256": "3c30a84f9060456313a3b2d59326c1b674d02325536cf64e186de82bbbdf05bf",
          "sha1": "0f5f60ad33a0303ad6323848f60d8a6c9de4b6ab",
          "md5": "d0a2ae29da88f011dbf31129d79c4bcd"
        }
      ]
    }
  ]
}
