{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk-uat",
    "version": "3.21.17.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-uat-3.21.17.2.aar",
          "url": "adfit-sdk-uat-3.21.17.2.aar",
          "size": 28843,
          "sha512": "629b9b2427d2e37888ec663a30870157a734840e4c7d9747dc822c1665b05f3f2dd91413e194e8dda86df5821759c0765799d58eab557544d053e08684a6c37b",
          "sha256": "7dba629f4cf52ef4dc62a8470bbc2cb2ac1b9a19749463293ec644fc5bc1f519",
          "sha1": "996d0e95dee5958726f38476a45a6690ce5b2bfc",
          "md5": "2a4fdef28349400a78c3ae1a4dcea7d8"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.21.17"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-uat-3.21.17.2.aar",
          "url": "adfit-sdk-uat-3.21.17.2.aar",
          "size": 28843,
          "sha512": "629b9b2427d2e37888ec663a30870157a734840e4c7d9747dc822c1665b05f3f2dd91413e194e8dda86df5821759c0765799d58eab557544d053e08684a6c37b",
          "sha256": "7dba629f4cf52ef4dc62a8470bbc2cb2ac1b9a19749463293ec644fc5bc1f519",
          "sha1": "996d0e95dee5958726f38476a45a6690ce5b2bfc",
          "md5": "2a4fdef28349400a78c3ae1a4dcea7d8"
        }
      ]
    }
  ]
}
