{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk",
    "version": "3.17.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-3.17.2.3.aar",
          "url": "adfit-sdk-3.17.2.3.aar",
          "size": 13769,
          "sha512": "317402044a7257814a66b7cf8b91cb292a10a0058af9f25e4be8110b3f2e3756033d0cd4defc8274acd454c0678acb5a402e67df4319451394932d45e2901186",
          "sha256": "974817e4282a1dc2a56cc6fa4fda0269408de09d9b2f4b980d623a2cb2cc2574",
          "sha1": "1834cd4412269d9f52db55fdd38ebaa96fb7ef54",
          "md5": "02b72a5da2bc105c84d1a88cc393033f"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-3.17.2.3.aar",
          "url": "adfit-sdk-3.17.2.3.aar",
          "size": 13769,
          "sha512": "317402044a7257814a66b7cf8b91cb292a10a0058af9f25e4be8110b3f2e3756033d0cd4defc8274acd454c0678acb5a402e67df4319451394932d45e2901186",
          "sha256": "974817e4282a1dc2a56cc6fa4fda0269408de09d9b2f4b980d623a2cb2cc2574",
          "sha1": "1834cd4412269d9f52db55fdd38ebaa96fb7ef54",
          "md5": "02b72a5da2bc105c84d1a88cc393033f"
        }
      ]
    }
  ]
}
