{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk",
    "version": "3.17.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-3.17.2.3.aar",
          "url": "adfit-sdk-3.17.2.3.aar",
          "size": 13778,
          "sha512": "a2dcc8b3146f221f538875bca8cf4532a2c2f34370bd93916aab2d4f1d70943e9cefbdc81ffe468767801c644aebba5f8587ac9bb6543405bfcc295ca9c0101c",
          "sha256": "332a6e6fe7c6625c7e058b978f6d51072a7d22cf35d1c2a1fba335fce4413f19",
          "sha1": "8119835fb72966bb6977ea9b6dfc350386b26364",
          "md5": "736ae4de3474c40595d5fff32cc68a39"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-3.17.2.3.aar",
          "url": "adfit-sdk-3.17.2.3.aar",
          "size": 13778,
          "sha512": "a2dcc8b3146f221f538875bca8cf4532a2c2f34370bd93916aab2d4f1d70943e9cefbdc81ffe468767801c644aebba5f8587ac9bb6543405bfcc295ca9c0101c",
          "sha256": "332a6e6fe7c6625c7e058b978f6d51072a7d22cf35d1c2a1fba335fce4413f19",
          "sha1": "8119835fb72966bb6977ea9b6dfc350386b26364",
          "md5": "736ae4de3474c40595d5fff32cc68a39"
        }
      ]
    }
  ]
}
