{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admob.adapter",
    "module": "admob-sdk-uat",
    "version": "24.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admob-sdk-uat-24.3.0.1.aar",
          "url": "admob-sdk-uat-24.3.0.1.aar",
          "size": 155852,
          "sha512": "50e254508d7e40943865717d86c3ad7af7ff963dfe9271712fce9fd41d21d095696f6fa62a021427730279431213486c5cec85e4b4fa6412642942a9ad19c537",
          "sha256": "d022ade129c6482ee3b8877be9645a5369a4de5c20f9e13f8ae11898abec095a",
          "sha1": "60264ec469345c3dfbaac9707fe736a7a3c97739",
          "md5": "38bdd71894704360d4fd1e2d9815ee46"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "admob-sdk-uat-24.3.0.1.aar",
          "url": "admob-sdk-uat-24.3.0.1.aar",
          "size": 155852,
          "sha512": "50e254508d7e40943865717d86c3ad7af7ff963dfe9271712fce9fd41d21d095696f6fa62a021427730279431213486c5cec85e4b4fa6412642942a9ad19c537",
          "sha256": "d022ade129c6482ee3b8877be9645a5369a4de5c20f9e13f8ae11898abec095a",
          "sha1": "60264ec469345c3dfbaac9707fe736a7a3c97739",
          "md5": "38bdd71894704360d4fd1e2d9815ee46"
        }
      ]
    }
  ]
}
