{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admob.adapter",
    "module": "admob-sdk-uat",
    "version": "24.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admob-sdk-uat-24.3.0.1.aar",
          "url": "admob-sdk-uat-24.3.0.1.aar",
          "size": 156553,
          "sha512": "6b623597ce52cebcbc82460892ab5c607598aff5ec539642780f2e94f2e01d734a106df73c22a1e120409e6a2cfd6921183ea7221be9ba461fe3cd6e1b6131dc",
          "sha256": "98ad35a5c1afdc560793ab8abc753e04a1df0427236c171dac5bd15f7cecd2aa",
          "sha1": "4fff406dca2066cbba33ac018c6a4335fa85256d",
          "md5": "e0dd2ab54c3948322f17625d75ae4987"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "admob-sdk-uat-24.3.0.1.aar",
          "url": "admob-sdk-uat-24.3.0.1.aar",
          "size": 156553,
          "sha512": "6b623597ce52cebcbc82460892ab5c607598aff5ec539642780f2e94f2e01d734a106df73c22a1e120409e6a2cfd6921183ea7221be9ba461fe3cd6e1b6131dc",
          "sha256": "98ad35a5c1afdc560793ab8abc753e04a1df0427236c171dac5bd15f7cecd2aa",
          "sha1": "4fff406dca2066cbba33ac018c6a4335fa85256d",
          "md5": "e0dd2ab54c3948322f17625d75ae4987"
        }
      ]
    }
  ]
}
