{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk-uat",
    "version": "2.7.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.7.6.aar",
          "url": "adwhale-core-sdk-uat-2.7.6.aar",
          "size": 54855,
          "sha512": "f234db23f2502fd5d2759c968531dbc07c71a90a6881a6bdc5f35efcd281fda21c29ff68e68a5b4c3a534927970f504e569d7e72129375112bead86cae6943fb",
          "sha256": "434c07455926317a4a5875b761f35970bb6f8f8ea027f20ec14497cacde47671",
          "sha1": "eaefbaf2d0a9cab1eea346f9964184fdfd68067d",
          "md5": "1216911215bec459868266f7886d18f8"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.7.6.aar",
          "url": "adwhale-core-sdk-uat-2.7.6.aar",
          "size": 54855,
          "sha512": "f234db23f2502fd5d2759c968531dbc07c71a90a6881a6bdc5f35efcd281fda21c29ff68e68a5b4c3a534927970f504e569d7e72129375112bead86cae6943fb",
          "sha256": "434c07455926317a4a5875b761f35970bb6f8f8ea027f20ec14497cacde47671",
          "sha1": "eaefbaf2d0a9cab1eea346f9964184fdfd68067d",
          "md5": "1216911215bec459868266f7886d18f8"
        }
      ]
    }
  ]
}
