{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admob.adapter",
    "module": "admob-sdk",
    "version": "24.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admob-sdk-24.3.0.1.aar",
          "url": "admob-sdk-24.3.0.1.aar",
          "size": 133776,
          "sha512": "450a485ee77b93e1779d50fea3396237091c9499617a026d22b76723d7b883082e5ddcdc7ade51380ebd7d03d86f96fc794bfdb000e4518765d98e9ac8f0bedb",
          "sha256": "a32112e52d4381c846e311bd5e93a0d98d9b88d68ed9d716778cc46c3f13aed4",
          "sha1": "25ab79985edf0da9e45d41abfe40d046771a43f7",
          "md5": "4efdf2f438cc4397ef028a5595105bd8"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "admob-sdk-24.3.0.1.aar",
          "url": "admob-sdk-24.3.0.1.aar",
          "size": 133776,
          "sha512": "450a485ee77b93e1779d50fea3396237091c9499617a026d22b76723d7b883082e5ddcdc7ade51380ebd7d03d86f96fc794bfdb000e4518765d98e9ac8f0bedb",
          "sha256": "a32112e52d4381c846e311bd5e93a0d98d9b88d68ed9d716778cc46c3f13aed4",
          "sha1": "25ab79985edf0da9e45d41abfe40d046771a43f7",
          "md5": "4efdf2f438cc4397ef028a5595105bd8"
        }
      ]
    }
  ]
}
