{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk-uat",
    "version": "2.7.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.6.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.6.aar",
          "size": 177014,
          "sha512": "be3b0361c660254f74bc08c2884f0a81d97b8149ddc3ca80167ac3a1b1a177e75334b069d07ab916c6bcd907d8fc6d75e6676ea4375651e4da239b4daf489b0a",
          "sha256": "0a89e93b263d2ce866a2845a9fde5e12170fbf5f146f0094924858f730f7ffc2",
          "sha1": "a51376dd33d52e7173a439c13d281000d09a6784",
          "md5": "4c205ce80dbacf4c43ec3fdc224dbc1b"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.6.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.6.aar",
          "size": 177014,
          "sha512": "be3b0361c660254f74bc08c2884f0a81d97b8149ddc3ca80167ac3a1b1a177e75334b069d07ab916c6bcd907d8fc6d75e6676ea4375651e4da239b4daf489b0a",
          "sha256": "0a89e93b263d2ce866a2845a9fde5e12170fbf5f146f0094924858f730f7ffc2",
          "sha1": "a51376dd33d52e7173a439c13d281000d09a6784",
          "md5": "4c205ce80dbacf4c43ec3fdc224dbc1b"
        }
      ]
    }
  ]
}
