{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk",
    "version": "8.7.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-8.7.0.1.aar",
          "url": "levelplay-sdk-8.7.0.1.aar",
          "size": 19008,
          "sha512": "48c16833f0a2be4dc8d3e09b2305f7f1740284f4c931aeb46fd1076d1819ad780f4ca2f7425b309f123aa8d0328c821a840e708c48b89ef67d8f6115e9e1cdd3",
          "sha256": "94d5c02ab433091c001439c2b32e6665aede5ff52fadb36cca871803042e1922",
          "sha1": "cef117f5e89b5acbe3008868f73fc614f62515de",
          "md5": "a5883d85b7f4cb7ff4c1c5eb80fa86bd"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.5.9"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-8.7.0.1.aar",
          "url": "levelplay-sdk-8.7.0.1.aar",
          "size": 19008,
          "sha512": "48c16833f0a2be4dc8d3e09b2305f7f1740284f4c931aeb46fd1076d1819ad780f4ca2f7425b309f123aa8d0328c821a840e708c48b89ef67d8f6115e9e1cdd3",
          "sha256": "94d5c02ab433091c001439c2b32e6665aede5ff52fadb36cca871803042e1922",
          "sha1": "cef117f5e89b5acbe3008868f73fc614f62515de",
          "md5": "a5883d85b7f4cb7ff4c1c5eb80fa86bd"
        }
      ]
    }
  ]
}
