{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.cauly.adapter",
    "module": "cauly-sdk-uat",
    "version": "3.5.40.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.40.4.aar",
          "url": "cauly-sdk-uat-3.5.40.4.aar",
          "size": 38780,
          "sha512": "40168cf7e1407c7901dfc01a2ca9259890550249998f25f2a97edcc0b054aa704dc4b9ca53bb7264bf1656632eecb60dd41dbc1247606beb933ed51e244510af",
          "sha256": "8fa81d1b0173ad9b16f0237f56e47e6138092adaaeb4553ce70b844d3790deb0",
          "sha1": "73c4c0aef62aa1077a87aa9b9b318b75ee90e02c",
          "md5": "6c377c10f8448e461042d91ee99b4d4e"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "com.fsn.cauly",
          "module": "cauly-sdk-uat",
          "version": {
            "requires": "3.5.40"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.40.4.aar",
          "url": "cauly-sdk-uat-3.5.40.4.aar",
          "size": 38780,
          "sha512": "40168cf7e1407c7901dfc01a2ca9259890550249998f25f2a97edcc0b054aa704dc4b9ca53bb7264bf1656632eecb60dd41dbc1247606beb933ed51e244510af",
          "sha256": "8fa81d1b0173ad9b16f0237f56e47e6138092adaaeb4553ce70b844d3790deb0",
          "sha1": "73c4c0aef62aa1077a87aa9b9b318b75ee90e02c",
          "md5": "6c377c10f8448e461042d91ee99b4d4e"
        }
      ]
    }
  ]
}
