{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk-uat",
    "version": "2.5.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.5.9.aar",
          "url": "adwhale-mediation-sdk-uat-2.5.9.aar",
          "size": 114781,
          "sha512": "6c0a0b68e047bc52517b21679a1b0ad9067782e6f453633287401ea98422c251abb3acab3e96a271b6fd7c28761fbcf46f378d189cd2ddb9f299eb6170fa1951",
          "sha256": "1c1edb751c10a92ce44eab939de01b3c0b17502024f66efc32ec3502e09dc56b",
          "sha1": "3799270f1b5c9115a6cfc933651669bb6c6affdd",
          "md5": "46482192dec26a442fcbd8f862812cbd"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.5.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.5.9.aar",
          "url": "adwhale-mediation-sdk-uat-2.5.9.aar",
          "size": 114781,
          "sha512": "6c0a0b68e047bc52517b21679a1b0ad9067782e6f453633287401ea98422c251abb3acab3e96a271b6fd7c28761fbcf46f378d189cd2ddb9f299eb6170fa1951",
          "sha256": "1c1edb751c10a92ce44eab939de01b3c0b17502024f66efc32ec3502e09dc56b",
          "sha1": "3799270f1b5c9115a6cfc933651669bb6c6affdd",
          "md5": "46482192dec26a442fcbd8f862812cbd"
        }
      ]
    }
  ]
}
