{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk-uat",
    "version": "2.5.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.5.9.aar",
          "url": "adwhale-mediation-sdk-uat-2.5.9.aar",
          "size": 114837,
          "sha512": "a98de20fa233d90f48fbcead682f54c16d027c2f12b316244872703c893a9c1c8c0d46a1a6357995000fcf4050303ae17bfdf79e4558b7ec7d9ca812f5a30fbe",
          "sha256": "a9d92fe4bf46bbcf6df384285e89e3dbbbbeecad0fe3db8a688ad6bde1fadd2a",
          "sha1": "72bcf15822a83e199b6b6a99c12070cc51d2b57e",
          "md5": "c9c018bf21e62fdd94526a8a876f9a81"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.5.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.5.9.aar",
          "url": "adwhale-mediation-sdk-uat-2.5.9.aar",
          "size": 114837,
          "sha512": "a98de20fa233d90f48fbcead682f54c16d027c2f12b316244872703c893a9c1c8c0d46a1a6357995000fcf4050303ae17bfdf79e4558b7ec7d9ca812f5a30fbe",
          "sha256": "a9d92fe4bf46bbcf6df384285e89e3dbbbbeecad0fe3db8a688ad6bde1fadd2a",
          "sha1": "72bcf15822a83e199b6b6a99c12070cc51d2b57e",
          "md5": "c9c018bf21e62fdd94526a8a876f9a81"
        }
      ]
    }
  ]
}
