{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk-uat",
    "version": "2.5.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.5.9.aar",
          "url": "adwhale-mediation-sdk-uat-2.5.9.aar",
          "size": 114775,
          "sha512": "2007c8a318f4978d82b893c1417c4fc1605b2058f745021f6ba8225bbc53e3177689a3bde4df17ec36d5d87a6ec46111069ecec8c1f14a11974d32cbce2aeca0",
          "sha256": "bd6c31c9e2e590e9fdee8c804e867d6e2563e6a4d1e8a218a11025449e38d106",
          "sha1": "df572c2d927ef94fc3c145cb84809b98827de774",
          "md5": "a1d8ad0869dc1fc8153a4df8f2481c39"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.5.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.5.9.aar",
          "url": "adwhale-mediation-sdk-uat-2.5.9.aar",
          "size": 114775,
          "sha512": "2007c8a318f4978d82b893c1417c4fc1605b2058f745021f6ba8225bbc53e3177689a3bde4df17ec36d5d87a6ec46111069ecec8c1f14a11974d32cbce2aeca0",
          "sha256": "bd6c31c9e2e590e9fdee8c804e867d6e2563e6a4d1e8a218a11025449e38d106",
          "sha1": "df572c2d927ef94fc3c145cb84809b98827de774",
          "md5": "a1d8ad0869dc1fc8153a4df8f2481c39"
        }
      ]
    }
  ]
}
