{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk-uat",
    "version": "2.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.3.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.3.aar",
          "size": 173766,
          "sha512": "fc3e4d9c592f9945d41e1f8e156b6f0bd515851628f2a698b3394c62c45672858516d15f5640b2e81a5545ba8bc2703843a6eb85ec4ba325c6f6034239de8e18",
          "sha256": "6826a98a01427b7598fead390a428a378a2eb5460e73e07c34f314f71c4f91f5",
          "sha1": "385960ca61576d6b46b11a7d0a30ec4fd4e65eb3",
          "md5": "01839be0fcb31964141f88b8c12a4d42"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.3.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.3.aar",
          "size": 173766,
          "sha512": "fc3e4d9c592f9945d41e1f8e156b6f0bd515851628f2a698b3394c62c45672858516d15f5640b2e81a5545ba8bc2703843a6eb85ec4ba325c6f6034239de8e18",
          "sha256": "6826a98a01427b7598fead390a428a378a2eb5460e73e07c34f314f71c4f91f5",
          "sha1": "385960ca61576d6b46b11a7d0a30ec4fd4e65eb3",
          "md5": "01839be0fcb31964141f88b8c12a4d42"
        }
      ]
    }
  ]
}
