{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk-uat",
    "version": "2.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.3.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.3.aar",
          "size": 143775,
          "sha512": "6bed48f0ba7f0fbceed0fa51a37b6f423d8d5667c338ff291d67b799474b739eddd0e2399ec4cc6948128f96a0942b4c9b11a9ec9051ccb67578b5e25a5d900e",
          "sha256": "ef81352af9861d438c20fdcbbfce2afee457174a35894036371fe0137cc3dd88",
          "sha1": "5ff49b583ef839c0fd541cd952e160ebccb64217",
          "md5": "7b0f36fa4736d7460d182d79e36c0e73"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.3.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.3.aar",
          "size": 143775,
          "sha512": "6bed48f0ba7f0fbceed0fa51a37b6f423d8d5667c338ff291d67b799474b739eddd0e2399ec4cc6948128f96a0942b4c9b11a9ec9051ccb67578b5e25a5d900e",
          "sha256": "ef81352af9861d438c20fdcbbfce2afee457174a35894036371fe0137cc3dd88",
          "sha1": "5ff49b583ef839c0fd541cd952e160ebccb64217",
          "md5": "7b0f36fa4736d7460d182d79e36c0e73"
        }
      ]
    }
  ]
}
