{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk",
    "version": "2.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "realReleaseVariantRealReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-2.7.4.aar",
          "url": "adwhale-core-sdk-2.7.4.aar",
          "size": 49033,
          "sha512": "62c633309b0c295106eaa35ada9d5f275cfbe4a6d7114ff593de7bb574b17af7d160c72bdbbdf374492ceca35a7b212309b5985fa267d47779c3caebc7dbb160",
          "sha256": "8e3c390383547711204712325216ee8330ce3c8d6e6d79e36941800b3d402970",
          "sha1": "12155ff0974c027cc1ecde6ddfff6050c0a32719",
          "md5": "eed6f9767fa11441d7250bab5a7281c7"
        }
      ]
    },
    {
      "name": "realReleaseVariantRealReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-2.7.4.aar",
          "url": "adwhale-core-sdk-2.7.4.aar",
          "size": 49033,
          "sha512": "62c633309b0c295106eaa35ada9d5f275cfbe4a6d7114ff593de7bb574b17af7d160c72bdbbdf374492ceca35a7b212309b5985fa267d47779c3caebc7dbb160",
          "sha256": "8e3c390383547711204712325216ee8330ce3c8d6e6d79e36941800b3d402970",
          "sha1": "12155ff0974c027cc1ecde6ddfff6050c0a32719",
          "md5": "eed6f9767fa11441d7250bab5a7281c7"
        }
      ]
    }
  ]
}
