{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admize.adapter",
    "module": "admize-sdk",
    "version": "1.0.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-1.0.7.2.aar",
          "url": "admize-sdk-1.0.7.2.aar",
          "size": 30769,
          "sha512": "fc6c25c77bed9efb8e7bf3e8eb6cde08b4033752c9ca036fea6e2042af1d8e229654f5a2822b3709ef480d6770a61ef2ccc1545c2a7b5a4ab6d9669ee4ebfcf7",
          "sha256": "3e42ee07365bbc459935190efb2767f1c815db63f98b0b1362f067b0e2d063a5",
          "sha1": "09e4b561d8479e53ec819b8534580504b9ab1ab6",
          "md5": "5a869d792b6ed26861fb82c606fc92da"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "io.admize.sdk.android",
          "module": "admize-sdk-android",
          "version": {
            "requires": "1.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-1.0.7.2.aar",
          "url": "admize-sdk-1.0.7.2.aar",
          "size": 30769,
          "sha512": "fc6c25c77bed9efb8e7bf3e8eb6cde08b4033752c9ca036fea6e2042af1d8e229654f5a2822b3709ef480d6770a61ef2ccc1545c2a7b5a4ab6d9669ee4ebfcf7",
          "sha256": "3e42ee07365bbc459935190efb2767f1c815db63f98b0b1362f067b0e2d063a5",
          "sha1": "09e4b561d8479e53ec819b8534580504b9ab1ab6",
          "md5": "5a869d792b6ed26861fb82c606fc92da"
        }
      ]
    }
  ]
}
