{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk",
    "version": "2.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "realReleaseVariantRealReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-2.7.3.aar",
          "url": "adwhale-core-sdk-2.7.3.aar",
          "size": 45285,
          "sha512": "9501c15d1b09d8e3761a6cb9d7176412cee7fc5a488d63228e0693de0aa306cd0e842074ad8afa37847ffdaa8607a822295527d4f76c2b76a07ca644ce9ee66e",
          "sha256": "c705820f0c7f3faa3ce5aec4f516769da202e0dda389bafd0b4416dba908f56b",
          "sha1": "eade8f82c78e98609ebe7a4e41f9a637991faba6",
          "md5": "2e813ac5e1aa62fde4fc6f66c97f8b4d"
        }
      ]
    },
    {
      "name": "realReleaseVariantRealReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-2.7.3.aar",
          "url": "adwhale-core-sdk-2.7.3.aar",
          "size": 45285,
          "sha512": "9501c15d1b09d8e3761a6cb9d7176412cee7fc5a488d63228e0693de0aa306cd0e842074ad8afa37847ffdaa8607a822295527d4f76c2b76a07ca644ce9ee66e",
          "sha256": "c705820f0c7f3faa3ce5aec4f516769da202e0dda389bafd0b4416dba908f56b",
          "sha1": "eade8f82c78e98609ebe7a4e41f9a637991faba6",
          "md5": "2e813ac5e1aa62fde4fc6f66c97f8b4d"
        }
      ]
    }
  ]
}
