{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk",
    "version": "2.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "realReleaseVariantRealReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-2.7.3.aar",
          "url": "adwhale-core-sdk-2.7.3.aar",
          "size": 48262,
          "sha512": "210f081e220bb23302590683aed33bd6e72882ad2af8927b7254d601ae795534420221aeaf8f615c9c8f3a32676f6400cbe4e12c34dcddbebd7f451301dfbec4",
          "sha256": "b0812336df6d1d331311293d6d2ca12dd237078dac28c38bfac77b8adc7db2b2",
          "sha1": "d4e7cbf8cfa43baaf44c2ee175e0c30586969620",
          "md5": "ebed0134f1d083f5a2cf08a04764cecd"
        }
      ]
    },
    {
      "name": "realReleaseVariantRealReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-2.7.3.aar",
          "url": "adwhale-core-sdk-2.7.3.aar",
          "size": 48262,
          "sha512": "210f081e220bb23302590683aed33bd6e72882ad2af8927b7254d601ae795534420221aeaf8f615c9c8f3a32676f6400cbe4e12c34dcddbebd7f451301dfbec4",
          "sha256": "b0812336df6d1d331311293d6d2ca12dd237078dac28c38bfac77b8adc7db2b2",
          "sha1": "d4e7cbf8cfa43baaf44c2ee175e0c30586969620",
          "md5": "ebed0134f1d083f5a2cf08a04764cecd"
        }
      ]
    }
  ]
}
