{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admize.adapter",
    "module": "admize-sdk",
    "version": "1.0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "realReleaseVariantRealReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-1.0.8.1.aar",
          "url": "admize-sdk-1.0.8.1.aar",
          "size": 31136,
          "sha512": "9d10416e677de5930b7e296d8f00c3e0aa9b0cb41165bb0055ef869065a329e3b0239f4ade61b6ea9440810e22670b560d4b23f9d7d1c8c50f72c2e1e36d7afc",
          "sha256": "3175b07b2ae7d036f7b67556ff11091071d86df8cadb94836f902f3ed11fce6a",
          "sha1": "859193bc4bea8c2b67bba1883fadd92b5ad8c0cc",
          "md5": "0ee39251fdfc12098ab58ed3da85881d"
        }
      ]
    },
    {
      "name": "realReleaseVariantRealReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "io.admize.sdk.android",
          "module": "admize-sdk-android",
          "version": {
            "requires": "1.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-1.0.8.1.aar",
          "url": "admize-sdk-1.0.8.1.aar",
          "size": 31136,
          "sha512": "9d10416e677de5930b7e296d8f00c3e0aa9b0cb41165bb0055ef869065a329e3b0239f4ade61b6ea9440810e22670b560d4b23f9d7d1c8c50f72c2e1e36d7afc",
          "sha256": "3175b07b2ae7d036f7b67556ff11091071d86df8cadb94836f902f3ed11fce6a",
          "sha1": "859193bc4bea8c2b67bba1883fadd92b5ad8c0cc",
          "md5": "0ee39251fdfc12098ab58ed3da85881d"
        }
      ]
    }
  ]
}
