{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk-uat",
    "version": "2.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.7.2.aar",
          "url": "adwhale-core-sdk-uat-2.7.2.aar",
          "size": 47483,
          "sha512": "f8ab5d044b016e99981cbb2f4027713e7cb3858e72e33eb14c0292ea57629061ace2d4281b6b6deca62e112fc750c0d9df74b777420020ea8119c0340ec15586",
          "sha256": "49bc304799012e5c6f8634987ead869c2d4c3810026f99cc0ba522384a48c971",
          "sha1": "d56b4e32fea038f797bcea00769f500fdf86d2f9",
          "md5": "41d285485ca23ef1bc270ec3a453b0f2"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.7.2.aar",
          "url": "adwhale-core-sdk-uat-2.7.2.aar",
          "size": 47483,
          "sha512": "f8ab5d044b016e99981cbb2f4027713e7cb3858e72e33eb14c0292ea57629061ace2d4281b6b6deca62e112fc750c0d9df74b777420020ea8119c0340ec15586",
          "sha256": "49bc304799012e5c6f8634987ead869c2d4c3810026f99cc0ba522384a48c971",
          "sha1": "d56b4e32fea038f797bcea00769f500fdf86d2f9",
          "md5": "41d285485ca23ef1bc270ec3a453b0f2"
        }
      ]
    }
  ]
}
