{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk",
    "version": "8.7.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-8.7.0.5.aar",
          "url": "levelplay-sdk-8.7.0.5.aar",
          "size": 22379,
          "sha512": "d3f74af59a217fb088dfaa4e4b99efd7686222a178d779da2018ee39a7634a1ba5b0b9084815e355cc7a4354d4740d5f4db5db182ba5ed2bbaeda554b4f5b074",
          "sha256": "0486bf04d6842a87b4f8821e9672c627681a530f0965b769b7082153e32aa27e",
          "sha1": "22ea6f9aebb865bf9e6b9148153a12dfdaf227c6",
          "md5": "7ae8932ac3888e165ff72a85627c496d"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-8.7.0.5.aar",
          "url": "levelplay-sdk-8.7.0.5.aar",
          "size": 22379,
          "sha512": "d3f74af59a217fb088dfaa4e4b99efd7686222a178d779da2018ee39a7634a1ba5b0b9084815e355cc7a4354d4740d5f4db5db182ba5ed2bbaeda554b4f5b074",
          "sha256": "0486bf04d6842a87b4f8821e9672c627681a530f0965b769b7082153e32aa27e",
          "sha1": "22ea6f9aebb865bf9e6b9148153a12dfdaf227c6",
          "md5": "7ae8932ac3888e165ff72a85627c496d"
        }
      ]
    }
  ]
}
