{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admob.adapter",
    "module": "admob-sdk-uat",
    "version": "23.6.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admob-sdk-uat-23.6.0.2.aar",
          "url": "admob-sdk-uat-23.6.0.2.aar",
          "size": 69106,
          "sha512": "bffc578a1f6f1aba88aa2f1bf785d0a6a918d48009a9096c6983d468b5422cb17b625bba5033948219dc527dc17ac47e55704bbce14cf4a251878af1d07af911",
          "sha256": "dabae8e392f271ff552076d0c6d893bc2b54c9c002aa892967a7e14cff298e49",
          "sha1": "9e52533bc7227d9ffebe634aa1192eb989c910f6",
          "md5": "da9877e5eb21eac34481823d3288e346"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "admob-sdk-uat-23.6.0.2.aar",
          "url": "admob-sdk-uat-23.6.0.2.aar",
          "size": 69106,
          "sha512": "bffc578a1f6f1aba88aa2f1bf785d0a6a918d48009a9096c6983d468b5422cb17b625bba5033948219dc527dc17ac47e55704bbce14cf4a251878af1d07af911",
          "sha256": "dabae8e392f271ff552076d0c6d893bc2b54c9c002aa892967a7e14cff298e49",
          "sha1": "9e52533bc7227d9ffebe634aa1192eb989c910f6",
          "md5": "da9877e5eb21eac34481823d3288e346"
        }
      ]
    }
  ]
}
