{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admob.adapter",
    "module": "admob-sdk-uat",
    "version": "23.6.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admob-sdk-uat-23.6.0.2.aar",
          "url": "admob-sdk-uat-23.6.0.2.aar",
          "size": 83051,
          "sha512": "94d31f0fb263b698bfcda38f6a75e6c52dc51ebf3b5baf7685926ec86c20b4edabee75c3c7f8260510272688bf3fa8172a535657785f5830ce8a0c878e9b2149",
          "sha256": "75e93e0ddec30717086abf55d659f90a549970058c18344c53a642727f8aab8b",
          "sha1": "2c77868054e9fb4fb7f0ee69eaeb5f0db1c527b8",
          "md5": "5d2f299a583017481e8c2f42317c2ccc"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "admob-sdk-uat-23.6.0.2.aar",
          "url": "admob-sdk-uat-23.6.0.2.aar",
          "size": 83051,
          "sha512": "94d31f0fb263b698bfcda38f6a75e6c52dc51ebf3b5baf7685926ec86c20b4edabee75c3c7f8260510272688bf3fa8172a535657785f5830ce8a0c878e9b2149",
          "sha256": "75e93e0ddec30717086abf55d659f90a549970058c18344c53a642727f8aab8b",
          "sha1": "2c77868054e9fb4fb7f0ee69eaeb5f0db1c527b8",
          "md5": "5d2f299a583017481e8c2f42317c2ccc"
        }
      ]
    }
  ]
}
