{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk-uat",
    "version": "2.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.2.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.2.aar",
          "size": 154813,
          "sha512": "fa3e6bd822b3089b5f52db75c832f8b13975e10a79e56c07c85c23eb88bc4a4bb1dcb39da6ceecc5ab0bf3d1559507f0f2c8ea39747e7e389ad821a33524c961",
          "sha256": "35450315354aecdac6442fe687aa489d7bed489902ca8fd63840508183a1db9d",
          "sha1": "5829e0861e2b8b864997b52e3fcd4351f3bc1d70",
          "md5": "089d2f13bcbafbf6d8f39825009bad9d"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.2.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.2.aar",
          "size": 154813,
          "sha512": "fa3e6bd822b3089b5f52db75c832f8b13975e10a79e56c07c85c23eb88bc4a4bb1dcb39da6ceecc5ab0bf3d1559507f0f2c8ea39747e7e389ad821a33524c961",
          "sha256": "35450315354aecdac6442fe687aa489d7bed489902ca8fd63840508183a1db9d",
          "sha1": "5829e0861e2b8b864997b52e3fcd4351f3bc1d70",
          "md5": "089d2f13bcbafbf6d8f39825009bad9d"
        }
      ]
    }
  ]
}
