{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk-uat",
    "version": "2.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.2.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.2.aar",
          "size": 154652,
          "sha512": "138ee73e93e69e5cba84ac1d32d7d5bed1291e119e2ed489af405af9193bcbbf862e4e27745e69ea429be23555afb986f9054fe38417280ce7d5fc7493c6e323",
          "sha256": "529da8a885b0dd8ee32dbbc1cbaec097ec527b9801d21b38fca3e1cb9fda5ee0",
          "sha1": "233dbb0379ad9f71e5177e6c80eb662ae6744919",
          "md5": "00d6e33a52be8a7dabdb0bac028b7dc2"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.2.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.2.aar",
          "size": 154652,
          "sha512": "138ee73e93e69e5cba84ac1d32d7d5bed1291e119e2ed489af405af9193bcbbf862e4e27745e69ea429be23555afb986f9054fe38417280ce7d5fc7493c6e323",
          "sha256": "529da8a885b0dd8ee32dbbc1cbaec097ec527b9801d21b38fca3e1cb9fda5ee0",
          "sha1": "233dbb0379ad9f71e5177e6c80eb662ae6744919",
          "md5": "00d6e33a52be8a7dabdb0bac028b7dc2"
        }
      ]
    }
  ]
}
