{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk-uat",
    "version": "2.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.2.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.2.aar",
          "size": 154859,
          "sha512": "ff5bc14e72584bd53c28f209967213bab1879d4effef7900b3be12aca3823fe569ecf5650d3c3ca6263876769c9d590880b0bfd2970c50ffcaa26eac04283758",
          "sha256": "4f8fb5064e941e0bf89b847249db599f3987d6bc81fb89af726f7da8c4eff652",
          "sha1": "27b63a499f41b4c6d5af7004c6ad7c7ed809f41f",
          "md5": "45eac9d47ffb8ba5bd055e98e633bf22"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.2.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.2.aar",
          "size": 154859,
          "sha512": "ff5bc14e72584bd53c28f209967213bab1879d4effef7900b3be12aca3823fe569ecf5650d3c3ca6263876769c9d590880b0bfd2970c50ffcaa26eac04283758",
          "sha256": "4f8fb5064e941e0bf89b847249db599f3987d6bc81fb89af726f7da8c4eff652",
          "sha1": "27b63a499f41b4c6d5af7004c6ad7c7ed809f41f",
          "md5": "45eac9d47ffb8ba5bd055e98e633bf22"
        }
      ]
    }
  ]
}
