{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk-uat",
    "version": "8.7.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.0.aar",
          "url": "levelplay-sdk-uat-8.7.0.0.aar",
          "size": 21899,
          "sha512": "824eb4998e1a126dc13d451568daf750ce24a0163fd8b00d43f60954c47a2d47d4d7d59262da09d4b21c0bdb35431cdd5dfacbdc6c547c51416a0923e68112e0",
          "sha256": "4b024d7e7578e3190ec9efbd5e85a0172582f5cd828c463a37dd3de50c109471",
          "sha1": "817ef7d80199c12fab012f3c0a618738974a8929",
          "md5": "57a4774fe69b748beeafdb84e8b0cea7"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.0.aar",
          "url": "levelplay-sdk-uat-8.7.0.0.aar",
          "size": 21899,
          "sha512": "824eb4998e1a126dc13d451568daf750ce24a0163fd8b00d43f60954c47a2d47d4d7d59262da09d4b21c0bdb35431cdd5dfacbdc6c547c51416a0923e68112e0",
          "sha256": "4b024d7e7578e3190ec9efbd5e85a0172582f5cd828c463a37dd3de50c109471",
          "sha1": "817ef7d80199c12fab012f3c0a618738974a8929",
          "md5": "57a4774fe69b748beeafdb84e8b0cea7"
        }
      ]
    }
  ]
}
