{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admob.adapter",
    "module": "admob-sdk-uat",
    "version": "24.3.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admob-sdk-uat-24.3.0.5.aar",
          "url": "admob-sdk-uat-24.3.0.5.aar",
          "size": 182453,
          "sha512": "7e2c8549789ea656bcdc28096fa8387c0f0c3747eb10d19418c6ede975e8314ec211541ce4a1c39723e3d73911b154753b409b56bbb722a1ffbe9170ce675dee",
          "sha256": "3fb23efe7c0793b58c1b7b5d9a9d6bc71749bb3f3dcebf9f9dde0af323cc3884",
          "sha1": "a99f3d77aa5f0027d77fe1787dbbc18da32e76b7",
          "md5": "da228a596bd276cd1b7090f70f7ea54c"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "net.adwhale.sdk.cauly.adapter",
          "module": "cauly-sdk-uat",
          "version": {
            "requires": "3.5.44.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "admob-sdk-uat-24.3.0.5.aar",
          "url": "admob-sdk-uat-24.3.0.5.aar",
          "size": 182453,
          "sha512": "7e2c8549789ea656bcdc28096fa8387c0f0c3747eb10d19418c6ede975e8314ec211541ce4a1c39723e3d73911b154753b409b56bbb722a1ffbe9170ce675dee",
          "sha256": "3fb23efe7c0793b58c1b7b5d9a9d6bc71749bb3f3dcebf9f9dde0af323cc3884",
          "sha1": "a99f3d77aa5f0027d77fe1787dbbc18da32e76b7",
          "md5": "da228a596bd276cd1b7090f70f7ea54c"
        }
      ]
    }
  ]
}
