{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk",
    "version": "3.17.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "realReleaseVariantRealReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-3.17.2.6.aar",
          "url": "adfit-sdk-3.17.2.6.aar",
          "size": 13867,
          "sha512": "fdd0184b6c950ee5b45644511621477e14d563433b2f270d9da6d130a546e6e8ddacb4c4962d027dfc1d842fd8f6272b75ca4fa34f81c46ef07acb283f26d702",
          "sha256": "44a8884e54d30485e71c396301e3725c341956821e516c34c608aa776e8e770d",
          "sha1": "65483bd5683cca4cb096a87c9773e37fc48fa0c8",
          "md5": "f1a105c5ddb39ddb228da3209c7aeef3"
        }
      ]
    },
    {
      "name": "realReleaseVariantRealReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-3.17.2.6.aar",
          "url": "adfit-sdk-3.17.2.6.aar",
          "size": 13867,
          "sha512": "fdd0184b6c950ee5b45644511621477e14d563433b2f270d9da6d130a546e6e8ddacb4c4962d027dfc1d842fd8f6272b75ca4fa34f81c46ef07acb283f26d702",
          "sha256": "44a8884e54d30485e71c396301e3725c341956821e516c34c608aa776e8e770d",
          "sha1": "65483bd5683cca4cb096a87c9773e37fc48fa0c8",
          "md5": "f1a105c5ddb39ddb228da3209c7aeef3"
        }
      ]
    }
  ]
}
