{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.cauly.adapter",
    "module": "cauly-sdk-uat",
    "version": "3.5.42.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.42.0.aar",
          "url": "cauly-sdk-uat-3.5.42.0.aar",
          "size": 39707,
          "sha512": "76e39a6c9d3ae42c0290b76186c04c149b16903d1b80bfaf5dc50d07417c06f6e1396578fe24822f65268ad6572ab87d8f9992ea873b6561709cf73d9461f008",
          "sha256": "298f9cbffd411b672e65712e83ec2f60cfc6b3577df15d63be9060219ab2f190",
          "sha1": "339f76f9947e33f7f166a142237d7be315f46465",
          "md5": "21196c53074b3126439609704adfd2c6"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "com.fsn.cauly",
          "module": "cauly-sdk-uat",
          "version": {
            "requires": "3.5.42"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.42.0.aar",
          "url": "cauly-sdk-uat-3.5.42.0.aar",
          "size": 39707,
          "sha512": "76e39a6c9d3ae42c0290b76186c04c149b16903d1b80bfaf5dc50d07417c06f6e1396578fe24822f65268ad6572ab87d8f9992ea873b6561709cf73d9461f008",
          "sha256": "298f9cbffd411b672e65712e83ec2f60cfc6b3577df15d63be9060219ab2f190",
          "sha1": "339f76f9947e33f7f166a142237d7be315f46465",
          "md5": "21196c53074b3126439609704adfd2c6"
        }
      ]
    }
  ]
}
