{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.cauly.adapter",
    "module": "cauly-sdk-uat",
    "version": "3.5.42.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.42.0.aar",
          "url": "cauly-sdk-uat-3.5.42.0.aar",
          "size": 39707,
          "sha512": "760e49de94f392bdd7510c87fab2dc12eaf0a6b21af21d0e05fb8b313b48904adf92e545de472cc460fd3632f254523d22a60fa66718870cd424e62e68c02f28",
          "sha256": "a31d5f22fea24b7ebb2e2bec48d63ebba8d0ef683d52bdd0f72c3f75831bd644",
          "sha1": "00d243e2c328fb05088866c52e8eff2ad0491f7e",
          "md5": "717bbb6a90b999ef9cf29863a2592512"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "com.fsn.cauly",
          "module": "cauly-sdk-uat",
          "version": {
            "requires": "3.5.42"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.42.0.aar",
          "url": "cauly-sdk-uat-3.5.42.0.aar",
          "size": 39707,
          "sha512": "760e49de94f392bdd7510c87fab2dc12eaf0a6b21af21d0e05fb8b313b48904adf92e545de472cc460fd3632f254523d22a60fa66718870cd424e62e68c02f28",
          "sha256": "a31d5f22fea24b7ebb2e2bec48d63ebba8d0ef683d52bdd0f72c3f75831bd644",
          "sha1": "00d243e2c328fb05088866c52e8eff2ad0491f7e",
          "md5": "717bbb6a90b999ef9cf29863a2592512"
        }
      ]
    }
  ]
}
