{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk",
    "version": "3.17.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-3.17.2.1.aar",
          "url": "adfit-sdk-3.17.2.1.aar",
          "size": 7037,
          "sha512": "7b3da1e29ef40138966099970cb64200ddbe04082d781138d5111f0ccdf4f142992e90ba644b549a0a7dbb0fbb363a7c7efd1615c34316275cc1ca58eccee26c",
          "sha256": "268af8a51faffb53769960469f3b10e459e3ab616ee9443f33a5183129d0727f",
          "sha1": "fc7dfb94ef920ad26e26ddd7be4455cf50b61810",
          "md5": "8b57089f7ef36f3af77d2b21019d8231"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-3.17.2.1.aar",
          "url": "adfit-sdk-3.17.2.1.aar",
          "size": 7037,
          "sha512": "7b3da1e29ef40138966099970cb64200ddbe04082d781138d5111f0ccdf4f142992e90ba644b549a0a7dbb0fbb363a7c7efd1615c34316275cc1ca58eccee26c",
          "sha256": "268af8a51faffb53769960469f3b10e459e3ab616ee9443f33a5183129d0727f",
          "sha1": "fc7dfb94ef920ad26e26ddd7be4455cf50b61810",
          "md5": "8b57089f7ef36f3af77d2b21019d8231"
        }
      ]
    }
  ]
}
