{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk-uat",
    "version": "3.17.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.0.aar",
          "url": "adfit-sdk-uat-3.17.2.0.aar",
          "size": 8485,
          "sha512": "8391c45fe6abc242aa03c51726a7e528dbc86f28d1f7cf5ce3155fb942e8cd91184d103f2e77f2c8895b3a2bb901edb343d827190c5fe7550b0f7d7f8432e5b8",
          "sha256": "7ec7a52e27a3a144a6f07267b09bff3151e3616df6b657251018f1951f51f096",
          "sha1": "359c1782005f7d719a8c4f2b5701b34ed351399b",
          "md5": "b59fd043aec0fa6c8445872a86df2455"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.0.aar",
          "url": "adfit-sdk-uat-3.17.2.0.aar",
          "size": 8485,
          "sha512": "8391c45fe6abc242aa03c51726a7e528dbc86f28d1f7cf5ce3155fb942e8cd91184d103f2e77f2c8895b3a2bb901edb343d827190c5fe7550b0f7d7f8432e5b8",
          "sha256": "7ec7a52e27a3a144a6f07267b09bff3151e3616df6b657251018f1951f51f096",
          "sha1": "359c1782005f7d719a8c4f2b5701b34ed351399b",
          "md5": "b59fd043aec0fa6c8445872a86df2455"
        }
      ]
    }
  ]
}
