{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admize.adapter",
    "module": "admize-sdk",
    "version": "1.0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-1.0.6.1.aar",
          "url": "admize-sdk-1.0.6.1.aar",
          "size": 23345,
          "sha512": "476feeb329f9215d5eb1a7de658b55067f1c853c7934cb22c78423d0ad665a60b442c13c525cd370a0f908acb7e3c7d66a9e2c5bf60ca74e7a31239762911ea7",
          "sha256": "4fb1b2420692025bb0e16d14bfb42364ae72c7abf0540c4d03f7d76aef124421",
          "sha1": "d9970c6cf062e1add3925c2da31b1c64720a3665",
          "md5": "12094877c4c28844caee935549afbfe9"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "io.admize.sdk.android",
          "module": "admize-sdk-android",
          "version": {
            "requires": "1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-1.0.6.1.aar",
          "url": "admize-sdk-1.0.6.1.aar",
          "size": 23345,
          "sha512": "476feeb329f9215d5eb1a7de658b55067f1c853c7934cb22c78423d0ad665a60b442c13c525cd370a0f908acb7e3c7d66a9e2c5bf60ca74e7a31239762911ea7",
          "sha256": "4fb1b2420692025bb0e16d14bfb42364ae72c7abf0540c4d03f7d76aef124421",
          "sha1": "d9970c6cf062e1add3925c2da31b1c64720a3665",
          "md5": "12094877c4c28844caee935549afbfe9"
        }
      ]
    }
  ]
}
