{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admize.adapter",
    "module": "admize-sdk",
    "version": "1.0.5.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-1.0.5.8.aar",
          "url": "admize-sdk-1.0.5.8.aar",
          "size": 22119,
          "sha512": "bb5ba40a8ec343f47c2fe1ac0087af55de5748511fe39f37cb6b6e97f5ebbc74c85268fc010065d91523169645ce7cddd0b86fc70164af3d78836199d9f0e54a",
          "sha256": "4670beec95f37e32766ecebca7378bbf2703f957c7860fa569ba19040796a8ce",
          "sha1": "69813ead3fe7e0ca6bdd236a9828ea650afd34d2",
          "md5": "8f197fcc0ee6350e91c4acec5af0819f"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "io.admize.sdk.android",
          "module": "admize-sdk-android",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-1.0.5.8.aar",
          "url": "admize-sdk-1.0.5.8.aar",
          "size": 22119,
          "sha512": "bb5ba40a8ec343f47c2fe1ac0087af55de5748511fe39f37cb6b6e97f5ebbc74c85268fc010065d91523169645ce7cddd0b86fc70164af3d78836199d9f0e54a",
          "sha256": "4670beec95f37e32766ecebca7378bbf2703f957c7860fa569ba19040796a8ce",
          "sha1": "69813ead3fe7e0ca6bdd236a9828ea650afd34d2",
          "md5": "8f197fcc0ee6350e91c4acec5af0819f"
        }
      ]
    }
  ]
}
