{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk-uat",
    "version": "2.7.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.7.7.aar",
          "url": "adwhale-core-sdk-uat-2.7.7.aar",
          "size": 54875,
          "sha512": "9f0a98deeff95ef11af83c77308ecfbb1be7e7bbaef527608eef1fcf4cf82cdac7393bc5d81c95054e04b71e1982b8cb1cc44e58ed372380f329257bf2265fe6",
          "sha256": "025fb42c6402d70eba960b22dbb99ba4ce2c9da580e143faf9f7e95b99442257",
          "sha1": "36eb247ca51eacacaedc072452318301b433eca6",
          "md5": "1d7e41d62b2bd2592daf18f44aee3601"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.7.7.aar",
          "url": "adwhale-core-sdk-uat-2.7.7.aar",
          "size": 54875,
          "sha512": "9f0a98deeff95ef11af83c77308ecfbb1be7e7bbaef527608eef1fcf4cf82cdac7393bc5d81c95054e04b71e1982b8cb1cc44e58ed372380f329257bf2265fe6",
          "sha256": "025fb42c6402d70eba960b22dbb99ba4ce2c9da580e143faf9f7e95b99442257",
          "sha1": "36eb247ca51eacacaedc072452318301b433eca6",
          "md5": "1d7e41d62b2bd2592daf18f44aee3601"
        }
      ]
    }
  ]
}
