{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.6.0.aar",
          "url": "adwhale-mediation-sdk-2.6.0.aar",
          "size": 90940,
          "sha512": "efe25010820f237c0c7bffdce0a15d44e8475206b9494f495afbbfd5c23f5ff24d9318ed54e6a6c7bc66c1184100d597d9f8ded1a5236b1d8f05624a8683c7c9",
          "sha256": "693331522557c0d1739984fb3cdd92ec038a06b846f9f27671a62df5b31710a3",
          "sha1": "a541265dcb3a2d27733f707af469964321675c0d",
          "md5": "34c8ff9f72813bcd18129e2437049d1a"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.6.0.aar",
          "url": "adwhale-mediation-sdk-2.6.0.aar",
          "size": 90940,
          "sha512": "efe25010820f237c0c7bffdce0a15d44e8475206b9494f495afbbfd5c23f5ff24d9318ed54e6a6c7bc66c1184100d597d9f8ded1a5236b1d8f05624a8683c7c9",
          "sha256": "693331522557c0d1739984fb3cdd92ec038a06b846f9f27671a62df5b31710a3",
          "sha1": "a541265dcb3a2d27733f707af469964321675c0d",
          "md5": "34c8ff9f72813bcd18129e2437049d1a"
        }
      ]
    }
  ]
}
