{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.6.0.aar",
          "url": "adwhale-mediation-sdk-2.6.0.aar",
          "size": 89262,
          "sha512": "5eb5c4b26f02e9cd34ec294859ff3f48a188c412f242bbcc763c0ed6906d19475c9b36406d548a86afae2aac47d69174217454077ddd3fefc9c65556defaab1a",
          "sha256": "1c85e25e7c0ae32223778722d53aaaa45f36626277adb3f9d88df1073f6da00b",
          "sha1": "47d071275e04843954dcfe113e336c61ffd56215",
          "md5": "e28412a63b5b07a7e2f991d9889c54a1"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.6.0.aar",
          "url": "adwhale-mediation-sdk-2.6.0.aar",
          "size": 89262,
          "sha512": "5eb5c4b26f02e9cd34ec294859ff3f48a188c412f242bbcc763c0ed6906d19475c9b36406d548a86afae2aac47d69174217454077ddd3fefc9c65556defaab1a",
          "sha256": "1c85e25e7c0ae32223778722d53aaaa45f36626277adb3f9d88df1073f6da00b",
          "sha1": "47d071275e04843954dcfe113e336c61ffd56215",
          "md5": "e28412a63b5b07a7e2f991d9889c54a1"
        }
      ]
    }
  ]
}
