{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk-uat",
    "version": "8.7.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.7.aar",
          "url": "levelplay-sdk-uat-8.7.0.7.aar",
          "size": 56657,
          "sha512": "486678dbb836f782f14b80a465e212909d331caff624bc1cdb299004b1da23e1e11ab0999fc1e5347d80b5247984beac1837a866b910ec99198d57fd814cc627",
          "sha256": "0c8a4a84bdb01e19799b5caaee2628e6c2321e4551e6781def72ea97b4799792",
          "sha1": "0cfd19b51b6a5dcb91becc1a055fd0afa83b3f19",
          "md5": "6661d06ad7b5b5aa2696f26fd24c32b2"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.7.aar",
          "url": "levelplay-sdk-uat-8.7.0.7.aar",
          "size": 56657,
          "sha512": "486678dbb836f782f14b80a465e212909d331caff624bc1cdb299004b1da23e1e11ab0999fc1e5347d80b5247984beac1837a866b910ec99198d57fd814cc627",
          "sha256": "0c8a4a84bdb01e19799b5caaee2628e6c2321e4551e6781def72ea97b4799792",
          "sha1": "0cfd19b51b6a5dcb91becc1a055fd0afa83b3f19",
          "md5": "6661d06ad7b5b5aa2696f26fd24c32b2"
        }
      ]
    }
  ]
}
