{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk-uat",
    "version": "8.7.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.7.aar",
          "url": "levelplay-sdk-uat-8.7.0.7.aar",
          "size": 55679,
          "sha512": "5d1dc9c59c63c0ca2ca8783def407d3c50bd2b456b40a007a0fe61a6398c3452f943954c7f9b12f7c74953a98f5da49161c4af0eb23f6095a77535112b0b9997",
          "sha256": "54dab6a09954d268d40008c46d5b32c376b4d9822a65f4b5abf1b5e1901e9916",
          "sha1": "8d05e2bfbe0d9fd998565b645f304e36d8e9752e",
          "md5": "8259f15c0dd7f08ec078d5daef244d73"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-uat-8.7.0.7.aar",
          "url": "levelplay-sdk-uat-8.7.0.7.aar",
          "size": 55679,
          "sha512": "5d1dc9c59c63c0ca2ca8783def407d3c50bd2b456b40a007a0fe61a6398c3452f943954c7f9b12f7c74953a98f5da49161c4af0eb23f6095a77535112b0b9997",
          "sha256": "54dab6a09954d268d40008c46d5b32c376b4d9822a65f4b5abf1b5e1901e9916",
          "sha1": "8d05e2bfbe0d9fd998565b645f304e36d8e9752e",
          "md5": "8259f15c0dd7f08ec078d5daef244d73"
        }
      ]
    }
  ]
}
