{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.cauly.adapter",
    "module": "cauly-sdk-uat",
    "version": "3.5.46.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.46.2.aar",
          "url": "cauly-sdk-uat-3.5.46.2.aar",
          "size": 45577,
          "sha512": "0951a77561a67c1374c099a91599e8d68390c69fadb48a49ff6460413c439a72c9f38f2e6345961fb7ee783c01530f4fcc963d28ce2b4f803684799bc2a53675",
          "sha256": "74d5bab9ec4e8a3dd82c8e6052a0bff62d4ae61c20290cccc90d11e5acee7a63",
          "sha1": "98d0bec6f0c1128fa8455dc476cffbb1e703e7f0",
          "md5": "26424fba99cdec89ff086f55cfb60af6"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.8"
          }
        },
        {
          "group": "com.fsn.cauly",
          "module": "cauly-sdk-uat",
          "version": {
            "requires": "3.5.46"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.8.9"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.46.2.aar",
          "url": "cauly-sdk-uat-3.5.46.2.aar",
          "size": 45577,
          "sha512": "0951a77561a67c1374c099a91599e8d68390c69fadb48a49ff6460413c439a72c9f38f2e6345961fb7ee783c01530f4fcc963d28ce2b4f803684799bc2a53675",
          "sha256": "74d5bab9ec4e8a3dd82c8e6052a0bff62d4ae61c20290cccc90d11e5acee7a63",
          "sha1": "98d0bec6f0c1128fa8455dc476cffbb1e703e7f0",
          "md5": "26424fba99cdec89ff086f55cfb60af6"
        }
      ]
    }
  ]
}
