{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admob.adapter",
    "module": "admob-sdk",
    "version": "24.3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admob-sdk-24.3.0.0.aar",
          "url": "admob-sdk-24.3.0.0.aar",
          "size": 132954,
          "sha512": "79eea90b8ade3ad4b97927f38b2291a7ff0506290587b527fe959609e5f02e29aaac8e13231fbfb99c700ea86d01ffdc5b4ad23b87c339a6e95a92bab3b48cca",
          "sha256": "5c37c66b2ce2b40dca19f268cd0627a9a42d1413854195918748d1e30fe647c6",
          "sha1": "8505586c559348ee7616b49db8b0340eac713141",
          "md5": "a77702a298cd67c123267d8ff32f67b7"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "admob-sdk-24.3.0.0.aar",
          "url": "admob-sdk-24.3.0.0.aar",
          "size": 132954,
          "sha512": "79eea90b8ade3ad4b97927f38b2291a7ff0506290587b527fe959609e5f02e29aaac8e13231fbfb99c700ea86d01ffdc5b4ad23b87c339a6e95a92bab3b48cca",
          "sha256": "5c37c66b2ce2b40dca19f268cd0627a9a42d1413854195918748d1e30fe647c6",
          "sha1": "8505586c559348ee7616b49db8b0340eac713141",
          "md5": "a77702a298cd67c123267d8ff32f67b7"
        }
      ]
    }
  ]
}
