{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admob.adapter",
    "module": "admob-sdk",
    "version": "24.3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admob-sdk-24.3.0.0.aar",
          "url": "admob-sdk-24.3.0.0.aar",
          "size": 132958,
          "sha512": "058acb69892f42f65fac33e8384635f84912996aaa75b166b7a7cdb28b3b9b55c8062f8fafb772ba2c30f431912a9b4f7ddad6b92daabdeb9ba4e3b449e6f8b9",
          "sha256": "fa499edc19350c5de4f9da32a5704f55100962c18926a8cedd53b628aac5dcb1",
          "sha1": "59ec8f96c3964fc955ac8be1d25ff08bc0d25004",
          "md5": "fc306f701b9c5d5bdf9d226ea6278376"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "admob-sdk-24.3.0.0.aar",
          "url": "admob-sdk-24.3.0.0.aar",
          "size": 132958,
          "sha512": "058acb69892f42f65fac33e8384635f84912996aaa75b166b7a7cdb28b3b9b55c8062f8fafb772ba2c30f431912a9b4f7ddad6b92daabdeb9ba4e3b449e6f8b9",
          "sha256": "fa499edc19350c5de4f9da32a5704f55100962c18926a8cedd53b628aac5dcb1",
          "sha1": "59ec8f96c3964fc955ac8be1d25ff08bc0d25004",
          "md5": "fc306f701b9c5d5bdf9d226ea6278376"
        }
      ]
    }
  ]
}
