{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk",
    "version": "2.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "realReleaseVariantRealReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.7.4.aar",
          "url": "adwhale-mediation-sdk-2.7.4.aar",
          "size": 134443,
          "sha512": "f8061a4302d667b65c930515f04266f57dd63cd28bae97b14043fc7865ecf5b6cde4d55debc5d32d055df23dcf42738e14891d745f418390db5d059651f04004",
          "sha256": "54a8c155802c0573adbf1e5d7407d780529f4313f3ec3381ef950c700e64cbfa",
          "sha1": "e1eb07e4c35f91e6f168be6f90588cd43131f813",
          "md5": "ee978e10a98b40deadedb8d56df00305"
        }
      ]
    },
    {
      "name": "realReleaseVariantRealReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.7.4.aar",
          "url": "adwhale-mediation-sdk-2.7.4.aar",
          "size": 134443,
          "sha512": "f8061a4302d667b65c930515f04266f57dd63cd28bae97b14043fc7865ecf5b6cde4d55debc5d32d055df23dcf42738e14891d745f418390db5d059651f04004",
          "sha256": "54a8c155802c0573adbf1e5d7407d780529f4313f3ec3381ef950c700e64cbfa",
          "sha1": "e1eb07e4c35f91e6f168be6f90588cd43131f813",
          "md5": "ee978e10a98b40deadedb8d56df00305"
        }
      ]
    }
  ]
}
