{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.cauly.adapter",
    "module": "cauly-sdk-uat",
    "version": "3.5.41.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.41.0.aar",
          "url": "cauly-sdk-uat-3.5.41.0.aar",
          "size": 38777,
          "sha512": "a7f88b11dbbe29c6874439cb2b61fafa205298ecd381e4a8980f2426d075d5785068b347e3053f743dced9a7dbcc37374f65f86111c73d6094f387746742717f",
          "sha256": "9d467f287184418a492a9b30120476b88949eaa8432c4eed2cb978b7998b2877",
          "sha1": "cdf890351c1a1e577238e945f82fc4adef92af1a",
          "md5": "84bfa547e5e028dfc1c2a1f5c8139b77"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "com.fsn.cauly",
          "module": "cauly-sdk-uat",
          "version": {
            "requires": "3.5.41"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.41.0.aar",
          "url": "cauly-sdk-uat-3.5.41.0.aar",
          "size": 38777,
          "sha512": "a7f88b11dbbe29c6874439cb2b61fafa205298ecd381e4a8980f2426d075d5785068b347e3053f743dced9a7dbcc37374f65f86111c73d6094f387746742717f",
          "sha256": "9d467f287184418a492a9b30120476b88949eaa8432c4eed2cb978b7998b2877",
          "sha1": "cdf890351c1a1e577238e945f82fc4adef92af1a",
          "md5": "84bfa547e5e028dfc1c2a1f5c8139b77"
        }
      ]
    }
  ]
}
