{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk-uat",
    "version": "2.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.7.3.aar",
          "url": "adwhale-core-sdk-uat-2.7.3.aar",
          "size": 50626,
          "sha512": "78e335a0136909079392c6485a976d6e35c9f56f476bd6c1c7a550f8fdbfb2dfbac22a9110886e60ce2a5f40f50073c87322fe0ef856290914061dee862d809a",
          "sha256": "e879c6292d22c7c82ef705008fbc9e654adfba8d7f6a71408c4b4758b46cb604",
          "sha1": "6eb4483d09df0b68a3456a3bf54bbc7285d5476a",
          "md5": "f07358a131cec002847251d54c28e6e4"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.7.3.aar",
          "url": "adwhale-core-sdk-uat-2.7.3.aar",
          "size": 50626,
          "sha512": "78e335a0136909079392c6485a976d6e35c9f56f476bd6c1c7a550f8fdbfb2dfbac22a9110886e60ce2a5f40f50073c87322fe0ef856290914061dee862d809a",
          "sha256": "e879c6292d22c7c82ef705008fbc9e654adfba8d7f6a71408c4b4758b46cb604",
          "sha1": "6eb4483d09df0b68a3456a3bf54bbc7285d5476a",
          "md5": "f07358a131cec002847251d54c28e6e4"
        }
      ]
    }
  ]
}
