{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk-uat",
    "version": "2.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.7.3.aar",
          "url": "adwhale-core-sdk-uat-2.7.3.aar",
          "size": 50644,
          "sha512": "bc8c7ef54127a64f4a2887ac0582a8f65661c9e7c21dbe4cef068aa3f486d0971379de71f0d13396953ca15ed275b7640260ad901bf9e761ee71f1f1287fe6e9",
          "sha256": "934b4ceb4bd0073ade253a4ab8b7616c67b371e15f0642786de842ce1ed9eec6",
          "sha1": "c93c5394aac36d3c9d698e9e1c06f1969f9ab1fb",
          "md5": "0389bf6d84c2da78b352df53ddc1bbba"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.7.3.aar",
          "url": "adwhale-core-sdk-uat-2.7.3.aar",
          "size": 50644,
          "sha512": "bc8c7ef54127a64f4a2887ac0582a8f65661c9e7c21dbe4cef068aa3f486d0971379de71f0d13396953ca15ed275b7640260ad901bf9e761ee71f1f1287fe6e9",
          "sha256": "934b4ceb4bd0073ade253a4ab8b7616c67b371e15f0642786de842ce1ed9eec6",
          "sha1": "c93c5394aac36d3c9d698e9e1c06f1969f9ab1fb",
          "md5": "0389bf6d84c2da78b352df53ddc1bbba"
        }
      ]
    }
  ]
}
