{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk-uat",
    "version": "2.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.7.3.aar",
          "url": "adwhale-core-sdk-uat-2.7.3.aar",
          "size": 54729,
          "sha512": "444303a075a7c41e28a9b39bb5e15995a906279415d9c9d22b8931b284aee2e6888f49b74f6185791bd17828b73ba27495b82ad01c5809aeb039f2da41838141",
          "sha256": "24139436eac2669f5324f0acef455f6e3fe6632466e9be20af6382fc58867597",
          "sha1": "71cd0018ddec9196127f59a77898d1e3da5bd086",
          "md5": "820bc04228a00f1edd4db42a7582a55c"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-uat-2.7.3.aar",
          "url": "adwhale-core-sdk-uat-2.7.3.aar",
          "size": 54729,
          "sha512": "444303a075a7c41e28a9b39bb5e15995a906279415d9c9d22b8931b284aee2e6888f49b74f6185791bd17828b73ba27495b82ad01c5809aeb039f2da41838141",
          "sha256": "24139436eac2669f5324f0acef455f6e3fe6632466e9be20af6382fc58867597",
          "sha1": "71cd0018ddec9196127f59a77898d1e3da5bd086",
          "md5": "820bc04228a00f1edd4db42a7582a55c"
        }
      ]
    }
  ]
}
