{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.cauly.adapter",
    "module": "cauly-sdk-uat",
    "version": "3.5.40.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.40.1.aar",
          "url": "cauly-sdk-uat-3.5.40.1.aar",
          "size": 22809,
          "sha512": "be73ee30bb0f05da7b2ad813d9346300c400a12cbfa4c4ce6fe382243e47d9970ae5387cba21814a27a946dfa15bbacf00deddd97aa77b2ba2187e3c1f232f7e",
          "sha256": "fa0db1d69ad279f9bb3b60e1c2deb9a5a06068e66b47ed81e175cd36e22a7c7e",
          "sha1": "741fbda0e33b5377fdfeaa67e3c3663625d85504",
          "md5": "e0f0c2ea3ac60568cdc4ffec616b9cfc"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.fsn.cauly",
          "module": "cauly-sdk-uat",
          "version": {
            "requires": "3.5.40"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.40.1.aar",
          "url": "cauly-sdk-uat-3.5.40.1.aar",
          "size": 22809,
          "sha512": "be73ee30bb0f05da7b2ad813d9346300c400a12cbfa4c4ce6fe382243e47d9970ae5387cba21814a27a946dfa15bbacf00deddd97aa77b2ba2187e3c1f232f7e",
          "sha256": "fa0db1d69ad279f9bb3b60e1c2deb9a5a06068e66b47ed81e175cd36e22a7c7e",
          "sha1": "741fbda0e33b5377fdfeaa67e3c3663625d85504",
          "md5": "e0f0c2ea3ac60568cdc4ffec616b9cfc"
        }
      ]
    }
  ]
}
