{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.cauly.adapter",
    "module": "cauly-sdk-uat",
    "version": "3.5.40.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.40.1.aar",
          "url": "cauly-sdk-uat-3.5.40.1.aar",
          "size": 22773,
          "sha512": "968714a1a7a4f0b39fd32ab81a1400d8ed0e4b968995411d64bb6c0f6c4bcc955c0db16ef0bc38b323ca99ed1f40bf31ad07d7d837527f04e68bb4c3affe4e28",
          "sha256": "af7be4cd3fec25c3df3b043cab6532f6cdc4419d4b643910e8c13a5acfcc0c2d",
          "sha1": "e02a0c9cf056fcd9c91f020e213d87cce95f53a8",
          "md5": "fcbb3a0fc9b4555c3e682c72c73ba43d"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.fsn.cauly",
          "module": "cauly-sdk-uat",
          "version": {
            "requires": "3.5.40"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.40.1.aar",
          "url": "cauly-sdk-uat-3.5.40.1.aar",
          "size": 22773,
          "sha512": "968714a1a7a4f0b39fd32ab81a1400d8ed0e4b968995411d64bb6c0f6c4bcc955c0db16ef0bc38b323ca99ed1f40bf31ad07d7d837527f04e68bb4c3affe4e28",
          "sha256": "af7be4cd3fec25c3df3b043cab6532f6cdc4419d4b643910e8c13a5acfcc0c2d",
          "sha1": "e02a0c9cf056fcd9c91f020e213d87cce95f53a8",
          "md5": "fcbb3a0fc9b4555c3e682c72c73ba43d"
        }
      ]
    }
  ]
}
