{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.cauly.adapter",
    "module": "cauly-sdk-uat",
    "version": "3.5.40.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.40.1.aar",
          "url": "cauly-sdk-uat-3.5.40.1.aar",
          "size": 22809,
          "sha512": "d32cd46f7bf115ee3ff09f4ff38e54afb20f24ce196b2b8e664e61ff389266ff277d42bb8152689623dfd59a36b3965e07f6a0125ccded2269d9ad123f7c9da1",
          "sha256": "aa9347be72a2cd679b69d65b4b54721738347bcafd61145dc839df0c751d7d75",
          "sha1": "85d97a36c4781968dcc63861234e7eb927374692",
          "md5": "ede36943bed4091b4602e1e7d74759dd"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.fsn.cauly",
          "module": "cauly-sdk-uat",
          "version": {
            "requires": "3.5.40"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.40.1.aar",
          "url": "cauly-sdk-uat-3.5.40.1.aar",
          "size": 22809,
          "sha512": "d32cd46f7bf115ee3ff09f4ff38e54afb20f24ce196b2b8e664e61ff389266ff277d42bb8152689623dfd59a36b3965e07f6a0125ccded2269d9ad123f7c9da1",
          "sha256": "aa9347be72a2cd679b69d65b4b54721738347bcafd61145dc839df0c751d7d75",
          "sha1": "85d97a36c4781968dcc63861234e7eb927374692",
          "md5": "ede36943bed4091b4602e1e7d74759dd"
        }
      ]
    }
  ]
}
