{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk",
    "version": "3.17.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-3.17.2.2.aar",
          "url": "adfit-sdk-3.17.2.2.aar",
          "size": 7463,
          "sha512": "bc7f07bcdb809400e2dac170f08a8b98c37303a7cc590e89f45172839f317e7c3a138837a87023b332e4e015ba4525bc697ea88c31b4b7e1ae7ca7cbe7baff78",
          "sha256": "3bebb5526f1aaa2b6135c96893eb1711e8cdfaff79d5a334221ae1cf825f32eb",
          "sha1": "1229e283df9ad82594d074a68c786e5a7f4e9b3c",
          "md5": "3d703d6d9d87cdd58b7cbccf5214e706"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-3.17.2.2.aar",
          "url": "adfit-sdk-3.17.2.2.aar",
          "size": 7463,
          "sha512": "bc7f07bcdb809400e2dac170f08a8b98c37303a7cc590e89f45172839f317e7c3a138837a87023b332e4e015ba4525bc697ea88c31b4b7e1ae7ca7cbe7baff78",
          "sha256": "3bebb5526f1aaa2b6135c96893eb1711e8cdfaff79d5a334221ae1cf825f32eb",
          "sha1": "1229e283df9ad82594d074a68c786e5a7f4e9b3c",
          "md5": "3d703d6d9d87cdd58b7cbccf5214e706"
        }
      ]
    }
  ]
}
