{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk-uat",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.6.0.aar",
          "url": "adwhale-mediation-sdk-uat-2.6.0.aar",
          "size": 120870,
          "sha512": "612981a3ee3aefc8f5149fafd7d618e749bf2a7f16a08de978ed19b766f580978c68e94462f004654baebb9762cf28617d1b8accedc96f9a0dba70d5d9f36d4a",
          "sha256": "06d82de2a12680cdc88438427f4f1c5598bc447e3154ec8ae186814ea7cb7cd8",
          "sha1": "bd961319336fcc5161f49c616375ecdc20e92f07",
          "md5": "7c66451846992597fe7e33c529a14f6e"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.6.0.aar",
          "url": "adwhale-mediation-sdk-uat-2.6.0.aar",
          "size": 120870,
          "sha512": "612981a3ee3aefc8f5149fafd7d618e749bf2a7f16a08de978ed19b766f580978c68e94462f004654baebb9762cf28617d1b8accedc96f9a0dba70d5d9f36d4a",
          "sha256": "06d82de2a12680cdc88438427f4f1c5598bc447e3154ec8ae186814ea7cb7cd8",
          "sha1": "bd961319336fcc5161f49c616375ecdc20e92f07",
          "md5": "7c66451846992597fe7e33c529a14f6e"
        }
      ]
    }
  ]
}
