{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk-uat",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.6.0.aar",
          "url": "adwhale-mediation-sdk-uat-2.6.0.aar",
          "size": 120861,
          "sha512": "e0a2dd6cf4f46d968422a248ca24f5fd8506910608b8ca2c4a475a9582d72b154f1ba84e0555fbcbd5047babb884197565e977e07bda7592c6234e2b873acc72",
          "sha256": "460bcbed757416bbdc1b4d6fae12e307bf44c3368f40ff6700783f79e271b7ce",
          "sha1": "beb840c47dda6cdff4dabecda8a852374b686ede",
          "md5": "d949dcf81c365e60b3b96f3e4e803e70"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.6.0.aar",
          "url": "adwhale-mediation-sdk-uat-2.6.0.aar",
          "size": 120861,
          "sha512": "e0a2dd6cf4f46d968422a248ca24f5fd8506910608b8ca2c4a475a9582d72b154f1ba84e0555fbcbd5047babb884197565e977e07bda7592c6234e2b873acc72",
          "sha256": "460bcbed757416bbdc1b4d6fae12e307bf44c3368f40ff6700783f79e271b7ce",
          "sha1": "beb840c47dda6cdff4dabecda8a852374b686ede",
          "md5": "d949dcf81c365e60b3b96f3e4e803e70"
        }
      ]
    }
  ]
}
