{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk-uat",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.6.0.aar",
          "url": "adwhale-mediation-sdk-uat-2.6.0.aar",
          "size": 120706,
          "sha512": "558636cd35d7ce4ed84c564919d75a6b832a6ef34cb3c94958f7856a0e025185c04dd32ecd2a0fe7c8f06b8cb1e9f5d442fa46487dfa3a1d70d8e0a7d0cd7b49",
          "sha256": "fc5fb6a7311ae16e8345da690c6138f850bdfffb55c25528d1682b2219274319",
          "sha1": "285346669050299be3f8a505ee5bf0e8fbc3980a",
          "md5": "50ecc14fd07a3bf22202ee49dde9332f"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.6.0.aar",
          "url": "adwhale-mediation-sdk-uat-2.6.0.aar",
          "size": 120706,
          "sha512": "558636cd35d7ce4ed84c564919d75a6b832a6ef34cb3c94958f7856a0e025185c04dd32ecd2a0fe7c8f06b8cb1e9f5d442fa46487dfa3a1d70d8e0a7d0cd7b49",
          "sha256": "fc5fb6a7311ae16e8345da690c6138f850bdfffb55c25528d1682b2219274319",
          "sha1": "285346669050299be3f8a505ee5bf0e8fbc3980a",
          "md5": "50ecc14fd07a3bf22202ee49dde9332f"
        }
      ]
    }
  ]
}
