{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk-uat",
    "version": "2.5.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.5.8.aar",
          "url": "adwhale-mediation-sdk-uat-2.5.8.aar",
          "size": 114781,
          "sha512": "9ef9002c6f02a6ec316ad2ede9f9f66290aed9d840087cb47c9f96021013eb69c6008bea10e061f50c4d1fd50c9ce088647912a28bfcd002b059f918bde5ab58",
          "sha256": "f430bf27b61ec485fb35ad37c86b8ff99205dd4fcbb5cade0664d04e5351e75a",
          "sha1": "7356db2242ad5e40d04c7b01a5818af61dec5794",
          "md5": "ce125b1dd01e9df9ef53953bbf1b8d49"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.5.8"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.5.8.aar",
          "url": "adwhale-mediation-sdk-uat-2.5.8.aar",
          "size": 114781,
          "sha512": "9ef9002c6f02a6ec316ad2ede9f9f66290aed9d840087cb47c9f96021013eb69c6008bea10e061f50c4d1fd50c9ce088647912a28bfcd002b059f918bde5ab58",
          "sha256": "f430bf27b61ec485fb35ad37c86b8ff99205dd4fcbb5cade0664d04e5351e75a",
          "sha1": "7356db2242ad5e40d04c7b01a5818af61dec5794",
          "md5": "ce125b1dd01e9df9ef53953bbf1b8d49"
        }
      ]
    }
  ]
}
