{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admize.adapter",
    "module": "admize-sdk-uat",
    "version": "1.0.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-uat-1.0.5.2.aar",
          "url": "admize-sdk-uat-1.0.5.2.aar",
          "size": 25812,
          "sha512": "a6494c0061d7c486c401527e8ffe22895992a144f71d1e54349b665f07a42850d9234077cef30b2c3eb62d9982ebddd74152fbcd5765dc38bad16e2810a77cac",
          "sha256": "462bb9b26facad65299b8fd3c553beae02ec45589a19a64991c37478ea3c48ba",
          "sha1": "b385e107b75247bd645de539a10d3991e5246128",
          "md5": "2607d078e80cc19c96e14ef0e39c067b"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "io.admize.sdk.android",
          "module": "admize-sdk-android-uat",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-uat-1.0.5.2.aar",
          "url": "admize-sdk-uat-1.0.5.2.aar",
          "size": 25812,
          "sha512": "a6494c0061d7c486c401527e8ffe22895992a144f71d1e54349b665f07a42850d9234077cef30b2c3eb62d9982ebddd74152fbcd5765dc38bad16e2810a77cac",
          "sha256": "462bb9b26facad65299b8fd3c553beae02ec45589a19a64991c37478ea3c48ba",
          "sha1": "b385e107b75247bd645de539a10d3991e5246128",
          "md5": "2607d078e80cc19c96e14ef0e39c067b"
        }
      ]
    }
  ]
}
