{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admize.adapter",
    "module": "admize-sdk-uat",
    "version": "1.0.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-uat-1.0.5.2.aar",
          "url": "admize-sdk-uat-1.0.5.2.aar",
          "size": 25812,
          "sha512": "60d99a163c61dd6f3a42f83ce119675308d453c6ac13311fca0122e0a64d3caa210872ec614d6eaed35c6ea7dccdb5d3b5c7c10b91b83c31a4287f9132f74a5a",
          "sha256": "61f030a5380cbbd03b94177dd21a6f5135dd6d4d8bf7d3de55b20d42d1d15594",
          "sha1": "350fe301edd6f8e26a2b1d1bdd591503a0c119f5",
          "md5": "04fe5d430abfd748d442392f8421665e"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "io.admize.sdk.android",
          "module": "admize-sdk-android-uat",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-uat-1.0.5.2.aar",
          "url": "admize-sdk-uat-1.0.5.2.aar",
          "size": 25812,
          "sha512": "60d99a163c61dd6f3a42f83ce119675308d453c6ac13311fca0122e0a64d3caa210872ec614d6eaed35c6ea7dccdb5d3b5c7c10b91b83c31a4287f9132f74a5a",
          "sha256": "61f030a5380cbbd03b94177dd21a6f5135dd6d4d8bf7d3de55b20d42d1d15594",
          "sha1": "350fe301edd6f8e26a2b1d1bdd591503a0c119f5",
          "md5": "04fe5d430abfd748d442392f8421665e"
        }
      ]
    }
  ]
}
