{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admize.adapter",
    "module": "admize-sdk",
    "version": "1.0.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-1.0.6.2.aar",
          "url": "admize-sdk-1.0.6.2.aar",
          "size": 23345,
          "sha512": "a66a6f8b66ef8ac6f49f087ab1ac6c8cf58d33f14327b4db58c82cfef8cc36f37aecd9370e498a7ae9457698734bed7e2bf6226a26660ada6b59e96c4623e28a",
          "sha256": "035024c167f6efffd2ec17ced03e3e272facefe5e865bdd3a6957a1d0c7d1f78",
          "sha1": "cf690387dda2909ae36135cb91cb396c75f58681",
          "md5": "0936e2b26e2ac8a855fd7ec7a4c64b55"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "io.admize.sdk.android",
          "module": "admize-sdk-android",
          "version": {
            "requires": "1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-1.0.6.2.aar",
          "url": "admize-sdk-1.0.6.2.aar",
          "size": 23345,
          "sha512": "a66a6f8b66ef8ac6f49f087ab1ac6c8cf58d33f14327b4db58c82cfef8cc36f37aecd9370e498a7ae9457698734bed7e2bf6226a26660ada6b59e96c4623e28a",
          "sha256": "035024c167f6efffd2ec17ced03e3e272facefe5e865bdd3a6957a1d0c7d1f78",
          "sha1": "cf690387dda2909ae36135cb91cb396c75f58681",
          "md5": "0936e2b26e2ac8a855fd7ec7a4c64b55"
        }
      ]
    }
  ]
}
