{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admize.adapter",
    "module": "admize-sdk-uat",
    "version": "1.0.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-uat-1.0.7.2.aar",
          "url": "admize-sdk-uat-1.0.7.2.aar",
          "size": 35394,
          "sha512": "f03943a331112cbf699c590ebcd80aa32d9722b9dcee22d8fa20945cc13f3c0314aa9b61d3f3b85938dfd620dfebd7a539f97abbf7e81a4695f4397a462a1692",
          "sha256": "4280096b7c77f98baebff5261f4a2bd8ce57c6fe67fe5fa1739879e50942727c",
          "sha1": "bdd36b61d117f64036b1709c3d158e41eea41cd0",
          "md5": "d54605159ddf5d963f36245337747f1b"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "io.admize.sdk.android",
          "module": "admize-sdk-android-uat",
          "version": {
            "requires": "1.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-uat-1.0.7.2.aar",
          "url": "admize-sdk-uat-1.0.7.2.aar",
          "size": 35394,
          "sha512": "f03943a331112cbf699c590ebcd80aa32d9722b9dcee22d8fa20945cc13f3c0314aa9b61d3f3b85938dfd620dfebd7a539f97abbf7e81a4695f4397a462a1692",
          "sha256": "4280096b7c77f98baebff5261f4a2bd8ce57c6fe67fe5fa1739879e50942727c",
          "sha1": "bdd36b61d117f64036b1709c3d158e41eea41cd0",
          "md5": "d54605159ddf5d963f36245337747f1b"
        }
      ]
    }
  ]
}
