{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admize.adapter",
    "module": "admize-sdk-uat",
    "version": "1.0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-uat-1.0.8.1.aar",
          "url": "admize-sdk-uat-1.0.8.1.aar",
          "size": 35917,
          "sha512": "f7ce4a9a7e74f01b838a1cb21c03be5ff086fd0a988dd93ee69e429ac2fda5affedd0c87e5aeed3bb34577fd61c664ec2d08ed5b6f1b2ce55f1950cc685fe56c",
          "sha256": "b230a2b00cc82fafe742bf576e96a4baff00ccf64e307386058e1ce6ccd8bc3c",
          "sha1": "1fcd8b304d833a65d55a948db1a22d6bee488579",
          "md5": "2d112921602d48ba7f573eefbcbc3b12"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "io.admize.sdk.android",
          "module": "admize-sdk-android-uat",
          "version": {
            "requires": "1.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-uat-1.0.8.1.aar",
          "url": "admize-sdk-uat-1.0.8.1.aar",
          "size": 35917,
          "sha512": "f7ce4a9a7e74f01b838a1cb21c03be5ff086fd0a988dd93ee69e429ac2fda5affedd0c87e5aeed3bb34577fd61c664ec2d08ed5b6f1b2ce55f1950cc685fe56c",
          "sha256": "b230a2b00cc82fafe742bf576e96a4baff00ccf64e307386058e1ce6ccd8bc3c",
          "sha1": "1fcd8b304d833a65d55a948db1a22d6bee488579",
          "md5": "2d112921602d48ba7f573eefbcbc3b12"
        }
      ]
    }
  ]
}
