{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk",
    "version": "2.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-2.6.1.aar",
          "url": "adwhale-core-sdk-2.6.1.aar",
          "size": 35103,
          "sha512": "0abae15c46442a9a814952f4f40d1b83e4ae466d165c0b5c4f9c259186ab9aab5b17211cc0638e37fda6287f1d6fb2dbaa4ff3f3f12304b49461e1fb1fda0312",
          "sha256": "4a26cf3f1e53f1befbc45e818479b7a0267a04e990d57ea9df43c0e4a3488995",
          "sha1": "0ff58ba0375989eee733f8fffc71f8535924bb94",
          "md5": "f1447f67b470fb0775d211821601a6a9"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-2.6.1.aar",
          "url": "adwhale-core-sdk-2.6.1.aar",
          "size": 35103,
          "sha512": "0abae15c46442a9a814952f4f40d1b83e4ae466d165c0b5c4f9c259186ab9aab5b17211cc0638e37fda6287f1d6fb2dbaa4ff3f3f12304b49461e1fb1fda0312",
          "sha256": "4a26cf3f1e53f1befbc45e818479b7a0267a04e990d57ea9df43c0e4a3488995",
          "sha1": "0ff58ba0375989eee733f8fffc71f8535924bb94",
          "md5": "f1447f67b470fb0775d211821601a6a9"
        }
      ]
    }
  ]
}
