{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.cauly.adapter",
    "module": "cauly-sdk-uat",
    "version": "3.5.39.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.39.2.aar",
          "url": "cauly-sdk-uat-3.5.39.2.aar",
          "size": 22718,
          "sha512": "bfa038934ba670827ab759e72b42b27f60ea07feaf24b0f1c4d1e12d5fc10320247f52936b061be300bdccd4207a5e96ad7190ca917fa4c049dda07fd95ca215",
          "sha256": "513c9e77b542fea325f6dc24731c8bac0d1e4f966f3dacae99b395cd2e078e77",
          "sha1": "869e58e710b33d6b874c5600e6300f74e3a82511",
          "md5": "65f81b4e81640e8f6340e6b58a3fca23"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.fsn.cauly",
          "module": "cauly-sdk-uat",
          "version": {
            "requires": "3.5.39"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.39.2.aar",
          "url": "cauly-sdk-uat-3.5.39.2.aar",
          "size": 22718,
          "sha512": "bfa038934ba670827ab759e72b42b27f60ea07feaf24b0f1c4d1e12d5fc10320247f52936b061be300bdccd4207a5e96ad7190ca917fa4c049dda07fd95ca215",
          "sha256": "513c9e77b542fea325f6dc24731c8bac0d1e4f966f3dacae99b395cd2e078e77",
          "sha1": "869e58e710b33d6b874c5600e6300f74e3a82511",
          "md5": "65f81b4e81640e8f6340e6b58a3fca23"
        }
      ]
    }
  ]
}
