{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admob.adapter",
    "module": "admob-sdk-uat",
    "version": "23.6.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admob-sdk-uat-23.6.0.3.aar",
          "url": "admob-sdk-uat-23.6.0.3.aar",
          "size": 83277,
          "sha512": "9168af2e70821b49f053dd294d9f5dc7844ba7083b09fca1884458c6056fc2cd016e4fe54157480bf653d31ea4ef5b760ab1a3a65bd68b184305eda2cf4b9caf",
          "sha256": "77c0741497bc1e6edb91612b050b0bda5f5d5efabaec93e013daad4adb5d1d28",
          "sha1": "0d19eaa41fe4e3da193b92e4ed05a0c0c1e5dad2",
          "md5": "c85ee9b015b52bab80d35fbbee913444"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "admob-sdk-uat-23.6.0.3.aar",
          "url": "admob-sdk-uat-23.6.0.3.aar",
          "size": 83277,
          "sha512": "9168af2e70821b49f053dd294d9f5dc7844ba7083b09fca1884458c6056fc2cd016e4fe54157480bf653d31ea4ef5b760ab1a3a65bd68b184305eda2cf4b9caf",
          "sha256": "77c0741497bc1e6edb91612b050b0bda5f5d5efabaec93e013daad4adb5d1d28",
          "sha1": "0d19eaa41fe4e3da193b92e4ed05a0c0c1e5dad2",
          "md5": "c85ee9b015b52bab80d35fbbee913444"
        }
      ]
    }
  ]
}
