{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admob.adapter",
    "module": "admob-sdk-uat",
    "version": "23.6.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admob-sdk-uat-23.6.0.3.aar",
          "url": "admob-sdk-uat-23.6.0.3.aar",
          "size": 83266,
          "sha512": "5a2940fc89898a601813914ea21873a6d5cafd147bcbad41a6c5cb0d3d96b5b5eb9126b04d83a39becf374bf391023d69ca96664f839112e867e3f63e1ce895d",
          "sha256": "486c2ebfb77db2dce5eedc00c69ad50639f491e02ac15d121797d0a1006151fb",
          "sha1": "4b05ac9e28d5d6591eccf51261ad8a1cd043535b",
          "md5": "1e14b9c4c3858733c84f3ac715006015"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "admob-sdk-uat-23.6.0.3.aar",
          "url": "admob-sdk-uat-23.6.0.3.aar",
          "size": 83266,
          "sha512": "5a2940fc89898a601813914ea21873a6d5cafd147bcbad41a6c5cb0d3d96b5b5eb9126b04d83a39becf374bf391023d69ca96664f839112e867e3f63e1ce895d",
          "sha256": "486c2ebfb77db2dce5eedc00c69ad50639f491e02ac15d121797d0a1006151fb",
          "sha1": "4b05ac9e28d5d6591eccf51261ad8a1cd043535b",
          "md5": "1e14b9c4c3858733c84f3ac715006015"
        }
      ]
    }
  ]
}
