{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk-uat",
    "version": "2.5.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.5.10.aar",
          "url": "adwhale-mediation-sdk-uat-2.5.10.aar",
          "size": 114659,
          "sha512": "3e7c864dadd96164e995adfa25268bc91f1ac05c6520ba64c118ee876efc6cb11abdd85f17ff35de27411f0ab6ec8931b9c310a9abe2216ce5ec8bdee33fcb09",
          "sha256": "c666c5a8fff17d5c5c168e640e9de5d7d01a2aa673e2ae9195f09a17113180fe",
          "sha1": "f20aa33171872b4ba66723afafac1baa6f53c534",
          "md5": "2c83bb7f5f0750cdcaaa346926a66827"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.5.10.aar",
          "url": "adwhale-mediation-sdk-uat-2.5.10.aar",
          "size": 114659,
          "sha512": "3e7c864dadd96164e995adfa25268bc91f1ac05c6520ba64c118ee876efc6cb11abdd85f17ff35de27411f0ab6ec8931b9c310a9abe2216ce5ec8bdee33fcb09",
          "sha256": "c666c5a8fff17d5c5c168e640e9de5d7d01a2aa673e2ae9195f09a17113180fe",
          "sha1": "f20aa33171872b4ba66723afafac1baa6f53c534",
          "md5": "2c83bb7f5f0750cdcaaa346926a66827"
        }
      ]
    }
  ]
}
