{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk-uat",
    "version": "2.5.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.5.10.aar",
          "url": "adwhale-mediation-sdk-uat-2.5.10.aar",
          "size": 115933,
          "sha512": "0e7dc2addff9193109923acc34d265fe1d8992a38404ce325af1dc49d027fca7a02b1c42e777a38cb5c59b258b5cf7e0d3daca8705c10562277bc96af7c6768c",
          "sha256": "b2c1175449aaa11d46d6f4b51fffb40cfc3e16e675d21a65018679381e344a23",
          "sha1": "2ce329b9fd89024fce8b799d060ca864ad990aa0",
          "md5": "2f9e5a107bd87f43d4fa7f745795920d"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.5.10.aar",
          "url": "adwhale-mediation-sdk-uat-2.5.10.aar",
          "size": 115933,
          "sha512": "0e7dc2addff9193109923acc34d265fe1d8992a38404ce325af1dc49d027fca7a02b1c42e777a38cb5c59b258b5cf7e0d3daca8705c10562277bc96af7c6768c",
          "sha256": "b2c1175449aaa11d46d6f4b51fffb40cfc3e16e675d21a65018679381e344a23",
          "sha1": "2ce329b9fd89024fce8b799d060ca864ad990aa0",
          "md5": "2f9e5a107bd87f43d4fa7f745795920d"
        }
      ]
    }
  ]
}
