{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk",
    "version": "2.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-2.7.1.aar",
          "url": "adwhale-core-sdk-2.7.1.aar",
          "size": 41077,
          "sha512": "1fafb137bf5e8e9630896d9e029e4508f2bbfb29d8707f30774b439c5465ddd0e2120c1ed3bc500d5fb2b48b5768966ea049e04fc115c41836170a43bc4bd407",
          "sha256": "07be812e3a32881470404ac406c76eb20a6bf26163fe0fe97cfad6bdec189189",
          "sha1": "e0aa6f42050766c0819a5f0861aaa65b27f9d004",
          "md5": "2102b4481fe00df5663ef7cbbeebde55"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-2.7.1.aar",
          "url": "adwhale-core-sdk-2.7.1.aar",
          "size": 41077,
          "sha512": "1fafb137bf5e8e9630896d9e029e4508f2bbfb29d8707f30774b439c5465ddd0e2120c1ed3bc500d5fb2b48b5768966ea049e04fc115c41836170a43bc4bd407",
          "sha256": "07be812e3a32881470404ac406c76eb20a6bf26163fe0fe97cfad6bdec189189",
          "sha1": "e0aa6f42050766c0819a5f0861aaa65b27f9d004",
          "md5": "2102b4481fe00df5663ef7cbbeebde55"
        }
      ]
    }
  ]
}
