{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk",
    "version": "2.7.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "realReleaseVariantRealReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.7.7.aar",
          "url": "adwhale-mediation-sdk-2.7.7.aar",
          "size": 163578,
          "sha512": "13324e068e24e2b6407ca123b68b0303380385640827371687a8cc8b7983373f0d08245b54fd7cba9543d2b598f5129e9e28a592a39b8e0d85a48839add04cab",
          "sha256": "0e3a3b0b72cde7995b98c884177d04f17b1b3067ce6a372c248ffd761098123f",
          "sha1": "735d8b2fc290965dac29bc48fbc3f6c7d48bde69",
          "md5": "3d837e0f95146e956cd926110621cb11"
        }
      ]
    },
    {
      "name": "realReleaseVariantRealReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.7.7.aar",
          "url": "adwhale-mediation-sdk-2.7.7.aar",
          "size": 163578,
          "sha512": "13324e068e24e2b6407ca123b68b0303380385640827371687a8cc8b7983373f0d08245b54fd7cba9543d2b598f5129e9e28a592a39b8e0d85a48839add04cab",
          "sha256": "0e3a3b0b72cde7995b98c884177d04f17b1b3067ce6a372c248ffd761098123f",
          "sha1": "735d8b2fc290965dac29bc48fbc3f6c7d48bde69",
          "md5": "3d837e0f95146e956cd926110621cb11"
        }
      ]
    }
  ]
}
