{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk",
    "version": "8.7.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-8.7.0.3.aar",
          "url": "levelplay-sdk-8.7.0.3.aar",
          "size": 22379,
          "sha512": "8da14aafc48e3d3ca37f320c601242241d8514a681c567eab2b427fadfe3735ecfd257d021c2bf8eae9f73977986e149d85bd6d22f6002e0804afad97e0bc1b1",
          "sha256": "243ac283f4c49af3891970e046acf1f0bfee553b966fe32f4ba6cc857f22659d",
          "sha1": "96be949455e86f366f1fe80f4f02d4d24e6ab220",
          "md5": "49c5960b5cdbcdd34e99f458e4734b11"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-8.7.0.3.aar",
          "url": "levelplay-sdk-8.7.0.3.aar",
          "size": 22379,
          "sha512": "8da14aafc48e3d3ca37f320c601242241d8514a681c567eab2b427fadfe3735ecfd257d021c2bf8eae9f73977986e149d85bd6d22f6002e0804afad97e0bc1b1",
          "sha256": "243ac283f4c49af3891970e046acf1f0bfee553b966fe32f4ba6cc857f22659d",
          "sha1": "96be949455e86f366f1fe80f4f02d4d24e6ab220",
          "md5": "49c5960b5cdbcdd34e99f458e4734b11"
        }
      ]
    }
  ]
}
