{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.cauly.adapter",
    "module": "cauly-sdk-uat",
    "version": "3.5.46.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.46.1.aar",
          "url": "cauly-sdk-uat-3.5.46.1.aar",
          "size": 45578,
          "sha512": "ef9742f8f8b523c6b21aee98f942800c40da735fc18fab547d1adf43e8f37eb54caa095fe70e6f3ce8fcd897c8eccba96c21a902d950a834c3b85428b06ac485",
          "sha256": "38b167ff28fd1364551e5a018b09128b1905d54b7cd3fc48b2f3ab48373b64b7",
          "sha1": "7efe31372ed3f64d916c9749d21ae6b909ad5fcf",
          "md5": "e75275831f17eef1a6997ac9a3366b61"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.fsn.cauly",
          "module": "cauly-sdk-uat",
          "version": {
            "requires": "3.5.46"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.8.9"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.46.1.aar",
          "url": "cauly-sdk-uat-3.5.46.1.aar",
          "size": 45578,
          "sha512": "ef9742f8f8b523c6b21aee98f942800c40da735fc18fab547d1adf43e8f37eb54caa095fe70e6f3ce8fcd897c8eccba96c21a902d950a834c3b85428b06ac485",
          "sha256": "38b167ff28fd1364551e5a018b09128b1905d54b7cd3fc48b2f3ab48373b64b7",
          "sha1": "7efe31372ed3f64d916c9749d21ae6b909ad5fcf",
          "md5": "e75275831f17eef1a6997ac9a3366b61"
        }
      ]
    }
  ]
}
