{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk-uat",
    "version": "2.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.4.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.4.aar",
          "size": 174874,
          "sha512": "0bcf42b760d23b5da3fdc75d44814a269a8bba92acea669fd9d0b3557629335b6040b6bda29c520ca0dfadb44465cb3a549023497ed312ee11a01247d0858f09",
          "sha256": "7512dd5a5b841d6950b3692c1f1b446fe31bd7026b06dc536144729aef359abf",
          "sha1": "69c57c237ee0010883a1d6b6f21134c7a9a9b30e",
          "md5": "2df66f746a700c058f95b83d5a2deb2c"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.4.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.4.aar",
          "size": 174874,
          "sha512": "0bcf42b760d23b5da3fdc75d44814a269a8bba92acea669fd9d0b3557629335b6040b6bda29c520ca0dfadb44465cb3a549023497ed312ee11a01247d0858f09",
          "sha256": "7512dd5a5b841d6950b3692c1f1b446fe31bd7026b06dc536144729aef359abf",
          "sha1": "69c57c237ee0010883a1d6b6f21134c7a9a9b30e",
          "md5": "2df66f746a700c058f95b83d5a2deb2c"
        }
      ]
    }
  ]
}
