{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admob.adapter",
    "module": "admob-sdk",
    "version": "23.6.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admob-sdk-23.6.0.3.aar",
          "url": "admob-sdk-23.6.0.3.aar",
          "size": 56022,
          "sha512": "6499b401f90fab44a3902018281ace91e3cec605f4bfd3d55322674fc2e630904393ccbec30b3367c043ad54ad78b88723b25b1b88fde2d636b442d6fb6a2b14",
          "sha256": "455199a9439f0a3e1f377da569ea23e7f9b0d5ff705773b282ac06de7d77dccc",
          "sha1": "fa9502e41cd90934849621d6ddcea80335939597",
          "md5": "6bff49aa81a645a141fcddf275e9824a"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "admob-sdk-23.6.0.3.aar",
          "url": "admob-sdk-23.6.0.3.aar",
          "size": 56022,
          "sha512": "6499b401f90fab44a3902018281ace91e3cec605f4bfd3d55322674fc2e630904393ccbec30b3367c043ad54ad78b88723b25b1b88fde2d636b442d6fb6a2b14",
          "sha256": "455199a9439f0a3e1f377da569ea23e7f9b0d5ff705773b282ac06de7d77dccc",
          "sha1": "fa9502e41cd90934849621d6ddcea80335939597",
          "md5": "6bff49aa81a645a141fcddf275e9824a"
        }
      ]
    }
  ]
}
