{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk",
    "version": "2.5.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.5.10.aar",
          "url": "adwhale-mediation-sdk-2.5.10.aar",
          "size": 85426,
          "sha512": "b1806436c9e23e3eb0eb0c28a7ab53fc0d8e7a676a4c9f097c9ae314ac40503108211baa657e7b6df45da20ebd4504b9999b349c1ee54da130f8c361315ce5fb",
          "sha256": "4afcd9c176256ecee4451ba44c3afa32c0de9f6044376d4e683ebd6e4b28e601",
          "sha1": "a6ec09f09bd7d4396f94ba040c4501d06572afed",
          "md5": "f1035ba8b52afcc55a7711f15deda0e2"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.5.10.aar",
          "url": "adwhale-mediation-sdk-2.5.10.aar",
          "size": 85426,
          "sha512": "b1806436c9e23e3eb0eb0c28a7ab53fc0d8e7a676a4c9f097c9ae314ac40503108211baa657e7b6df45da20ebd4504b9999b349c1ee54da130f8c361315ce5fb",
          "sha256": "4afcd9c176256ecee4451ba44c3afa32c0de9f6044376d4e683ebd6e4b28e601",
          "sha1": "a6ec09f09bd7d4396f94ba040c4501d06572afed",
          "md5": "f1035ba8b52afcc55a7711f15deda0e2"
        }
      ]
    }
  ]
}
