{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk",
    "version": "2.5.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.5.10.aar",
          "url": "adwhale-mediation-sdk-2.5.10.aar",
          "size": 84798,
          "sha512": "2b169c86982250f0b3c975f3599c63f51e13cb0fa8229ed3c2d8e3448b86de7a35d1d7a609a788edafde0a560f06cc68d1586a6f813a02124bd31abdc3263cf8",
          "sha256": "998d2d0706023268cdae82538f927613d431d810d71ae87137e5ef8d09ee4def",
          "sha1": "973b34ec9c678dbd76b3ca7e95f35d2bbc1be1c2",
          "md5": "f955ae438578223ca35168fa6fe26f5c"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.5.10.aar",
          "url": "adwhale-mediation-sdk-2.5.10.aar",
          "size": 84798,
          "sha512": "2b169c86982250f0b3c975f3599c63f51e13cb0fa8229ed3c2d8e3448b86de7a35d1d7a609a788edafde0a560f06cc68d1586a6f813a02124bd31abdc3263cf8",
          "sha256": "998d2d0706023268cdae82538f927613d431d810d71ae87137e5ef8d09ee4def",
          "sha1": "973b34ec9c678dbd76b3ca7e95f35d2bbc1be1c2",
          "md5": "f955ae438578223ca35168fa6fe26f5c"
        }
      ]
    }
  ]
}
