{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admize.adapter",
    "module": "admize-sdk-uat",
    "version": "1.0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-uat-1.0.6.1.aar",
          "url": "admize-sdk-uat-1.0.6.1.aar",
          "size": 27401,
          "sha512": "13dc3bf44e9ea24f91dc573715c9dfa0b4ff9ce8738419dd09095f9ef62d3ff062077c859d8475ab002e497b7c020508793b93c7fb1c4ac8fda3f3dee041faab",
          "sha256": "ca6bca1228c4dfd69c297e62b09ace8ba641d01b0c684f56b14778417d139da8",
          "sha1": "490a80d62acb8e55aa7d35f4b7bec8a55db021bd",
          "md5": "c77c24247ff24cb51eb110439383a264"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "io.admize.sdk.android",
          "module": "admize-sdk-android-uat",
          "version": {
            "requires": "1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-uat-1.0.6.1.aar",
          "url": "admize-sdk-uat-1.0.6.1.aar",
          "size": 27401,
          "sha512": "13dc3bf44e9ea24f91dc573715c9dfa0b4ff9ce8738419dd09095f9ef62d3ff062077c859d8475ab002e497b7c020508793b93c7fb1c4ac8fda3f3dee041faab",
          "sha256": "ca6bca1228c4dfd69c297e62b09ace8ba641d01b0c684f56b14778417d139da8",
          "sha1": "490a80d62acb8e55aa7d35f4b7bec8a55db021bd",
          "md5": "c77c24247ff24cb51eb110439383a264"
        }
      ]
    }
  ]
}
