{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admize.adapter",
    "module": "admize-sdk-uat",
    "version": "1.0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-uat-1.0.6.1.aar",
          "url": "admize-sdk-uat-1.0.6.1.aar",
          "size": 27434,
          "sha512": "2d6fbdb9b7f40d2b5fd845d935969bc1c830620e2075f49d8ead2e361d5e75317a9b6a02c85893799e408de2662ac999beb7c7e636d8014a01669fc3fb574f29",
          "sha256": "043d62fe2d94fe947ab4512f830ee699ef27f8715fb490518f4f5697304ff7fe",
          "sha1": "29facbc07b66e2053cb95796be8b6121b6aef744",
          "md5": "5d0e67a60bac66f520a202e05029e69d"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "io.admize.sdk.android",
          "module": "admize-sdk-android-uat",
          "version": {
            "requires": "1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-uat-1.0.6.1.aar",
          "url": "admize-sdk-uat-1.0.6.1.aar",
          "size": 27434,
          "sha512": "2d6fbdb9b7f40d2b5fd845d935969bc1c830620e2075f49d8ead2e361d5e75317a9b6a02c85893799e408de2662ac999beb7c7e636d8014a01669fc3fb574f29",
          "sha256": "043d62fe2d94fe947ab4512f830ee699ef27f8715fb490518f4f5697304ff7fe",
          "sha1": "29facbc07b66e2053cb95796be8b6121b6aef744",
          "md5": "5d0e67a60bac66f520a202e05029e69d"
        }
      ]
    }
  ]
}
