{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admob.adapter",
    "module": "admob-sdk",
    "version": "24.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "realReleaseVariantRealReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admob-sdk-24.3.0.3.aar",
          "url": "admob-sdk-24.3.0.3.aar",
          "size": 152953,
          "sha512": "3f71ba9967e5f78e44e9d4c0270cba19b0ce9c11e74464ad203b4acc5e78e55346a8271ea212c81660cffdc4f88704d23b3235209eb78c0f0ed8a3884b40ee44",
          "sha256": "b755ba21e71c5b7635b7929df26d843bd3d1149a532e7151e80762689f822197",
          "sha1": "913d4fb9c4af4fc1c6b54a9c1aee16a9722aa7bc",
          "md5": "5a9d0e4f4c0bd329b9547dd7c42536b7"
        }
      ]
    },
    {
      "name": "realReleaseVariantRealReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "admob-sdk-24.3.0.3.aar",
          "url": "admob-sdk-24.3.0.3.aar",
          "size": 152953,
          "sha512": "3f71ba9967e5f78e44e9d4c0270cba19b0ce9c11e74464ad203b4acc5e78e55346a8271ea212c81660cffdc4f88704d23b3235209eb78c0f0ed8a3884b40ee44",
          "sha256": "b755ba21e71c5b7635b7929df26d843bd3d1149a532e7151e80762689f822197",
          "sha1": "913d4fb9c4af4fc1c6b54a9c1aee16a9722aa7bc",
          "md5": "5a9d0e4f4c0bd329b9547dd7c42536b7"
        }
      ]
    }
  ]
}
