{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.cauly.adapter",
    "module": "cauly-sdk-uat",
    "version": "3.5.40.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.40.2.aar",
          "url": "cauly-sdk-uat-3.5.40.2.aar",
          "size": 38661,
          "sha512": "54af46174d188d96cb3019cb87be7682a8ba881782f9da032a83b865e2880a8cd80e9309c5d37e1e108601aa1a716e749c2c6b69c1caab0d6e76d96c073c3681",
          "sha256": "3d848c765a5302a2bade27c027f28bf184af1f4df58a40daf0a688fb50d96657",
          "sha1": "bf63a36d1b61c63aace116d77740701f4b727afe",
          "md5": "6adc359a2cd3182699f2cdaf63e9ab90"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.fsn.cauly",
          "module": "cauly-sdk-uat",
          "version": {
            "requires": "3.5.40"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.40.2.aar",
          "url": "cauly-sdk-uat-3.5.40.2.aar",
          "size": 38661,
          "sha512": "54af46174d188d96cb3019cb87be7682a8ba881782f9da032a83b865e2880a8cd80e9309c5d37e1e108601aa1a716e749c2c6b69c1caab0d6e76d96c073c3681",
          "sha256": "3d848c765a5302a2bade27c027f28bf184af1f4df58a40daf0a688fb50d96657",
          "sha1": "bf63a36d1b61c63aace116d77740701f4b727afe",
          "md5": "6adc359a2cd3182699f2cdaf63e9ab90"
        }
      ]
    }
  ]
}
