{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.cauly.adapter",
    "module": "cauly-sdk-uat",
    "version": "3.5.40.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.40.2.aar",
          "url": "cauly-sdk-uat-3.5.40.2.aar",
          "size": 38668,
          "sha512": "0b497177ca52d4036c4647d8abdc80d3fa89f9add4806882f2a300fcf797a99697e1231db43e0a4391680f401e2c1db6e2e2ecfcdb01d55943bb22e9acede9fd",
          "sha256": "906c4cc19f4ca5d6448e40dffb7c12f833d4465652cf048bcf0a501f7109481e",
          "sha1": "6ccda46dee1b2efdbdf7f084fa91a5c713126dc3",
          "md5": "7379659588317e11166e1caaebfb84d4"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.fsn.cauly",
          "module": "cauly-sdk-uat",
          "version": {
            "requires": "3.5.40"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.40.2.aar",
          "url": "cauly-sdk-uat-3.5.40.2.aar",
          "size": 38668,
          "sha512": "0b497177ca52d4036c4647d8abdc80d3fa89f9add4806882f2a300fcf797a99697e1231db43e0a4391680f401e2c1db6e2e2ecfcdb01d55943bb22e9acede9fd",
          "sha256": "906c4cc19f4ca5d6448e40dffb7c12f833d4465652cf048bcf0a501f7109481e",
          "sha1": "6ccda46dee1b2efdbdf7f084fa91a5c713126dc3",
          "md5": "7379659588317e11166e1caaebfb84d4"
        }
      ]
    }
  ]
}
