{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.cauly.adapter",
    "module": "cauly-sdk-uat",
    "version": "3.5.40.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.40.2.aar",
          "url": "cauly-sdk-uat-3.5.40.2.aar",
          "size": 38633,
          "sha512": "dc5b433781b960ccea9558e63eb526e9e1f4dbd6cbdaef696777d3f56629b3b737d554a5418ab043b4854f95c10c065707c2619e6baf4cb9671c140198944f29",
          "sha256": "6d34bae4bdafaf9f99cbbd1776e7c0ef813b072a132e97e98d7292595a3bcb0a",
          "sha1": "20441c51780ba895f84b21c9761efb485fde9aeb",
          "md5": "b4342c86454b9d3a62b0362595871457"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.fsn.cauly",
          "module": "cauly-sdk-uat",
          "version": {
            "requires": "3.5.40"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.40.2.aar",
          "url": "cauly-sdk-uat-3.5.40.2.aar",
          "size": 38633,
          "sha512": "dc5b433781b960ccea9558e63eb526e9e1f4dbd6cbdaef696777d3f56629b3b737d554a5418ab043b4854f95c10c065707c2619e6baf4cb9671c140198944f29",
          "sha256": "6d34bae4bdafaf9f99cbbd1776e7c0ef813b072a132e97e98d7292595a3bcb0a",
          "sha1": "20441c51780ba895f84b21c9761efb485fde9aeb",
          "md5": "b4342c86454b9d3a62b0362595871457"
        }
      ]
    }
  ]
}
