{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk",
    "version": "3.17.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-3.17.2.5.aar",
          "url": "adfit-sdk-3.17.2.5.aar",
          "size": 13837,
          "sha512": "d05ff77b07567538ab18a896dd6b0274d7a0b5ac0bf19ec6121080347861b0c31fe828a959fdaf8039af352fec79c4df2666f6ee1fdf08ae257d1500fda41c6d",
          "sha256": "61ec0634f34aa9231c350e4a59e2a323f3a493e180a03825c62c9b8b3e8fb613",
          "sha1": "fe60df0fe00079233f4fcfad601e33b342ce8196",
          "md5": "cfbd8180ba2c8ae9eac9d85576008089"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-3.17.2.5.aar",
          "url": "adfit-sdk-3.17.2.5.aar",
          "size": 13837,
          "sha512": "d05ff77b07567538ab18a896dd6b0274d7a0b5ac0bf19ec6121080347861b0c31fe828a959fdaf8039af352fec79c4df2666f6ee1fdf08ae257d1500fda41c6d",
          "sha256": "61ec0634f34aa9231c350e4a59e2a323f3a493e180a03825c62c9b8b3e8fb613",
          "sha1": "fe60df0fe00079233f4fcfad601e33b342ce8196",
          "md5": "cfbd8180ba2c8ae9eac9d85576008089"
        }
      ]
    }
  ]
}
