{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk",
    "version": "8.7.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-8.7.0.8.aar",
          "url": "levelplay-sdk-8.7.0.8.aar",
          "size": 19008,
          "sha512": "c5f1fdb743fa82ddd36eb8ccf1879f05b9ff07379cb5bc2ddd8874d6e8d69f093b8c56e1fb703da630ce20dccd1532530c59212e422553ac65a88f314a49757b",
          "sha256": "48f8abb128febd1bcea054b64864fe885838b435a58a6ecbd47d086cb73d417f",
          "sha1": "383bf2207f84d03a007385d8dc4dc5963a41f2b9",
          "md5": "ed8c29d5a54bbc702919e3a4043bd30f"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-8.7.0.8.aar",
          "url": "levelplay-sdk-8.7.0.8.aar",
          "size": 19008,
          "sha512": "c5f1fdb743fa82ddd36eb8ccf1879f05b9ff07379cb5bc2ddd8874d6e8d69f093b8c56e1fb703da630ce20dccd1532530c59212e422553ac65a88f314a49757b",
          "sha256": "48f8abb128febd1bcea054b64864fe885838b435a58a6ecbd47d086cb73d417f",
          "sha1": "383bf2207f84d03a007385d8dc4dc5963a41f2b9",
          "md5": "ed8c29d5a54bbc702919e3a4043bd30f"
        }
      ]
    }
  ]
}
