{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk-uat",
    "version": "8.11.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-uat-8.11.0.0.aar",
          "url": "levelplay-sdk-uat-8.11.0.0.aar",
          "size": 56707,
          "sha512": "9e3fbcc6830d99fe870f3b348bbdd1880041e5ea1ccc9f54e001d0d01f2977abb687959dae5f52e1376c88cebbcabeeaf86c19b76c6b0c38370be9625cec7139",
          "sha256": "6f0f19486eeb21f47f6f355bbbd5893de89de8f8c1c08ecf42c790a184c25945",
          "sha1": "fe43f23a3e0b7b1dfce91b7b87d85f03724e604b",
          "md5": "e22ea25200f4414b7686ebdea991e988"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-uat-8.11.0.0.aar",
          "url": "levelplay-sdk-uat-8.11.0.0.aar",
          "size": 56707,
          "sha512": "9e3fbcc6830d99fe870f3b348bbdd1880041e5ea1ccc9f54e001d0d01f2977abb687959dae5f52e1376c88cebbcabeeaf86c19b76c6b0c38370be9625cec7139",
          "sha256": "6f0f19486eeb21f47f6f355bbbd5893de89de8f8c1c08ecf42c790a184c25945",
          "sha1": "fe43f23a3e0b7b1dfce91b7b87d85f03724e604b",
          "md5": "e22ea25200f4414b7686ebdea991e988"
        }
      ]
    }
  ]
}
