{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk",
    "version": "8.7.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-8.7.0.6.aar",
          "url": "levelplay-sdk-8.7.0.6.aar",
          "size": 48176,
          "sha512": "fba14723da565db74e838167fd39d909fd0256960c83419e1baede6b9649b7913b78c87d308cc7e91da9f14155b5d293dbd53430b728d713962923106afa3ddd",
          "sha256": "e6179545edb05a67970b10e614a9b9c0918bfafff339151fd705d3354bf3bc69",
          "sha1": "5d428e591bdea0477f814e594687df02932318db",
          "md5": "4614e38f992c1a8b774a4853e3ef3e7c"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-8.7.0.6.aar",
          "url": "levelplay-sdk-8.7.0.6.aar",
          "size": 48176,
          "sha512": "fba14723da565db74e838167fd39d909fd0256960c83419e1baede6b9649b7913b78c87d308cc7e91da9f14155b5d293dbd53430b728d713962923106afa3ddd",
          "sha256": "e6179545edb05a67970b10e614a9b9c0918bfafff339151fd705d3354bf3bc69",
          "sha1": "5d428e591bdea0477f814e594687df02932318db",
          "md5": "4614e38f992c1a8b774a4853e3ef3e7c"
        }
      ]
    }
  ]
}
