{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.levelplay.adapter",
    "module": "levelplay-sdk",
    "version": "8.7.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "levelplay-sdk-8.7.0.6.aar",
          "url": "levelplay-sdk-8.7.0.6.aar",
          "size": 48162,
          "sha512": "bc8ef2437f80b0e8aabd4f95aa23501fc4154abb8ed6631e11ab8d0ea07665d06deea462dbbbea7441601d20d85fcbfa6249a45851e3f900871e77488d1c2af3",
          "sha256": "9b3bbb673bd57f59834adc4f79cc192b0795e3674043df52d8bde5e85d3f2e7c",
          "sha1": "2e0aa7984c64048554cf5f781aef18a23790722d",
          "md5": "69643f7411419b067aef2b7b2745dfc9"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mediation-sdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "levelplay-sdk-8.7.0.6.aar",
          "url": "levelplay-sdk-8.7.0.6.aar",
          "size": 48162,
          "sha512": "bc8ef2437f80b0e8aabd4f95aa23501fc4154abb8ed6631e11ab8d0ea07665d06deea462dbbbea7441601d20d85fcbfa6249a45851e3f900871e77488d1c2af3",
          "sha256": "9b3bbb673bd57f59834adc4f79cc192b0795e3674043df52d8bde5e85d3f2e7c",
          "sha1": "2e0aa7984c64048554cf5f781aef18a23790722d",
          "md5": "69643f7411419b067aef2b7b2745dfc9"
        }
      ]
    }
  ]
}
