{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.cauly.adapter",
    "module": "cauly-sdk-uat",
    "version": "3.5.43.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.43.0.aar",
          "url": "cauly-sdk-uat-3.5.43.0.aar",
          "size": 45562,
          "sha512": "459c4d69a169dfab60a26e9c49b66279721902aecdb527ab18d20ecc1efc872ede3c1758ca58f495bb316fbb8732f2a74762aef1e65d152ad65a33531e3ebb47",
          "sha256": "f36646bca9552a068652f0dbb87409a823561b4e8955af544bd498eba6884a87",
          "sha1": "48abe94ce2a00ecd7e29f56e18a669e093cb140b",
          "md5": "fd5acc4315114ba9d9ee995aaa967f18"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "com.fsn.cauly",
          "module": "cauly-sdk-uat",
          "version": {
            "requires": "3.5.43"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.8.9"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.43.0.aar",
          "url": "cauly-sdk-uat-3.5.43.0.aar",
          "size": 45562,
          "sha512": "459c4d69a169dfab60a26e9c49b66279721902aecdb527ab18d20ecc1efc872ede3c1758ca58f495bb316fbb8732f2a74762aef1e65d152ad65a33531e3ebb47",
          "sha256": "f36646bca9552a068652f0dbb87409a823561b4e8955af544bd498eba6884a87",
          "sha1": "48abe94ce2a00ecd7e29f56e18a669e093cb140b",
          "md5": "fd5acc4315114ba9d9ee995aaa967f18"
        }
      ]
    }
  ]
}
