{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.cauly.adapter",
    "module": "cauly-sdk-uat",
    "version": "3.5.43.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.43.0.aar",
          "url": "cauly-sdk-uat-3.5.43.0.aar",
          "size": 45576,
          "sha512": "d041c20d59e11cdfbf80c215a272784f1adce29977a298d5e4c204ca673374a2858ff344cff68a88314f3db013a4c96bcef1b7352097e0b91c425995606f93e7",
          "sha256": "3357c3d540e8f684bc4c5d70a4c7f6655d3d06c8eb8ecb11209706ab96735a7b",
          "sha1": "b3ef7ca74855e2fa63fc35b7d1bfd2c5051d9064",
          "md5": "5b0de12172099a9790671a2ae39c256d"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "com.fsn.cauly",
          "module": "cauly-sdk-uat",
          "version": {
            "requires": "3.5.43"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.8.9"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.43.0.aar",
          "url": "cauly-sdk-uat-3.5.43.0.aar",
          "size": 45576,
          "sha512": "d041c20d59e11cdfbf80c215a272784f1adce29977a298d5e4c204ca673374a2858ff344cff68a88314f3db013a4c96bcef1b7352097e0b91c425995606f93e7",
          "sha256": "3357c3d540e8f684bc4c5d70a4c7f6655d3d06c8eb8ecb11209706ab96735a7b",
          "sha1": "b3ef7ca74855e2fa63fc35b7d1bfd2c5051d9064",
          "md5": "5b0de12172099a9790671a2ae39c256d"
        }
      ]
    }
  ]
}
