{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk",
    "version": "2.5.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.5.9.aar",
          "url": "adwhale-mediation-sdk-2.5.9.aar",
          "size": 84908,
          "sha512": "7aa9bbaa6d1b79ce92a2aec14d1ff667c32b515ee4c78fa24f6f09bfcec5ae8b8b40a52fabfb7815a2d22838c6a503b37a1a2d47cbb914452f9c44f9ea54d7f2",
          "sha256": "8bd0630b6c7e59201f050b42b3aa5bed8680b094d26a87c15d53f9721a99a9e4",
          "sha1": "3cdce63972f2dce7a853c63ae97b852cd52c19b6",
          "md5": "248be7dc10cc352efff17419fc455e6b"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.5.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.5.9.aar",
          "url": "adwhale-mediation-sdk-2.5.9.aar",
          "size": 84908,
          "sha512": "7aa9bbaa6d1b79ce92a2aec14d1ff667c32b515ee4c78fa24f6f09bfcec5ae8b8b40a52fabfb7815a2d22838c6a503b37a1a2d47cbb914452f9c44f9ea54d7f2",
          "sha256": "8bd0630b6c7e59201f050b42b3aa5bed8680b094d26a87c15d53f9721a99a9e4",
          "sha1": "3cdce63972f2dce7a853c63ae97b852cd52c19b6",
          "md5": "248be7dc10cc352efff17419fc455e6b"
        }
      ]
    }
  ]
}
