{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk",
    "version": "2.5.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.5.9.aar",
          "url": "adwhale-mediation-sdk-2.5.9.aar",
          "size": 85458,
          "sha512": "74d565199024adcc28ec2644d8b4fdd960e40302a2431880a2bd4c78b71d044a1c59fa08df9033d0eb99f36de903b9ccb0b04744e2a5543ab44bd3a1c4d1e113",
          "sha256": "32f5f44fabec1bc4f9cdca87eaa575af5dbe299f422dcecce64f21536fa511ce",
          "sha1": "42742b3da3d549b96a8a984f18d76f4ac758b5e7",
          "md5": "f1f4a7249405d3ddbe51ddff4e756ec3"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.5.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.5.9.aar",
          "url": "adwhale-mediation-sdk-2.5.9.aar",
          "size": 85458,
          "sha512": "74d565199024adcc28ec2644d8b4fdd960e40302a2431880a2bd4c78b71d044a1c59fa08df9033d0eb99f36de903b9ccb0b04744e2a5543ab44bd3a1c4d1e113",
          "sha256": "32f5f44fabec1bc4f9cdca87eaa575af5dbe299f422dcecce64f21536fa511ce",
          "sha1": "42742b3da3d549b96a8a984f18d76f4ac758b5e7",
          "md5": "f1f4a7249405d3ddbe51ddff4e756ec3"
        }
      ]
    }
  ]
}
