{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk",
    "version": "2.5.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.5.9.aar",
          "url": "adwhale-mediation-sdk-2.5.9.aar",
          "size": 85486,
          "sha512": "be4e86e764522aac1fbb9782153bbba101bcb390e570afcf40ff8eb68323e5fda167a436e6357711acbeb9fc9d84a905d7975dbb1160b9cb621157fc2676788a",
          "sha256": "77c02b80281c52168f4243020d087c4bf6c6ffdfeec79e9ff6088a9870226ebc",
          "sha1": "eb9d81cae4bc42f53aaa880ec61af6ff7cde6a2e",
          "md5": "866fbfb86a00cd37bda67124c2b21edc"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.5.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.5.9.aar",
          "url": "adwhale-mediation-sdk-2.5.9.aar",
          "size": 85486,
          "sha512": "be4e86e764522aac1fbb9782153bbba101bcb390e570afcf40ff8eb68323e5fda167a436e6357711acbeb9fc9d84a905d7975dbb1160b9cb621157fc2676788a",
          "sha256": "77c02b80281c52168f4243020d087c4bf6c6ffdfeec79e9ff6088a9870226ebc",
          "sha1": "eb9d81cae4bc42f53aaa880ec61af6ff7cde6a2e",
          "md5": "866fbfb86a00cd37bda67124c2b21edc"
        }
      ]
    }
  ]
}
