{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.core",
    "module": "adwhale-core-sdk",
    "version": "2.7.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "realReleaseVariantRealReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-core-sdk-2.7.6.aar",
          "url": "adwhale-core-sdk-2.7.6.aar",
          "size": 49131,
          "sha512": "935be15fd656fb20a7924cc43b1cbf4998a578214bd40a40059414e38d5a408336c73415630cd72fa983086e867282e93e28d138000706d8f0bead422358f930",
          "sha256": "fd918a16c9ab575f99a004e6128131defa6278c9bb8fd7e15bbd5c977b346a13",
          "sha1": "8d64465420415cb864eb4a7231d62879f13b79a5",
          "md5": "e20e9e75bafd7c10d03da912bab74a80"
        }
      ]
    },
    {
      "name": "realReleaseVariantRealReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-core-sdk-2.7.6.aar",
          "url": "adwhale-core-sdk-2.7.6.aar",
          "size": 49131,
          "sha512": "935be15fd656fb20a7924cc43b1cbf4998a578214bd40a40059414e38d5a408336c73415630cd72fa983086e867282e93e28d138000706d8f0bead422358f930",
          "sha256": "fd918a16c9ab575f99a004e6128131defa6278c9bb8fd7e15bbd5c977b346a13",
          "sha1": "8d64465420415cb864eb4a7231d62879f13b79a5",
          "md5": "e20e9e75bafd7c10d03da912bab74a80"
        }
      ]
    }
  ]
}
