{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk-uat",
    "version": "2.7.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.8.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.8.aar",
          "size": 212307,
          "sha512": "79e3a5c2b75fa5aabea748eb601c745cf38a7be07bc3e86d0b447857b8fe1bb7e7c0192acc52c650fc08b63384863885b9ceb19c1db58510623d27351659c754",
          "sha256": "3af1981cf2508e65c81dec36a62d47a0dbbde9ebd8ebf4a75408958970d1f4d1",
          "sha1": "fa1db81ebe54961adb05b1855670fe22d06cf2af",
          "md5": "e9d10c8ed1cfb2cf48e13fa6233c813f"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.8"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-uat-2.7.8.aar",
          "url": "adwhale-mediation-sdk-uat-2.7.8.aar",
          "size": 212307,
          "sha512": "79e3a5c2b75fa5aabea748eb601c745cf38a7be07bc3e86d0b447857b8fe1bb7e7c0192acc52c650fc08b63384863885b9ceb19c1db58510623d27351659c754",
          "sha256": "3af1981cf2508e65c81dec36a62d47a0dbbde9ebd8ebf4a75408958970d1f4d1",
          "sha1": "fa1db81ebe54961adb05b1855670fe22d06cf2af",
          "md5": "e9d10c8ed1cfb2cf48e13fa6233c813f"
        }
      ]
    }
  ]
}
