{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk-uat",
    "version": "3.17.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.3.aar",
          "url": "adfit-sdk-uat-3.17.2.3.aar",
          "size": 15608,
          "sha512": "68db9c1a456028f176a7d639685a3c40ed61ec475c3e32cb0aa0cc90d778342e3cdf58a5e1ca56039b52df30ca8f4ec7edb5642174535e09dd103e480d410dca",
          "sha256": "d0f4a27af15e2f0c060a10cf51a6f03bdc80d95e8db5ebd4c105382fca68bc46",
          "sha1": "15e55d9aa19d5b5f3c54dc575cdaec7c46b9c41f",
          "md5": "8508b69c1c41b45dc07126d475296f3a"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.3.aar",
          "url": "adfit-sdk-uat-3.17.2.3.aar",
          "size": 15608,
          "sha512": "68db9c1a456028f176a7d639685a3c40ed61ec475c3e32cb0aa0cc90d778342e3cdf58a5e1ca56039b52df30ca8f4ec7edb5642174535e09dd103e480d410dca",
          "sha256": "d0f4a27af15e2f0c060a10cf51a6f03bdc80d95e8db5ebd4c105382fca68bc46",
          "sha1": "15e55d9aa19d5b5f3c54dc575cdaec7c46b9c41f",
          "md5": "8508b69c1c41b45dc07126d475296f3a"
        }
      ]
    }
  ]
}
