{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk-uat",
    "version": "3.17.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.3.aar",
          "url": "adfit-sdk-uat-3.17.2.3.aar",
          "size": 15614,
          "sha512": "32a9416129c72e402f740c9281c540737e40183d91e7b15546f8baf1225948415058cf6434b78aad7702a84d3133d3f52829633398db38a294524d6e7e45506b",
          "sha256": "749ae1d2740244dc591f668c3eaf53d1c5837aee7f538b0631e9a646ff1a29d5",
          "sha1": "c1551005b6a9fe24060cc1d43b0ca9806302d3ba",
          "md5": "8ca8d8ba5b75c2a07e4b67d5ccfd54f3"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.3.aar",
          "url": "adfit-sdk-uat-3.17.2.3.aar",
          "size": 15614,
          "sha512": "32a9416129c72e402f740c9281c540737e40183d91e7b15546f8baf1225948415058cf6434b78aad7702a84d3133d3f52829633398db38a294524d6e7e45506b",
          "sha256": "749ae1d2740244dc591f668c3eaf53d1c5837aee7f538b0631e9a646ff1a29d5",
          "sha1": "c1551005b6a9fe24060cc1d43b0ca9806302d3ba",
          "md5": "8ca8d8ba5b75c2a07e4b67d5ccfd54f3"
        }
      ]
    }
  ]
}
