{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admize.adapter",
    "module": "admize-sdk-uat",
    "version": "1.0.5.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-uat-1.0.5.8.aar",
          "url": "admize-sdk-uat-1.0.5.8.aar",
          "size": 25811,
          "sha512": "21d3e70c7e71632f6f661ef573d342ea9661ebac8c24a3f66b2cb6d6369172e838e30068360849feb4eb8718f5c5f33a9afd15fc26131233402bb6f5c8af542b",
          "sha256": "f104c164399c86b30f443a04f0f3363a4726b58236dfe2fde6243c328ae8a08d",
          "sha1": "df29bec307effe1460c90e25e682c1426f4d5d9d",
          "md5": "861083f04201ee0e88ce2462a38e87a5"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "io.admize.sdk.android",
          "module": "admize-sdk-android-uat",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-uat-1.0.5.8.aar",
          "url": "admize-sdk-uat-1.0.5.8.aar",
          "size": 25811,
          "sha512": "21d3e70c7e71632f6f661ef573d342ea9661ebac8c24a3f66b2cb6d6369172e838e30068360849feb4eb8718f5c5f33a9afd15fc26131233402bb6f5c8af542b",
          "sha256": "f104c164399c86b30f443a04f0f3363a4726b58236dfe2fde6243c328ae8a08d",
          "sha1": "df29bec307effe1460c90e25e682c1426f4d5d9d",
          "md5": "861083f04201ee0e88ce2462a38e87a5"
        }
      ]
    }
  ]
}
