{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk-uat",
    "version": "3.17.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.6.aar",
          "url": "adfit-sdk-uat-3.17.2.6.aar",
          "size": 15947,
          "sha512": "9b23ab829bf4d000120b629387488601300aefccb1b257c558c1ffc012d655d04694aaa1ac0c825cb23416a5b778960ac07352179b2031f2a79e43a4a6e8593f",
          "sha256": "a5359befa64dc496e9819367cf77ad8b4d6f63fcbfb29fe1006a24f2fc0f65d5",
          "sha1": "6174dc65da7901efa6dcbb42c443b9ed7a29427a",
          "md5": "9b7d98529caff8ba3553f3c0aa09a39e"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.6.aar",
          "url": "adfit-sdk-uat-3.17.2.6.aar",
          "size": 15947,
          "sha512": "9b23ab829bf4d000120b629387488601300aefccb1b257c558c1ffc012d655d04694aaa1ac0c825cb23416a5b778960ac07352179b2031f2a79e43a4a6e8593f",
          "sha256": "a5359befa64dc496e9819367cf77ad8b4d6f63fcbfb29fe1006a24f2fc0f65d5",
          "sha1": "6174dc65da7901efa6dcbb42c443b9ed7a29427a",
          "md5": "9b7d98529caff8ba3553f3c0aa09a39e"
        }
      ]
    }
  ]
}
