{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk-uat",
    "version": "3.17.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.6.aar",
          "url": "adfit-sdk-uat-3.17.2.6.aar",
          "size": 15929,
          "sha512": "80cc051ea288c3ca473617b6073e14023b074bc1bbac5fb61b9888dfe44d8e71685a5e9ce3493179f071781ce626188b9a6ac02a85a9cd07a89f113799d45c14",
          "sha256": "1d81cbda89175ccbc536bb083688644a1d6783218b8ac8e926f602bf44d6b563",
          "sha1": "08fb7861c086f2e693d22aa505ce9a9568ccc30b",
          "md5": "e6804e1da4dd5d8b52359a79410e91d5"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.6.aar",
          "url": "adfit-sdk-uat-3.17.2.6.aar",
          "size": 15929,
          "sha512": "80cc051ea288c3ca473617b6073e14023b074bc1bbac5fb61b9888dfe44d8e71685a5e9ce3493179f071781ce626188b9a6ac02a85a9cd07a89f113799d45c14",
          "sha256": "1d81cbda89175ccbc536bb083688644a1d6783218b8ac8e926f602bf44d6b563",
          "sha1": "08fb7861c086f2e693d22aa505ce9a9568ccc30b",
          "md5": "e6804e1da4dd5d8b52359a79410e91d5"
        }
      ]
    }
  ]
}
