{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admize.adapter",
    "module": "admize-sdk-uat",
    "version": "1.0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-uat-1.0.5.1.aar",
          "url": "admize-sdk-uat-1.0.5.1.aar",
          "size": 25813,
          "sha512": "92227305c571b8386b04d99b1113867aa48ad7e46c3aab2bd122628e8f41f1779fa3df368f4eacd5533b6380e3316e4020b46a9c789f9b65d9553b0ba475e2b1",
          "sha256": "e79b1f9d1d229d5747e40ff6c8c7032d1989e3c91b7560916ae46d0b2fbe7f88",
          "sha1": "ff234e04ac24337fe0412143840484c329bde5b6",
          "md5": "f31c7a07d4626631ab58cc2e30b74481"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.5.9"
          }
        },
        {
          "group": "io.admize.sdk.android",
          "module": "admize-sdk-android-uat",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-uat-1.0.5.1.aar",
          "url": "admize-sdk-uat-1.0.5.1.aar",
          "size": 25813,
          "sha512": "92227305c571b8386b04d99b1113867aa48ad7e46c3aab2bd122628e8f41f1779fa3df368f4eacd5533b6380e3316e4020b46a9c789f9b65d9553b0ba475e2b1",
          "sha256": "e79b1f9d1d229d5747e40ff6c8c7032d1989e3c91b7560916ae46d0b2fbe7f88",
          "sha1": "ff234e04ac24337fe0412143840484c329bde5b6",
          "md5": "f31c7a07d4626631ab58cc2e30b74481"
        }
      ]
    }
  ]
}
