{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk",
    "version": "2.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.7.1.aar",
          "url": "adwhale-mediation-sdk-2.7.1.aar",
          "size": 99139,
          "sha512": "332c95f404057f481981fb80d2abf84f56bfe09bef65e8c9371207ab8e332b1986170be4752ee2e86cab7949591ec9aaf151c2d710e8e5a02d85478e66202227",
          "sha256": "5e8d907c4f712fba484e8ae8a0a9d4241cf8a376d73194172a632b1ae6c94167",
          "sha1": "45a372e87689656c5e7c364efeccf705bdbe0da0",
          "md5": "65a9d7d0d3f6d7d56eeb067a80c7b59d"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.7.1.aar",
          "url": "adwhale-mediation-sdk-2.7.1.aar",
          "size": 99139,
          "sha512": "332c95f404057f481981fb80d2abf84f56bfe09bef65e8c9371207ab8e332b1986170be4752ee2e86cab7949591ec9aaf151c2d710e8e5a02d85478e66202227",
          "sha256": "5e8d907c4f712fba484e8ae8a0a9d4241cf8a376d73194172a632b1ae6c94167",
          "sha1": "45a372e87689656c5e7c364efeccf705bdbe0da0",
          "md5": "65a9d7d0d3f6d7d56eeb067a80c7b59d"
        }
      ]
    }
  ]
}
