{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk-uat",
    "version": "3.21.17.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-uat-3.21.17.4.aar",
          "url": "adfit-sdk-uat-3.21.17.4.aar",
          "size": 28844,
          "sha512": "e3bcb49353a3a54c0d57fd39ce116cd741125b766b89e9ebaaf8ce32de77a8732d88091f1dce7e6748f82ad36c2b98e07c7d38ee79009eaf512c7afc0a78e3dc",
          "sha256": "d4bf680b0cee8954eb72bec860243d83b63f557806a3df6f3c5ebd6ac5fd7ce7",
          "sha1": "7291b6d0dd5964701264f019bc9c9ef288070857",
          "md5": "c2fc71fb555af8c8274472cf6dccb9de"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.21.17"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-uat-3.21.17.4.aar",
          "url": "adfit-sdk-uat-3.21.17.4.aar",
          "size": 28844,
          "sha512": "e3bcb49353a3a54c0d57fd39ce116cd741125b766b89e9ebaaf8ce32de77a8732d88091f1dce7e6748f82ad36c2b98e07c7d38ee79009eaf512c7afc0a78e3dc",
          "sha256": "d4bf680b0cee8954eb72bec860243d83b63f557806a3df6f3c5ebd6ac5fd7ce7",
          "sha1": "7291b6d0dd5964701264f019bc9c9ef288070857",
          "md5": "c2fc71fb555af8c8274472cf6dccb9de"
        }
      ]
    }
  ]
}
