{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk-uat",
    "version": "3.21.17.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-uat-3.21.17.5.aar",
          "url": "adfit-sdk-uat-3.21.17.5.aar",
          "size": 28845,
          "sha512": "54bc88c014791f4560ee56a8a14d89688c15c30e3cbf12e6f83ba0f16f8e0640713ce26230fa8e66cfd111a25cfe6c0d2e23a8c1d214563171d4926402e2e04f",
          "sha256": "9da6e4a064baf05dbd3f5d6af1d9e5495e2836df44f6894858f1a4fd90c10dd8",
          "sha1": "945bb97145947e65e8021e61c5528e7955c4a44b",
          "md5": "fe1d9f3768a796f71ca0a5f29cc96951"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.8"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.21.17"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-uat-3.21.17.5.aar",
          "url": "adfit-sdk-uat-3.21.17.5.aar",
          "size": 28845,
          "sha512": "54bc88c014791f4560ee56a8a14d89688c15c30e3cbf12e6f83ba0f16f8e0640713ce26230fa8e66cfd111a25cfe6c0d2e23a8c1d214563171d4926402e2e04f",
          "sha256": "9da6e4a064baf05dbd3f5d6af1d9e5495e2836df44f6894858f1a4fd90c10dd8",
          "sha1": "945bb97145947e65e8021e61c5528e7955c4a44b",
          "md5": "fe1d9f3768a796f71ca0a5f29cc96951"
        }
      ]
    }
  ]
}
