{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admize.adapter",
    "module": "admize-sdk",
    "version": "1.0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-1.0.7.0.aar",
          "url": "admize-sdk-1.0.7.0.aar",
          "size": 30732,
          "sha512": "5d7a893cda1144a5b2c84ba2983e8e18886a8ac5b0cd659dff8fa7d9ad89504cab219c26d7f55ed595daf8ea035119f247a003158cb25341cbc8d91da408376d",
          "sha256": "197236741334215228fe5d4fbf74fb911a2633e30ef43ea30837684d4c4e1f1c",
          "sha1": "d3713137d9cfc703b76763fc27d7f6297af67814",
          "md5": "d825f93f9aa805131e05493050785c2b"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.admize.sdk.android",
          "module": "admize-sdk-android",
          "version": {
            "requires": "1.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-1.0.7.0.aar",
          "url": "admize-sdk-1.0.7.0.aar",
          "size": 30732,
          "sha512": "5d7a893cda1144a5b2c84ba2983e8e18886a8ac5b0cd659dff8fa7d9ad89504cab219c26d7f55ed595daf8ea035119f247a003158cb25341cbc8d91da408376d",
          "sha256": "197236741334215228fe5d4fbf74fb911a2633e30ef43ea30837684d4c4e1f1c",
          "sha1": "d3713137d9cfc703b76763fc27d7f6297af67814",
          "md5": "d825f93f9aa805131e05493050785c2b"
        }
      ]
    }
  ]
}
