{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admize.adapter",
    "module": "admize-sdk",
    "version": "1.0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-1.0.7.0.aar",
          "url": "admize-sdk-1.0.7.0.aar",
          "size": 30728,
          "sha512": "49d25b6faeb1bb7e8979c242402a7ab10c9118029242c9c8c211b08b9cb5dd1f68d64dd0a204d48328da0d81f395494706907b6af097b4d7a8ec9247b9913502",
          "sha256": "0f31736dac0e83ea9fd37f05a90ec64fb7b6cd9589d92ed765615992b4ae440f",
          "sha1": "8fbc6fa06720be20304b03eb54a2c1f31733fb28",
          "md5": "20637067075d0b124df997f24a7a024e"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.admize.sdk.android",
          "module": "admize-sdk-android",
          "version": {
            "requires": "1.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-1.0.7.0.aar",
          "url": "admize-sdk-1.0.7.0.aar",
          "size": 30728,
          "sha512": "49d25b6faeb1bb7e8979c242402a7ab10c9118029242c9c8c211b08b9cb5dd1f68d64dd0a204d48328da0d81f395494706907b6af097b4d7a8ec9247b9913502",
          "sha256": "0f31736dac0e83ea9fd37f05a90ec64fb7b6cd9589d92ed765615992b4ae440f",
          "sha1": "8fbc6fa06720be20304b03eb54a2c1f31733fb28",
          "md5": "20637067075d0b124df997f24a7a024e"
        }
      ]
    }
  ]
}
