{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.mediation",
    "module": "adwhale-mediation-sdk",
    "version": "2.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.7.0.aar",
          "url": "adwhale-mediation-sdk-2.7.0.aar",
          "size": 98489,
          "sha512": "403879c5206e72c506fa4474090cd83df7ecbb508d13707848ed388d882da5293d6b4248380836777e36c878c6ec7053feab8cf627ac463a0a91905acaa766a2",
          "sha256": "5d356e6fac36d6efc065fa8622fa84100b627436bba28c6964395fdc409bb7bf",
          "sha1": "44b9003ad2ef100d8176c097acf249f22167757e",
          "md5": "3ba9334df392ffe2cbb528db9911517b"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex-instrumentation",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adwhale-mediation-sdk-2.7.0.aar",
          "url": "adwhale-mediation-sdk-2.7.0.aar",
          "size": 98489,
          "sha512": "403879c5206e72c506fa4474090cd83df7ecbb508d13707848ed388d882da5293d6b4248380836777e36c878c6ec7053feab8cf627ac463a0a91905acaa766a2",
          "sha256": "5d356e6fac36d6efc065fa8622fa84100b627436bba28c6964395fdc409bb7bf",
          "sha1": "44b9003ad2ef100d8176c097acf249f22167757e",
          "md5": "3ba9334df392ffe2cbb528db9911517b"
        }
      ]
    }
  ]
}
