{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.admob.adapter",
    "module": "admob-sdk-uat",
    "version": "24.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admob-sdk-uat-24.3.0.4.aar",
          "url": "admob-sdk-uat-24.3.0.4.aar",
          "size": 182304,
          "sha512": "f4f4fd1cc618abd6d369dafdfcae5d0e315c272cce02a0c08ef94280176ab9fb3fb193619b9db74de9dc0277b8b380cb0b79a4c2664fba4cf6a5473d37a142d0",
          "sha256": "15727ae5d4623d6c3cd3008462800d6b57e693bc0b279205e4d6ffcb7031f7ce",
          "sha1": "b6a049afcba9994e0449e4c2e3d629b149b3fa6a",
          "md5": "2be574c29e1f4c470fcbac9918404ef9"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "net.adwhale.sdk.cauly.adapter",
          "module": "cauly-sdk-uat",
          "version": {
            "requires": "3.5.44.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "admob-sdk-uat-24.3.0.4.aar",
          "url": "admob-sdk-uat-24.3.0.4.aar",
          "size": 182304,
          "sha512": "f4f4fd1cc618abd6d369dafdfcae5d0e315c272cce02a0c08ef94280176ab9fb3fb193619b9db74de9dc0277b8b380cb0b79a4c2664fba4cf6a5473d37a142d0",
          "sha256": "15727ae5d4623d6c3cd3008462800d6b57e693bc0b279205e4d6ffcb7031f7ce",
          "sha1": "b6a049afcba9994e0449e4c2e3d629b149b3fa6a",
          "md5": "2be574c29e1f4c470fcbac9918404ef9"
        }
      ]
    }
  ]
}
