{
  "formatVersion": "1.1",
  "component": {
    "group": "net.adwhale.sdk.adfit.adapter",
    "module": "adfit-sdk-uat",
    "version": "3.17.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.8.aar",
          "url": "adfit-sdk-uat-3.17.2.8.aar",
          "size": 8483,
          "sha512": "ac71cfbe87e797eff81edc5b3a766e5d3c53dcfe323c28d1feb688bea9daa2742dc3cb855cd8c42574aed6f7c97f581555eab40b36355c0c08f3f0fd8d03af4f",
          "sha256": "dabbcd1c8f00084af61f6d966030611407675bbab956e9a9be3c03876a662d54",
          "sha1": "453f03120add97238296dce7fc26588483d4d7c4",
          "md5": "6769dac2c1f0400ba83308ed4d0e146c"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.adwhale.sdk.core",
          "module": "adwhale-core-sdk-uat",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "adfit-sdk-uat-3.17.2.8.aar",
          "url": "adfit-sdk-uat-3.17.2.8.aar",
          "size": 8483,
          "sha512": "ac71cfbe87e797eff81edc5b3a766e5d3c53dcfe323c28d1feb688bea9daa2742dc3cb855cd8c42574aed6f7c97f581555eab40b36355c0c08f3f0fd8d03af4f",
          "sha256": "dabbcd1c8f00084af61f6d966030611407675bbab956e9a9be3c03876a662d54",
          "sha1": "453f03120add97238296dce7fc26588483d4d7c4",
          "md5": "6769dac2c1f0400ba83308ed4d0e146c"
        }
      ]
    }
  ]
}
